import { Course } from "@/types";

export const aiMlCourse: Course = {
  id: "course-ai-ml",
  slug: "ai-ml",
  title: "Artificial Intelligence & Machine Learning Engineering",
  tagline: "Neural networks, PyTorch, Large Language Models (LLMs), Embeddings, and RAG Architecture.",
  description: "From Python data foundations to cutting-edge GenAI: NumPy & Pandas dataframes, Supervised/Unsupervised Learning with Scikit-learn, Neural Networks & Deep Learning with PyTorch, LLM APIs, Vector Embeddings, Vector Databases (pgvector, Pinecone), and Retrieval-Augmented Generation (RAG).",
  category: "AI & Machine Learning",
  level: "Intermediate",
  estimatedHours: 32,
  icon: "Brain",
  badgeColor: "amber",
  prerequisites: ["Python Fundamentals", "Basic Linear Algebra"],
  skillsGained: [
    "NumPy Vectorized Computing & Pandas Data Wrangling",
    "Deep Learning Architectures & PyTorch Tensors",
    "Large Language Models (LLM) Prompt Engineering & APIs",
    "Vector Embeddings & Semantic Cosine Similarity Search",
    "Production Retrieval-Augmented Generation (RAG) Systems",
  ],
  featured: true,
  modules: [
    {
      id: "mod-ai-1",
      slug: "intro",
      title: "Module 1: AI & Machine Learning Foundations",
      description: "AI vs ML vs Deep Learning vs GenAI, datasets, training/test splits, and loss functions.",
      lessons: [
        {
          id: "ai-intro",
          slug: "ai-and-machine-learning-fundamentals",
          courseSlug: "ai-ml",
          moduleSlug: "intro",
          title: "AI & Machine Learning Foundations",
          description: "Understand the AI spectrum: Artificial Intelligence -> Machine Learning -> Deep Learning -> Generative AI.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "The distinction between Classical AI, Machine Learning, Deep Learning, and Generative AI",
            "Supervised (labeled data) vs Unsupervised (clustering) vs Reinforcement Learning",
            "Training, Validation, and Test dataset splitting (80/10/10 split)",
          ],
          introduction: `Machine Learning is a subset of Artificial Intelligence that focuses on building algorithms that learn from data and improve their performance over time without being explicitly programmed with hardcoded rules.`,
          whyItMatters: `Instead of writing 10,000 brittle if-else rules to recognize faces or detect fraud, ML models learn the underlying mathematical distributions directly from training datasets.`,
          mainExample: {
            title: "Supervised Learning Pipeline Flow",
            language: "text",
            code: `Raw Data -> Feature Extraction -> Train/Test Split (80/20) -> Model Training (Loss Optimization) -> Evaluation Metrics (Accuracy/F1) -> Inference Deployment`,
            takeaway: "Machine learning replaces procedural rules with data-driven statistical models.",
          },
          detailedExplanation: ["Overfitting occurs when a model memorizes training noise rather than generalizing to unseen test data."],
          commonMistakes: [],
          bestPractices: ["Always evaluate models on a strictly held-out test set that was never seen during training."],
          summary: ["Machine Learning turns data patterns into predictive algorithms."],
        },
      ],
    },
    {
      id: "mod-ai-2",
      slug: "numpy-pandas",
      title: "Module 2: Python Data Science Stack (NumPy & Pandas)",
      description: "NumPy vectorized n-dimensional arrays, matrix math, Pandas DataFrames, filtering, and aggregation.",
      lessons: [
        {
          id: "ai-numpy-pandas",
          slug: "numpy-and-pandas-data-wrangling",
          courseSlug: "ai-ml",
          moduleSlug: "numpy-pandas",
          title: "Vectorized Computing with NumPy & Pandas DataFrames",
          description: "Manipulate multi-dimensional numerical tensors with NumPy and clean tabular datasets with Pandas.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "NumPy ndarray vectorized math operations (100x faster than Python loops)",
            "Broadcasting rules and matrix multiplication (np.dot / @ operator)",
            "Pandas DataFrame filtering, grouping, and handling missing data (dropna, fillna)",
          ],
          introduction: `NumPy provides fast C-implemented contiguous arrays for numerical computing. Pandas builds on NumPy to provide labeled two-dimensional DataFrames for tabular data analysis.`,
          whyItMatters: `NumPy vectorized operations execute using SIMD CPU instructions, running 50x to 100x faster than standard Python for-loops.`,
          mainExample: {
            title: "NumPy Vectorization & Pandas DataFrame",
            language: "python",
            code: `import numpy as np\n\n# Vectorized matrix math\na = np.array([1.0, 2.0, 3.0])\nb = np.array([4.0, 5.0, 6.0])\n\ndot_product = np.dot(a, b)\nprint("Dot Product:", dot_product)\nprint(f"Vector Mean: {a.mean():.2f} | Standard Deviation: {a.std():.2f}")`,
            executable: true,
            explanation: ["np.dot calculates matrix inner product in hardware-optimized C routines."],
          },
          detailedExplanation: ["Pandas DataFrames provide SQL-like groupby(), join(), and pivot() transformations in Python."],
          commonMistakes: [],
          bestPractices: ["Avoid iterating over Pandas rows with for loops; always use vectorized expressions or .apply()."],
          summary: ["NumPy and Pandas are the foundational computing engine of data science and AI."],
        },
      ],
    },
    {
      id: "mod-ai-3",
      slug: "data-viz",
      title: "Module 3: Data Visualization & Exploratory Analysis",
      description: "Matplotlib plotting, Seaborn statistical heatmaps, feature correlations, and outlier detection.",
      lessons: [
        {
          id: "ai-visualization",
          slug: "exploratory-data-analysis-and-visualization",
          courseSlug: "ai-ml",
          moduleSlug: "data-viz",
          title: "Exploratory Data Analysis (EDA) & Visualization",
          description: "Discover hidden patterns, correlations, and data skew using Matplotlib and Seaborn statistical plots.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Scatter plots, histograms, and box plots for outlier detection",
            "Correlation heatmaps to identify multicollinear features",
            "Feature scaling: Min-Max Normalization vs Standard Z-Score Standardization",
          ],
          introduction: `Exploratory Data Analysis (EDA) is an approach to analyzing datasets to summarize their main characteristics, often with visual methods, before applying complex machine learning algorithms.`,
          whyItMatters: `Garbage in, garbage out: no machine learning algorithm can overcome uncleaned, biased, or highly skewed input data.`,
          mainExample: {
            title: "Z-Score Standardization Formula",
            language: "python",
            code: `import numpy as np\n\ndef standardize(data):\n    mean = np.mean(data)\n    std = np.std(data)\n    return (data - mean) / std\n\nraw_features = np.array([100.0, 200.0, 300.0, 400.0, 500.0])\nz_scaled = standardize(raw_features)\nprint("Standardized Features (Mean=0, Std=1):", np.round(z_scaled, 2))`,
            executable: true,
            explanation: ["Standardization scales features to have mean=0 and variance=1 for optimal gradient descent."],
          },
          detailedExplanation: ["Box plots visually identify outliers beyond 1.5x the Interquartile Range (IQR)."],
          commonMistakes: [],
          bestPractices: ["Always visualize the distribution of target variables before training."],
          summary: ["EDA and visualization uncover feature relationships and data anomalies."],
        },
      ],
    },
    {
      id: "mod-ai-4",
      slug: "supervised-learning",
      title: "Module 4: Supervised Learning (Regression & Classification)",
      description: "Linear Regression, Logistic Regression, Decision Trees, Random Forests, and Scikit-learn.",
      lessons: [
        {
          id: "ai-supervised",
          slug: "supervised-learning-with-scikit-learn",
          courseSlug: "ai-ml",
          moduleSlug: "supervised-learning",
          title: "Supervised Learning: Regression, Classification & Random Forests",
          description: "Train predictive models using Linear Regression, Logistic Regression, and Random Forest ensembles with Scikit-learn.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Linear Regression for continuous numerical predictions (housing prices)",
            "Logistic Regression for binary classification probabilities (fraud detection)",
            "Decision Trees and Random Forest ensembles for tabular data dominance",
          ],
          introduction: `Supervised Learning algorithms learn a mapping function from input features (X) to output labels (y) based on example pairs of inputs and outputs.`,
          whyItMatters: `Random Forests combine hundreds of randomized decision trees to produce robust predictions that resist individual tree overfitting.`,
          mainExample: {
            title: "Linear Regression Prediction Model",
            language: "python",
            code: `import numpy as np\n\n# Linear Model: y = weight * x + bias\nx = np.array([1.0, 2.0, 3.0, 4.0, 5.0])\ny = np.array([2.1, 3.9, 6.2, 8.0, 10.1])\n\n# Fit slope via ordinary least squares\nweight, bias = np.polyfit(x, y, 1)\nprint(f"Trained Model: y = {weight:.2f}x + {bias:.2f}")\n\n# Predict for x = 6\npredicted = weight * 6 + bias\nprint(f"Predicted value for x=6: {predicted:.2f}")`,
            executable: true,
            explanation: ["Calculates optimal weight and bias to minimize Mean Squared Error."],
          },
          detailedExplanation: ["Evaluation metrics: Use RMSE/MAE for regression and Precision/Recall/F1-Score for imbalanced classification."],
          commonMistakes: [],
          bestPractices: ["Never evaluate classification accuracy alone on imbalanced datasets (e.g. 99% non-fraud vs 1% fraud)."],
          summary: ["Supervised learning maps historical features to future numerical and categorical predictions."],
        },
      ],
    },
    {
      id: "mod-ai-5",
      slug: "unsupervised-learning",
      title: "Module 5: Unsupervised Learning & Clustering",
      description: "K-Means clustering, Principal Component Analysis (PCA) dimensionality reduction, and anomaly detection.",
      lessons: [
        {
          id: "ai-unsupervised",
          slug: "kmeans-and-pca-dimensionality-reduction",
          courseSlug: "ai-ml",
          moduleSlug: "unsupervised-learning",
          title: "K-Means Clustering & Dimensionality Reduction (PCA)",
          description: "Discover hidden customer segments with K-Means and compress high-dimensional feature spaces with PCA.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "K-Means clustering: centroid convergence algorithm and the Elbow Method for optimal K",
            "Principal Component Analysis (PCA) for reducing 100 features to 2D/3D visual embeddings",
            "Anomaly and fraud detection with Isolation Forests",
          ],
          introduction: `Unsupervised learning finds hidden patterns, groupings, and clusters in unlabeled data without predefined ground-truth target labels.`,
          whyItMatters: `K-Means clustering segments e-commerce users into behavioral cohorts (e.g. VIP shoppers vs bargain hunters) automatically.`,
          mainExample: {
            title: "Euclidean Distance Metric in Clustering",
            language: "python",
            code: `import numpy as np\n\ndef euclidean_dist(p1, p2):\n    return np.sqrt(np.sum((p1 - p2) ** 2))\n\nuser_point = np.array([25.0, 50000.0]) # Age, Income\ncluster_center = np.array([28.0, 52000.0])\n\nprint("Distance to Cluster Center:", euclidean_dist(user_point, cluster_center))`,
            executable: true,
            explanation: ["K-Means iteratively assigns points to the nearest centroid using Euclidean distance."],
          },
          detailedExplanation: ["PCA calculates eigenvectors of the covariance matrix to project data onto axes of maximum variance."],
          commonMistakes: [],
          bestPractices: ["Always standardize features before running K-Means or PCA so high-magnitude numbers don't dominate distance."],
          summary: ["Unsupervised learning discovers natural groupings and structures in unlabeled datasets."],
        },
      ],
    },
    {
      id: "mod-ai-6",
      slug: "neural-networks",
      title: "Module 6: Neural Networks & Deep Learning Basics",
      description: "Artificial neurons, Perceptrons, activation functions (ReLU, Sigmoid), forward pass, and backpropagation.",
      lessons: [
        {
          id: "ai-neural-nets",
          slug: "artificial-neurons-and-backpropagation",
          courseSlug: "ai-ml",
          moduleSlug: "neural-networks",
          title: "Artificial Neurons, Activation Functions & Backpropagation",
          description: "Understand the mathematical mechanics of deep learning: weights, biases, ReLU, and Gradient Descent backpropagation.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Mathematical model of an artificial neuron (y = σ(W·X + b))",
            "Why non-linear activation functions (ReLU, GELU, Softmax) are mandatory for deep networks",
            "Gradient Descent and Backpropagation using the calculus Chain Rule",
          ],
          introduction: `Deep Learning is a branch of machine learning based on Artificial Neural Networks with representation learning. The adjective 'deep' refers to the use of multiple layers in the network.`,
          whyItMatters: `Without non-linear activation functions like ReLU (max(0, x)), a 100-layer neural network collapses into a simple 1-layer linear regression model.`,
          mainExample: {
            title: "Single Artificial Neuron Computation",
            language: "python",
            code: `import numpy as np\n\ndef relu(z):\n    return np.maximum(0, z)\n\n# Inputs, Weights, Bias\nx = np.array([0.5, -0.2, 0.8])\nw = np.array([0.4, 0.9, -0.3])\nbias = 0.1\n\nz = np.dot(w, x) + bias\nactivation = relu(z)\n\nprint(f"Linear z: {z:.3f} | ReLU Output: {activation:.3f}")`,
            executable: true,
            explanation: ["Calculates dot product of weights and inputs, adds bias, and passes through ReLU."],
          },
          detailedExplanation: ["Backpropagation computes the gradient of the loss function with respect to every weight using the chain rule."],
          commonMistakes: [],
          bestPractices: ["Use ReLU for hidden layers and Softmax for multi-class classification output layers."],
          summary: ["Neural networks learn non-linear hierarchical representations through backpropagation."],
        },
      ],
    },
    {
      id: "mod-ai-7",
      slug: "pytorch",
      title: "Module 7: Deep Learning with PyTorch",
      description: "PyTorch Tensors, GPU acceleration (CUDA), torch.nn.Module, loss functions, and Adam optimizer.",
      lessons: [
        {
          id: "ai-pytorch",
          slug: "pytorch-tensors-and-nn-module",
          courseSlug: "ai-ml",
          moduleSlug: "pytorch",
          title: "PyTorch Tensors, Autograd & Building nn.Module Networks",
          description: "Construct deep neural networks using PyTorch, perform automatic differentiation (autograd), and train models on GPUs.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "PyTorch Tensors and transferring to GPU (tensor.to('cuda'))",
            "Automatic differentiation with loss.backward()",
            "Building modular architectures with torch.nn.Module and torch.optim.Adam",
          ],
          introduction: `PyTorch is the premier open-source machine learning framework used by Meta, OpenAI, Tesla, and top AI research institutions worldwide.`,
          whyItMatters: `PyTorch's dynamic computational graph (imperative execution) allows debugging neural networks line-by-line just like standard Python.`,
          mainExample: {
            title: "PyTorch Neural Network Class Definition",
            language: "python",
            code: `# Conceptual PyTorch Architecture Blueprint\nimport numpy as np\n\nclass MultiLayerPerceptron:\n    def __init__(self, input_dim, hidden_dim, output_dim):\n        self.w1 = np.random.randn(input_dim, hidden_dim) * 0.01\n        self.w2 = np.random.randn(hidden_dim, output_dim) * 0.01\n        \n    def forward(self, x):\n        h = np.maximum(0, np.dot(x, self.w1)) # Layer 1 + ReLU\n        out = np.dot(h, self.w2)               # Layer 2\n        return out\n\nmlp = MultiLayerPerceptron(4, 16, 2)\nprint("MultiLayerPerceptron Initialized.")`,
            executable: true,
            explanation: ["Forward pass propagates input through hidden layers to produce logits."],
          },
          detailedExplanation: ["The training loop iterates: Zero Gradients -> Forward Pass -> Compute Loss -> Backward Pass -> Optimizer Step."],
          commonMistakes: [],
          bestPractices: ["Always call optimizer.zero_grad() before loss.backward() in PyTorch."],
          summary: ["PyTorch provides high-performance tensor computing and automatic differentiation."],
        },
      ],
    },
    {
      id: "mod-ai-8",
      slug: "nlp-transformers",
      title: "Module 8: Natural Language Processing & Transformers",
      description: "Tokenization, self-attention mechanism, transformer architecture (Encoder/Decoder), and BERT vs GPT.",
      lessons: [
        {
          id: "ai-transformers",
          slug: "transformers-and-self-attention",
          courseSlug: "ai-ml",
          moduleSlug: "nlp-transformers",
          title: "The Transformer Architecture & Self-Attention Mechanism",
          description: "Understand the 'Attention Is All You Need' paper: Query, Key, Value matrices, Multi-Head Self-Attention, and positional encodings.",
          durationMinutes: 24,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Why recurrent networks (RNNs/LSTMs) were replaced by parallelizable Transformers",
            "Scaled Dot-Product Attention: Attention(Q, K, V) = softmax(QKᵀ / √dₖ) V",
            "Encoder-only (BERT), Decoder-only (GPT), and Encoder-Decoder (T5) models",
          ],
          introduction: `The Transformer architecture (Vaswani et al., 2017) revolutionized AI by allowing models to attend to all words in a sentence simultaneously in parallel rather than processing sequentially.`,
          whyItMatters: `Self-attention enables models to understand that in 'The animal didn't cross the street because it was too tired', the word 'it' refers to 'animal'.`,
          mainExample: {
            title: "Scaled Dot-Product Attention Formula",
            language: "python",
            code: `import numpy as np\n\ndef softmax(x):\n    e_x = np.exp(x - np.max(x))\n    return e_x / e_x.sum(axis=-1, keepdims=True)\n\ndef self_attention(Q, K, V):\n    d_k = Q.shape[-1]\n    scores = np.dot(Q, K.T) / np.sqrt(d_k)\n    attention_weights = softmax(scores)\n    return np.dot(attention_weights, V)\n\nprint("Self-Attention calculates contextual importance weights across all tokens.")`,
            executable: true,
            explanation: ["Calculates similarity between Query and Key matrices, scaled by square root of dimension."],
          },
          detailedExplanation: ["Positional encodings inject token sequence order information since self-attention is permutation-invariant."],
          commonMistakes: [],
          bestPractices: ["Understand the distinction between encoder models (embeddings) and decoder models (text generation)."],
          summary: ["Transformers and self-attention are the foundational architecture behind all modern Large Language Models."],
        },
      ],
    },
    {
      id: "mod-ai-9",
      slug: "llms-prompts",
      title: "Module 9: Large Language Models (LLMs) & Prompt Engineering",
      description: "Autoregressive text generation, temperature, top-p sampling, Few-Shot prompting, and Chain-of-Thought (CoT).",
      lessons: [
        {
          id: "ai-llms",
          slug: "llm-apis-and-prompt-engineering",
          courseSlug: "ai-ml",
          moduleSlug: "llms-prompts",
          title: "LLM APIs, Sampling Parameters & Prompt Engineering",
          description: "Master modern LLM APIs, sampling parameters (temperature, top_p), System prompts, and Few-Shot Chain-of-Thought reasoning.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How Autoregressive LLMs predict the next token probability distribution",
            "Controlling randomness: Temperature (0.0 = deterministic, 1.0 = creative) and top_p",
            "Advanced prompt techniques: Few-Shot In-Context Learning and Chain-of-Thought (CoT)",
          ],
          introduction: `Large Language Models (LLMs) are deep neural networks trained on vast corpora of internet text to generate human-quality text, write code, and perform multi-step reasoning.`,
          whyItMatters: `Prompt engineering (adding structured instructions and few-shot examples) can boost model reasoning accuracy on complex tasks from 40% to over 85%.`,
          mainExample: {
            title: "Structured LLM Prompt Template",
            language: "text",
            code: `System: You are an expert code reviewer specializing in high-performance TypeScript.\n\nUser: Analyze this function for potential memory leaks.\nProvide recommendations in valid JSON schema format:\n{\n  "hasLeak": boolean,\n  "explanation": string,\n  "fix": string\n}\n\nAssistant:`,
            takeaway: "Providing explicit JSON schema templates forces structured, parseable LLM outputs.",
          },
          detailedExplanation: ["Temperature 0.0 selects the argmax most probable token, ideal for deterministic code generation and SQL extraction."],
          commonMistakes: [],
          bestPractices: ["Use system messages to establish role boundaries and enforce structured JSON output."],
          summary: ["Disciplined prompt engineering and parameter tuning extract peak capability from LLMs."],
        },
      ],
    },
    {
      id: "mod-ai-10",
      slug: "vector-databases",
      title: "Module 10: Vector Embeddings & Vector Databases (pgvector, Pinecone)",
      description: "Dense vector representations, cosine distance vs dot product, pgvector PostgreSQL extension, and HNSW indexes.",
      lessons: [
        {
          id: "ai-embeddings",
          slug: "vector-embeddings-and-pgvector",
          courseSlug: "ai-ml",
          moduleSlug: "vector-databases",
          title: "Vector Embeddings & Vector Databases (pgvector)",
          description: "Convert unstructured text into mathematical vector embeddings and execute nearest neighbor searches with pgvector.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Dense vector embeddings (e.g. 1536-dimensional float arrays)",
            "Distance metrics: Cosine Similarity, Euclidean Distance (L2), Dot Product",
            "Storing and indexing vectors in PostgreSQL using the pgvector HNSW index",
          ],
          introduction: `Vector embeddings transform words, sentences, and documents into high-dimensional numerical vectors where semantically similar texts are placed close together in vector space.`,
          whyItMatters: `Vector search finds relevant answers even when the user uses completely different vocabulary ('car' matches 'automobile' and 'vehicle').`,
          mainExample: {
            title: "Semantic Cosine Similarity Calculation",
            language: "python",
            code: `import numpy as np\n\ndef cosine_similarity(v1, v2):\n    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))\n\nv_html = np.array([0.90, 0.15, 0.05])\nv_css = np.array([0.88, 0.18, 0.04])\nv_quantum = np.array([0.05, 0.85, 0.70])\n\nprint("HTML vs CSS Similarity:", cosine_similarity(v_html, v_css))\nprint("HTML vs Quantum Similarity:", cosine_similarity(v_html, v_quantum))`,
            executable: true,
            explanation: ["Calculates angle cosine: 1.0 means identical semantic meaning; 0.0 means unrelated."],
          },
          detailedExplanation: ["HNSW (Hierarchical Navigable Small World) indexes perform Approximate Nearest Neighbor (ANN) search in O(log n) time."],
          commonMistakes: [],
          bestPractices: ["Normalize vectors to unit length to make Dot Product equivalent to Cosine Similarity for 3x faster GPU searches."],
          summary: ["Vector embeddings and vector databases enable semantic AI search across billions of documents."],
        },
      ],
    },
    {
      id: "mod-ai-11",
      slug: "rag-architecture",
      title: "Module 11: Retrieval-Augmented Generation (RAG) Architecture",
      description: "Document ingestion pipelines, chunking strategies, semantic retrieval, context re-ranking, and hallucination reduction.",
      lessons: [
        {
          id: "ai-rag-intro",
          slug: "ai-and-rag-introduction",
          courseSlug: "ai-ml",
          moduleSlug: "rag-architecture",
          title: "Production Retrieval-Augmented Generation (RAG) Systems",
          description: "Build enterprise RAG pipelines that ground LLM answers in private documentation with zero hallucinations.",
          durationMinutes: 24,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The 5-step RAG pipeline: Ingestion -> Chunking -> Embedding -> Retrieval -> Generation",
            "Chunking strategies: Recursive character splitters with 10% overlap",
            "Context injection and citing factual source references",
          ],
          introduction: `Retrieval-Augmented Generation (RAG) is the process of optimizing the output of an LLM by referencing an authoritative knowledge base outside of its training data sources before generating a response.`,
          whyItMatters: `RAG allows AI applications to answer questions on proprietary company docs, private codebase repos, and live real-time news with citations without expensive fine-tuning.`,
          mainExample: {
            title: "Production RAG Query Flow",
            language: "python",
            code: `def rag_query(user_question):\n    # 1. Embed query\n    # 2. Vector DB search top 3 chunks\n    # 3. Augment prompt with context\n    context = "KWAS Academy provides 20+ free comprehensive software engineering courses."\n    prompt = f"Context:\\n{context}\\n\\nQuestion: {user_question}\\nAnswer based strictly on context:"\n    return f"[LLM Response generated from grounded context: {prompt}]"\n\nprint(rag_query("What does KWAS Academy provide?"))`,
            executable: true,
            explanation: ["Grounding the prompt on retrieved context eliminates hallucinations."],
          },
          detailedExplanation: ["Hybrid search combines traditional BM25 keyword search with dense vector semantic search for peak retrieval accuracy."],
          commonMistakes: [],
          bestPractices: ["Always include document metadata (filename, page number, url) with chunk embeddings for automated citations."],
          summary: ["RAG architecture delivers reliable, factual, and hallucination-free generative AI applications."],
        },
      ],
    },
  ],
};
