import { Course } from "@/types";

export const cppCourse: Course = {
  id: "course-cpp",
  slug: "cpp",
  title: "C++ High-Performance Systems Engineering",
  tagline: "Master memory pointers, RAII, templates, STL containers, and modern C++20 standards.",
  description: "Deep dive into C++: manual memory management, raw pointers vs smart pointers (std::unique_ptr, std::shared_ptr), RAII idioms, Object-Oriented design, Operator overloading, Templates, and the Standard Template Library (STL).",
  category: "Programming Languages",
  level: "Advanced",
  estimatedHours: 30,
  icon: "Cpu",
  badgeColor: "blue",
  prerequisites: ["Basic Programming Logic"],
  skillsGained: [
    "Direct Memory Addressing & Pointer Arithmetic",
    "Modern Smart Pointers & RAII Resource Management",
    "C++ Standard Template Library (vector, unordered_map, algorithm)",
    "Template Metaprogramming & Concepts (C++20)",
    "High-Performance Low-Latency Systems Optimization",
  ],
  featured: false,
  modules: [
    {
      id: "mod-cpp-1",
      slug: "intro",
      title: "Module 1: C++ Overview & Compilation Process",
      description: "Preprocessing, compilation, assembly, linking, and the main() entry point.",
      lessons: [
        {
          id: "cpp-intro",
          slug: "cpp-introduction",
          courseSlug: "cpp",
          moduleSlug: "intro",
          title: "C++ Introduction & The Compilation Toolchain",
          description: "Understand the C++ compilation pipeline (Preprocessor, Compiler, Linker) and standard I/O.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Direct machine code compilation vs runtime interpreters",
            "The 4 compilation stages (Preprocessing, Compilation, Assembly, Linking)",
            "Standard I/O with std::cout, std::cin, and header includes",
          ],
          introduction: `C++ is a high-performance compiled language that provides low-level memory control alongside powerful object-oriented and generic abstractions.`,
          whyItMatters: `C++ powers game engines (Unreal Engine), operating systems (Windows, macOS kernels), database engines, and high-frequency trading platforms.`,
          mainExample: {
            title: "C++20 Main Function & Stream Output",
            language: "cpp",
            code: `#include <iostream>\n\nint main() {\n    std::cout << "KWAS Academy: C++20 Systems Engineering" << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: ["std::cout outputs text to standard console output stream."],
          },
          detailedExplanation: ["C++ compiles directly to CPU instructions with zero virtual machine overhead."],
          commonMistakes: [],
          bestPractices: ["Always compile with -Wall -Wextra to catch potential bugs early."],
          summary: ["C++ delivers unmatched performance and direct hardware control."],
        },
      ],
    },
    {
      id: "mod-cpp-2",
      slug: "types-memory",
      title: "Module 2: Variables, Types & Memory Footprint",
      description: "Fundamental types, sizeof, type casting (static_cast), and memory alignment.",
      lessons: [
        {
          id: "cpp-types",
          slug: "primitive-types-and-sizeof",
          courseSlug: "cpp",
          moduleSlug: "types-memory",
          title: "Data Types, sizeof & Type Casting (static_cast)",
          description: "Inspect byte sizes of fundamental types with sizeof and perform safe type conversions with static_cast.",
          durationMinutes: 14,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Exact bit-width types (int32_t, int64_t, size_t) from <cstdint>",
            "Inspecting memory footprint with sizeof",
            "Modern C++ explicit type casting with static_cast<T>(val)",
          ],
          introduction: `In C++, every variable has an exact byte size in memory determined by the compiler and CPU architecture.`,
          whyItMatters: `Using C-style casts (int)val bypasses type safety. static_cast checks conversions at compile time.`,
          mainExample: {
            title: "Memory Sizing & Safe Casting",
            language: "cpp",
            code: `#include <iostream>\n#include <cstdint>\n\nint main() {\n    int32_t count = 42;\n    double ratio = static_cast<double>(count) / 10.0;\n    std::cout << "Size of int32: " << sizeof(count) << " bytes" << std::endl;\n    std::cout << "Ratio: " << ratio << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: ["sizeof(count) outputs 4 bytes."],
          },
          detailedExplanation: ["Memory alignment rules ensure variables align to CPU cache boundaries."],
          commonMistakes: [],
          bestPractices: ["Always prefer static_cast over C-style parenthetical casts."],
          summary: ["Precise byte control allows C++ systems to optimize hardware utilization."],
        },
      ],
    },
    {
      id: "mod-cpp-3",
      slug: "pointers-references",
      title: "Module 3: Pointers, References & Pointer Arithmetic",
      description: "Address-of operator (&), dereference (*), raw pointers, references (Type&), and pointer arithmetic.",
      lessons: [
        {
          id: "cpp-pointers",
          slug: "pointers-and-references",
          courseSlug: "cpp",
          moduleSlug: "pointers-references",
          title: "Memory Addresses, Pointers & References",
          description: "Master direct memory addressing (&), pointer dereferencing (*), null pointers (nullptr), and references.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "How pointers store memory addresses of variables",
            "Dereferencing pointers to mutate underlying memory (*ptr = val)",
            "References (const Type&) for zero-copy function parameter passing",
          ],
          introduction: `A pointer is a variable that stores the memory address of another variable. References provide safe aliases to existing variables without nullability risks.`,
          whyItMatters: `Passing 1MB objects by value makes an expensive copy. Passing by const reference (const BigObject&) takes 0 copies (8 bytes pointer).`,
          mainExample: {
            title: "Pointer & Reference Manipulation",
            language: "cpp",
            code: `#include <iostream>\n\nvoid increment(int& ref) { ref += 1; }\n\nint main() {\n    int value = 10;\n    int* ptr = &value;\n    *ptr = 20; // Mutate via pointer\n    increment(value); // Mutate via reference\n    std::cout << "Final Value: " << value << " at address: " << ptr << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: ["*ptr modifies the memory at address &value."],
          },
          detailedExplanation: ["Always use nullptr instead of NULL or 0 for uninitialized pointers."],
          commonMistakes: [],
          bestPractices: ["Pass large structs and vectors by const reference (const std::vector<int>&)."],
          summary: ["Pointers and references give direct control over computer memory."],
        },
      ],
    },
    {
      id: "mod-cpp-4",
      slug: "stack-heap",
      title: "Module 4: Stack vs Heap & Dynamic Memory",
      description: "Stack allocation speed, dynamic heap allocation (new/delete), memory fragmentation, and leaks.",
      lessons: [
        {
          id: "cpp-memory",
          slug: "stack-vs-heap-allocation",
          courseSlug: "cpp",
          moduleSlug: "stack-heap",
          title: "Stack vs Heap Allocation & Lifetime Mechanics",
          description: "Understand CPU stack frame allocation vs heap dynamic allocation, and the risks of memory leaks.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Stack memory: LIFO order, nanosecond allocation speed, automatic cleanup",
            "Heap memory: dynamic size, manual lifetime management",
            "Why forgetting 'delete' causes permanent memory leaks",
          ],
          introduction: `Variables declared inside functions live on the CPU Stack and are destroyed automatically when the function returns. Dynamic Heap memory persists until explicitly deleted.`,
          whyItMatters: `Allocating on the stack is literally just moving the CPU stack pointer register (1 CPU instruction). Heap allocation requires OS kernel memory search.`,
          mainExample: {
            title: "Stack vs Heap Lifetime",
            language: "cpp",
            code: `#include <iostream>\n\nint main() {\n    // Stack Allocation (Fast & Auto-Cleaned)\n    int stackVal = 100;\n\n    // Heap Allocation (Dynamic)\n    int* heapVal = new int(200);\n    std::cout << "Stack: " << stackVal << " | Heap: " << *heapVal << std::endl;\n    delete heapVal; // Must free heap memory\n    return 0;\n}`,
            executable: true,
            explanation: ["Stack memory cleans up on exit; heap requires explicit deletion."],
          },
          detailedExplanation: ["Dangling pointers occur when referencing heap memory after delete has already executed."],
          commonMistakes: [],
          bestPractices: ["Prefer stack allocation whenever object size is known at compile time."],
          summary: ["Stack and heap offer complementary memory allocation tradeoffs."],
        },
      ],
    },
    {
      id: "mod-cpp-5",
      slug: "smart-pointers",
      title: "Module 5: RAII & Smart Pointers (unique_ptr, shared_ptr)",
      description: "Resource Acquisition Is Initialization (RAII), std::unique_ptr, std::shared_ptr, and std::weak_ptr.",
      lessons: [
        {
          id: "cpp-smart-pointers",
          slug: "raii-and-smart-pointers",
          courseSlug: "cpp",
          moduleSlug: "smart-pointers",
          title: "RAII & Smart Pointers (std::unique_ptr, std::shared_ptr)",
          description: "Eliminate memory leaks forever using RAII smart pointers from the modern C++ <memory> header.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The RAII Idiom: Binding resource lifetime to object lifetime",
            "std::unique_ptr for exclusive ownership (zero runtime overhead)",
            "std::shared_ptr for reference-counted shared ownership",
          ],
          introduction: `RAII (Resource Acquisition Is Initialization) is the core design philosophy of modern C++. Destructors automatically release memory, database locks, and file handles when variables go out of scope.`,
          whyItMatters: `Using std::make_unique eliminates 100% of manual 'delete' calls, preventing memory leaks even if exceptions are thrown.`,
          mainExample: {
            title: "Safe RAII with std::unique_ptr",
            language: "cpp",
            code: `#include <iostream>\n#include <memory>\n\nstruct Resource {\n    Resource() { std::cout << "Resource Acquired" << std::endl; }\n    ~Resource() { std::cout << "Resource Destroyed (Auto RAII)" << std::endl; }\n};\n\nint main() {\n    {\n        auto ptr = std::make_unique<Resource>();\n    } // Destructor runs automatically here!\n    std::cout << "Exited scope safely." << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: ["unique_ptr destructor cleans up the Resource when leaving the block scope."],
          },
          detailedExplanation: ["std::make_unique has zero memory overhead compared to raw pointers."],
          commonMistakes: [],
          bestPractices: ["Never use raw 'new' and 'delete' in modern C++; use std::make_unique."],
          summary: ["Smart pointers bring effortless memory safety to modern C++."],
        },
      ],
    },
    {
      id: "mod-cpp-6",
      slug: "classes-oop",
      title: "Module 6: Classes, Constructors & Destructors",
      description: "Class declaration, constructor initializer lists, destructors (~Class), and const member methods.",
      lessons: [
        {
          id: "cpp-classes",
          slug: "classes-and-constructors",
          courseSlug: "cpp",
          moduleSlug: "classes-oop",
          title: "Classes, Initializer Lists & Destructors",
          description: "Design efficient C++ classes using member initializer lists, rule of zero, and const correctness.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Member initializer list syntax (: member(val)) for direct construction",
            "Class Destructors (~Class()) for resource cleanup",
            "Const member methods (void getInfo() const) preventing accidental mutations",
          ],
          introduction: `Classes in C++ encapsulate data members and member functions. Initializer lists initialize members directly before the constructor body executes.`,
          whyItMatters: `Initializing members in initializer lists avoids constructing default objects only to overwrite them inside the constructor body.`,
          mainExample: {
            title: "C++ Class with Initializer List",
            language: "cpp",
            code: `#include <iostream>\n#include <string>\n\nclass Engine {\nprivate:\n    std::string name;\n    int horsepower;\npublic:\n    Engine(std::string n, int hp) : name(std::move(n)), horsepower(hp) {}\n    int getHP() const { return horsepower; }\n};\n\nint main() {\n    Engine v8("V8 Twin Turbo", 650);\n    std::cout << "Horsepower: " << v8.getHP() << " HP" << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: [": name(std::move(n)), horsepower(hp) initializes members directly."],
          },
          detailedExplanation: ["Methods marked 'const' can be safely called on const instances of the class."],
          commonMistakes: [],
          bestPractices: ["Always use member initializer lists instead of assignments inside constructor bodies."],
          summary: ["Initializer lists and const correctness produce efficient, predictable C++ classes."],
        },
      ],
    },
    {
      id: "mod-cpp-7",
      slug: "move-semantics",
      title: "Module 7: Operator Overloading & Copy/Move Semantics",
      description: "Lvalue vs Rvalue references (&&), std::move, copy constructor, move constructor, and Rule of 5.",
      lessons: [
        {
          id: "cpp-move",
          slug: "move-semantics-and-rvalues",
          courseSlug: "cpp",
          moduleSlug: "move-semantics",
          title: "Move Semantics, Rvalues (&&) & The Rule of 5",
          description: "Steal resources from temporary rvalues without expensive deep copies using move constructors (Type(Type&&)).",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Lvalues (named variables) vs Rvalues (temporary expressions)",
            "Move constructor and move assignment operator with std::move",
            "The Rule of 5 (Destructor, Copy Ctor, Copy Assign, Move Ctor, Move Assign)",
          ],
          introduction: `Move semantics (introduced in C++11) allows objects to transfer ownership of resources (like dynamic heap buffers) from temporary objects without performing deep memory copies.`,
          whyItMatters: `Moving a 1GB vector takes 3 pointer copies (nanoseconds) instead of allocating and copying 1GB of memory!`,
          mainExample: {
            title: "Move Semantics with std::move",
            language: "cpp",
            code: `#include <iostream>\n#include <vector>\n#include <utility>\n\nint main() {\n    std::vector<int> bigVector(100000, 42);\n    // Transfer ownership of internal pointer without copying elements\n    std::vector<int> destination = std::move(bigVector);\n    \n    std::cout << "Destination size: " << destination.size() << std::endl;\n    std::cout << "Original size after move: " << bigVector.size() << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: ["std::move casts bigVector to an rvalue, allowing destination to steal its memory buffer."],
          },
          detailedExplanation: ["After a move, the source object is left in a valid but unspecified empty state."],
          commonMistakes: [],
          bestPractices: ["Follow the Rule of Zero: let smart pointers and STL containers handle copying and moving automatically."],
          summary: ["Move semantics eliminated the performance penalty of returning large objects by value."],
        },
      ],
    },
    {
      id: "mod-cpp-8",
      slug: "templates",
      title: "Module 8: Templates & Metaprogramming",
      description: "Function templates, class templates, template specialization, and compile-time constexpr evaluation.",
      lessons: [
        {
          id: "cpp-templates",
          slug: "templates-and-metaprogramming",
          courseSlug: "cpp",
          moduleSlug: "templates",
          title: "Function & Class Templates (template <typename T>)",
          description: "Write generic, type-agnostic algorithms that compile to highly optimized specialized machine code.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Declaring function templates (template <typename T>)",
            "Class templates with multiple type parameters",
            "Compile-time computation with constexpr",
          ],
          introduction: `Templates are C++'s mechanism for generic programming. Unlike Java/C# generics which use runtime type erasure or boxing, C++ templates generate specialized machine code for each type at compile time.`,
          whyItMatters: `Template algorithms run at the exact same native hardware speed as hand-written type-specific assembly code with zero abstraction penalty.`,
          mainExample: {
            title: "Generic Maximum Template Function",
            language: "cpp",
            code: `#include <iostream>\n\ntemplate <typename T>\nT getMax(T a, T b) {\n    return (a > b) ? a : b;\n}\n\nint main() {\n    std::cout << "Int Max: " << getMax(10, 20) << std::endl;\n    std::cout << "Double Max: " << getMax(3.14, 2.71) << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: ["Compiler instantiates two distinct optimized functions: getMax<int> and getMax<double>."],
          },
          detailedExplanation: ["Template definitions must typically reside in header files so the compiler can instantiate them in translation units."],
          commonMistakes: [],
          bestPractices: ["Use constexpr functions for computations that can be evaluated at compile time."],
          summary: ["C++ templates deliver zero-cost generic abstractions."],
        },
      ],
    },
    {
      id: "mod-cpp-9",
      slug: "stl",
      title: "Module 9: Standard Template Library (STL) Containers & Algorithms",
      description: "std::vector, std::unordered_map, std::sort, iterators, and <algorithm> header.",
      lessons: [
        {
          id: "cpp-stl",
          slug: "stl-containers-and-algorithms",
          courseSlug: "cpp",
          moduleSlug: "stl",
          title: "STL Containers (vector, unordered_map) & Algorithms",
          description: "Master standard contiguous vectors, hash maps (unordered_map), and standard algorithms (std::sort, std::find).",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Contiguous memory layout of std::vector for CPU cache efficiency",
            "Hash-based lookups with std::unordered_map",
            "Standard algorithms from <algorithm> using lambda predicates",
          ],
          introduction: `The Standard Template Library (STL) is a powerful set of C++ template classes to provide general-purpose classes and functions with templates that implement many popular algorithms and data structures.`,
          whyItMatters: `std::vector stores elements contiguously in memory, making iteration drastically faster than pointer-chasing linked lists due to CPU cache locality.`,
          mainExample: {
            title: "Vector Sorting with Custom Lambda",
            language: "cpp",
            code: `#include <iostream>\n#include <vector>\n#include <algorithm>\n\nint main() {\n    std::vector<int> data = {50, 10, 40, 20, 30};\n    std::sort(data.begin(), data.end());\n    std::cout << "Sorted STL Vector: ";\n    for (int x : data) std::cout << x << " ";\n    std::cout << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: ["std::sort executes in O(n log n) time using Introsort."],
          },
          detailedExplanation: ["Use reserve() on std::vector to pre-allocate memory and avoid dynamic reallocation copies."],
          commonMistakes: [],
          bestPractices: ["Always default to std::vector unless you have a proven profiling need for another container."],
          summary: ["The STL provides battle-tested, high-performance algorithms and containers."],
        },
      ],
    },
    {
      id: "mod-cpp-10",
      slug: "cpp20-features",
      title: "Module 10: Modern C++20 Concepts, Coroutines & Ranges",
      description: "C++20 Concepts (type constraints), Ranges pipeline (| std::views), and Modules.",
      lessons: [
        {
          id: "cpp-concepts",
          slug: "cpp20-concepts-and-ranges",
          courseSlug: "cpp",
          moduleSlug: "cpp20-features",
          title: "C++20 Concepts & The Ranges Library",
          description: "Constrain template arguments with C++20 Concepts and write composable range pipelines with views.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Declaring template constraints with 'requires' and Concepts",
            "Clear compiler error messages instead of 500-line template errors",
            "Composable range pipelines (std::views::filter | std::views::transform)",
          ],
          introduction: `C++20 represents one of the largest updates to C++, introducing Concepts for compile-time template validation and Ranges for clean functional composition.`,
          whyItMatters: `Concepts replace cryptic 100-line template error traces with clear, single-line compile failure diagnostics.`,
          mainExample: {
            title: "C++20 Concept Constraint",
            language: "cpp",
            code: `#include <iostream>\n#include <concepts>\n\ntemplate <std::integral T>\nT addIntegers(T a, T b) {\n    return a + b;\n}\n\nint main() {\n    std::cout << "Sum: " << addIntegers(15, 25) << std::endl;\n    // addIntegers(3.14, 2.71); // Compile Error: double does not satisfy std::integral!\n    return 0;\n}`,
            executable: true,
            explanation: ["std::integral concept restricts template instantiation strictly to integer types."],
          },
          detailedExplanation: ["Ranges allow lazy, zero-copy transformation pipelines on containers."],
          commonMistakes: [],
          bestPractices: ["Use C++20 Concepts instead of SFINAE / std::enable_if in modern codebases."],
          summary: ["C++20 Concepts and Ranges elevate template expressiveness and safety."],
        },
      ],
    },
    {
      id: "mod-cpp-11",
      slug: "concurrency",
      title: "Module 11: Multithreading & High-Performance Optimization",
      description: "std::thread, std::mutex, lock_guard, std::atomic, lock-free programming, and CPU cache optimization.",
      lessons: [
        {
          id: "cpp-threads",
          slug: "multithreading-and-atomics",
          courseSlug: "cpp",
          moduleSlug: "concurrency",
          title: "Multithreading with std::thread, Mutex & Atomics",
          description: "Spawn hardware threads with std::thread, protect shared memory with std::lock_guard, and use lock-free std::atomic.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Spawning native threads with std::thread and joining",
            "Preventing race conditions using std::mutex and std::lock_guard",
            "Lock-free atomic counters with std::atomic<int>",
          ],
          introduction: `C++ provides low-level multithreading primitives allowing software to extract peak multi-core CPU performance.`,
          whyItMatters: `std::atomic operations execute as single hardware CPU instructions without the heavy operating system lock overhead of mutexes.`,
          mainExample: {
            title: "Lock-Free Multithreaded Counter with std::atomic",
            language: "cpp",
            code: `#include <iostream>\n#include <thread>\n#include <atomic>\n\nstd::atomic<int> counter(0);\n\nvoid increment() {\n    for (int i = 0; i < 1000; ++i) counter.fetch_add(1);\n}\n\nint main() {\n    std::thread t1(increment);\n    std::thread t2(increment);\n    t1.join();\n    t2.join();\n    std::cout << "Atomic Counter: " << counter.load() << std::endl;\n    return 0;\n}`,
            executable: true,
            explanation: ["std::atomic guarantees thread-safe mutation without mutex locks."],
          },
          detailedExplanation: ["Always use std::lock_guard to ensure mutexes unlock automatically even if exceptions occur."],
          commonMistakes: [],
          bestPractices: ["Prefer std::atomic for simple counters and std::lock_guard for complex critical sections."],
          summary: ["Multithreading and atomics unlock the full parallel computing potential of modern multi-core CPUs."],
        },
      ],
    },
  ],
};
