import { Course } from "@/types";

export const cssCourse: Course = {
  id: "course-css",
  slug: "css",
  title: "CSS3 Architecture, Flexbox & Grid Mastery",
  tagline: "Master modern styling, responsive layouts, CSS Grid, Flexbox, transitions, and container queries.",
  description: "Deep dive into CSS: box model, specificity, Flexbox alignment, CSS Grid 2D layouts, responsive typography, custom properties (CSS variables), animations, transforms, and modern container queries.",
  category: "Frontend",
  level: "Beginner",
  estimatedHours: 20,
  icon: "Palette",
  badgeColor: "blue",
  prerequisites: ["HTML Fundamentals"],
  skillsGained: [
    "The CSS Box Model & Sizing Mechanics",
    "Flexbox 1D Layout System",
    "CSS Grid 2D Layout System",
    "Responsive Design & Media Queries",
    "Container Queries (@container)",
    "CSS Variables & Theming",
  ],
  featured: true,
  modules: [
    {
      id: "mod-css-1",
      slug: "intro",
      title: "Module 1: Introduction to CSS & Syntax Rules",
      description: "CSS selectors, element targeting, inline vs internal vs external stylesheets.",
      lessons: [
        {
          id: "css-intro",
          slug: "css-introduction-and-syntax",
          courseSlug: "css",
          moduleSlug: "intro",
          title: "CSS Syntax, Selectors & Rule Sets",
          description: "Learn how CSS rule sets attach styling declarations to HTML DOM elements.",
          durationMinutes: 12,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "CSS selector types: type, class, id, and attribute selectors",
            "Property-value declarations and semicolon terminators",
            "Connecting stylesheets with <link rel='stylesheet'>",
          ],
          introduction: `CSS (Cascading Style Sheets) is the design language of the web. It describes how HTML elements are displayed on screen, paper, or in other media.`,
          whyItMatters: `CSS completely decouples visual presentation from HTML document structure, allowing you to redesign an entire website without touching HTML.`,
          mainExample: {
            title: "Basic CSS Rule Set",
            language: "css",
            code: `/* Class Selector */\n.btn-primary {\n  background-color: #2563eb;\n  color: #ffffff;\n  padding: 12px 24px;\n  border-radius: 8px;\n  border: none;\n  font-weight: 600;\n  cursor: pointer;\n}`,
            executable: true,
            explanation: [".btn-primary selects all elements with class='btn-primary'."],
          },
          detailedExplanation: ["External stylesheets are cached by browsers, maximizing page load speed across subsequent visits."],
          commonMistakes: [],
          bestPractices: ["Always use external stylesheets linked via the <head>."],
          summary: ["CSS rule sets bind visual styles to targeted DOM selectors."],
        },
      ],
    },
    {
      id: "mod-css-2",
      slug: "cascade-specificity",
      title: "Module 2: The Cascade, Specificity & Inheritance",
      description: "How browsers resolve style conflicts, calculate specificity weights, and inherit values.",
      lessons: [
        {
          id: "css-specificity",
          slug: "cascade-and-specificity",
          courseSlug: "css",
          moduleSlug: "cascade-specificity",
          title: "The Cascade & Specificity Hierarchy",
          description: "Master specificity calculation: inline styles (1000) > IDs (100) > Classes (10) > Elements (1).",
          durationMinutes: 15,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "How the Cascade algorithm resolves conflicting properties",
            "The 4-column specificity matrix (Inline, ID, Class, Type)",
            "Why !important should be avoided in scalable codebases",
          ],
          introduction: `When multiple conflicting CSS rules target the same element, the browser uses specificity and the cascade order to determine which style wins.`,
          whyItMatters: `Understanding specificity prevents fragile codebases where developers resort to adding '!important' everywhere to override stubborn styles.`,
          mainExample: {
            title: "Specificity Resolution",
            language: "css",
            code: `/* Specificity: 0-0-0-1 (Element) */\nbutton { color: black; }\n\n/* Specificity: 0-0-1-0 (Class wins over element) */\n.action-btn { color: blue; }\n\n/* Specificity: 0-1-0-0 (ID wins over class) */\n#submit-btn { color: green; }`,
            executable: true,
            explanation: ["Higher specificity rules override lower specificity declarations regardless of order."],
          },
          detailedExplanation: ["If two selectors have equal specificity, the rule written last in the stylesheet takes precedence."],
          commonMistakes: [],
          bestPractices: ["Keep specificity low and uniform using single class selectors (BEM methodology)."],
          summary: ["Specificity and source order resolve all CSS style declarations deterministically."],
        },
      ],
    },
    {
      id: "mod-css-3",
      slug: "box-model",
      title: "Module 3: The Box Model & Sizing Mechanics",
      description: "Content, padding, border, margin, margin collapsing, and universal border-box reset.",
      lessons: [
        {
          id: "css-box-model",
          slug: "css-box-model",
          courseSlug: "css",
          moduleSlug: "box-model",
          title: "The CSS Box Model & Box Sizing",
          description: "Master the fundamental building block of all web layouts: content, padding, border, margin, and box-sizing.",
          durationMinutes: 15,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "The 4 distinct layers of the CSS Box Model",
            "Why box-sizing: border-box is industry standard",
            "Margin collapsing mechanics and how to prevent it",
          ],
          introduction: `In CSS, every visible element on the page is treated as a rectangular box. The CSS Box Model describes the layers of space surrounding the content: Content -> Padding -> Border -> Margin.`,
          whyItMatters: `By default (content-box), adding padding or borders expands the physical rendered width of an element, causing unexpected overflow bugs.`,
          syntax: `*, *::before, *::after {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}`,
          mainExample: {
            title: "Universal Box-Sizing Reset & Card Layout",
            language: "css",
            code: `.card {\n  box-sizing: border-box;\n  width: 350px;\n  padding: 24px;\n  border: 2px solid #2563eb;\n  background-color: #ffffff;\n  border-radius: 8px;\n}`,
            executable: true,
            explanation: ["Total computed width remains exactly 350px."],
          },
          detailedExplanation: ["border-box includes padding and border within the declared width/height."],
          commonMistakes: [],
          bestPractices: ["Always include the universal border-box reset at the top of your stylesheet."],
          summary: ["The Box Model comprises Content, Padding, Border, and Margin."],
        },
      ],
    },
    {
      id: "mod-css-4",
      slug: "typography",
      title: "Module 4: Typography, Web Fonts & Responsive Units",
      description: "rem vs em vs px, font-family, font-display: swap, and line-height.",
      lessons: [
        {
          id: "css-typography",
          slug: "responsive-typography-units",
          courseSlug: "css",
          moduleSlug: "typography",
          title: "Responsive Typography & Relative Units (rem, em, ch)",
          description: "Scale typography cleanly across mobile and desktop displays using rem, em, line-height, and clamp().",
          durationMinutes: 14,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Why rem units respect user browser accessibility font settings",
            "Using clamp() for fluid, responsive typography without media queries",
            "Optimizing web fonts with font-display: swap",
          ],
          introduction: `Typography is the cornerstone of content consumption. Using relative units like rem (relative to root font size) ensures text scales dynamically when visually impaired users increase default browser zoom.`,
          whyItMatters: `Hardcoded px font sizes ignore user accessibility preferences and break on mobile screens.`,
          mainExample: {
            title: "Fluid Typography with clamp()",
            language: "css",
            code: `h1 {\n  /* Minimum 1.75rem, Scales with viewport 4vw, Maximum 3.5rem */\n  font-size: clamp(1.75rem, 4vw + 1rem, 3.5rem);\n  line-height: 1.2;\n  letter-spacing: -0.02em;\n}`,
            executable: true,
            explanation: ["clamp() smoothly scales font size between mobile and 4K displays seamlessly."],
          },
          detailedExplanation: ["1rem equals 16px by default in standard browser environments."],
          commonMistakes: [],
          bestPractices: ["Use rem for font sizes and padding; use clamp() for fluid headings."],
          summary: ["Relative units guarantee scalable, accessible typography across all screen sizes."],
        },
      ],
    },
    {
      id: "mod-css-5",
      slug: "colors",
      title: "Module 5: Colors, Gradients & Modern Color Spaces",
      description: "HEX, RGB, HSL, modern OKLCH color spaces, alpha channels, and linear/radial gradients.",
      lessons: [
        {
          id: "css-colors",
          slug: "modern-color-spaces-and-gradients",
          courseSlug: "css",
          moduleSlug: "colors",
          title: "Modern Color Spaces (OKLCH, HSL) & Gradients",
          description: "Design accessible, vibrant color palettes using modern CSS OKLCH, alpha transparency, and gradients.",
          durationMinutes: 14,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Perceptually uniform color spaces (OKLCH) vs sRGB",
            "Creating smooth multi-stop linear and radial gradients",
            "Ensuring WCAG AA 4.5:1 text contrast ratios",
          ],
          introduction: `Modern CSS supports advanced color gamuts like OKLCH and Display P3, delivering richer and perceptually uniform color adjustments.`,
          whyItMatters: `OKLCH ensures that adjusting color lightness produces predictable perceived brightness across all hues.`,
          mainExample: {
            title: "OKLCH Theme Colors & Mesh Gradient",
            language: "css",
            code: `:root {\n  --brand-primary: oklch(0.55 0.22 260);\n  --brand-accent: oklch(0.70 0.18 150);\n}\n.hero {\n  background: linear-gradient(135deg, var(--brand-primary), var(--brand-accent));\n}`,
            executable: true,
            explanation: ["OKLCH delivers vivid wide-gamut colors on modern displays."],
          },
          detailedExplanation: ["Always verify contrast using WCAG 2.2 color contrast analyzers."],
          commonMistakes: [],
          bestPractices: ["Use CSS custom properties to manage design system color tokens."],
          summary: ["Modern color models give developers precise control over hue, chroma, and lightness."],
        },
      ],
    },
    {
      id: "mod-css-6",
      slug: "flexbox",
      title: "Module 6: Flexbox 1D Layout Engine",
      description: "Main axis vs cross axis, justify-content, align-items, flex-grow, flex-shrink, and wrap.",
      lessons: [
        {
          id: "css-flexbox",
          slug: "css-flexbox",
          courseSlug: "css",
          moduleSlug: "flexbox",
          title: "Flexbox 1D Alignment Mastery",
          description: "Master main vs cross axis, justify-content, align-items, flex-grow, flex-shrink, and flex-basis.",
          durationMinutes: 20,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "The Main Axis and Cross Axis concepts in Flexbox",
            "Aligning content with justify-content and align-items",
            "Sizing items dynamically with flex: 1 1 auto",
          ],
          introduction: `Flexbox (Flexible Box Layout) is a 1-dimensional CSS layout model designed to distribute space and align items along a single axis.`,
          whyItMatters: `Flexbox revolutionized web styling by making vertical centering and navigation bars effortless.`,
          mainExample: {
            title: "Navigation Bar with Flexbox",
            language: "css",
            code: `.navbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  padding: 16px 24px;\n  background: #0f172a;\n  color: white;\n}`,
            executable: true,
            explanation: ["display: flex activates the flex formatting context."],
          },
          detailedExplanation: ["Main Axis is aligned via justify-content; Cross Axis via align-items."],
          commonMistakes: [],
          bestPractices: ["Use gap for spacing flex items instead of margins."],
          summary: ["Flexbox excels at 1D component alignment and distribution."],
        },
      ],
    },
    {
      id: "mod-css-7",
      slug: "css-grid",
      title: "Module 7: CSS Grid 2D Layout Engine",
      description: "Grid tracks, fractional units (fr), grid-template-areas, and auto-fit responsive patterns.",
      lessons: [
        {
          id: "css-grid",
          slug: "css-grid-architecture",
          courseSlug: "css",
          moduleSlug: "css-grid",
          title: "CSS Grid 2D Layouts & Auto-Fit Grids",
          description: "Build complex two-dimensional page layouts: grid-template-columns, fr units, minmax(), and auto-fit responsive patterns.",
          durationMinutes: 22,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "2D grid systems: rows and columns simultaneously",
            "The fr (fractional) unit and minmax() sizing",
            "Creating responsive card grids without media queries",
          ],
          introduction: `CSS Grid is a 2-dimensional layout system designed for rows and columns simultaneously.`,
          whyItMatters: `With CSS Grid, you can create fully responsive multi-column layouts that automatically adapt from mobile to desktop with a single line of CSS.`,
          mainExample: {
            title: "Auto-Fit Responsive Card Grid",
            language: "css",
            code: `.card-grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n  gap: 24px;\n}`,
            executable: true,
            explanation: ["repeat(auto-fit, minmax(280px, 1fr)) creates adaptive column counts automatically."],
          },
          detailedExplanation: ["fr unit distributes available free space across column tracks."],
          commonMistakes: [],
          bestPractices: ["Use Grid for overall page layouts and Flexbox for micro-components."],
          summary: ["CSS Grid is the standard 2D layout tool in modern web architecture."],
        },
      ],
    },
    {
      id: "mod-css-8",
      slug: "responsive-design",
      title: "Module 8: Responsive Design, Media & Container Queries",
      description: "Mobile-first breakpoints, @media queries, and modern @container queries.",
      lessons: [
        {
          id: "css-container-queries",
          slug: "container-queries-and-responsive-design",
          courseSlug: "css",
          moduleSlug: "responsive-design",
          title: "Container Queries (@container) & Responsive Design",
          description: "Style components based on their parent container width rather than the global viewport with @container.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Mobile-first responsive design philosophy",
            "Why Container Queries (@container) supersede viewport media queries for design systems",
            "Declaring container-type: inline-size",
          ],
          introduction: `While media queries inspect the entire browser window width, Container Queries allow components to adapt based on the size of their parent container.`,
          whyItMatters: `A card component placed in a narrow sidebar can display vertically, while the same card in a wide main area displays horizontally, automatically!`,
          mainExample: {
            title: "Modern Container Query Component",
            language: "css",
            code: `.card-container {\n  container-type: inline-size;\n}\n\n@container (min-width: 400px) {\n  .card {\n    display: flex;\n    flex-direction: row;\n  }\n}`,
            executable: true,
            explanation: ["The card adapts based on its container, enabling truly modular design system components."],
          },
          detailedExplanation: ["Container queries make components independently responsive anywhere on the page."],
          commonMistakes: [],
          bestPractices: ["Use container queries for self-contained UI widgets."],
          summary: ["Container queries deliver component-driven responsive layouts."],
        },
      ],
    },
    {
      id: "mod-css-9",
      slug: "css-variables",
      title: "Module 9: CSS Custom Properties & Dynamic Theming",
      description: "CSS variables, cascade scoping, dark/light theme switching, and JavaScript manipulation.",
      lessons: [
        {
          id: "css-vars",
          slug: "custom-properties-and-theming",
          courseSlug: "css",
          moduleSlug: "css-variables",
          title: "CSS Variables (--custom-prop) & Dynamic Theming",
          description: "Build robust dark/light themes and parameterized design tokens with native CSS variables.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Declaring custom properties with --prefix in :root",
            "Dynamic runtime overriding for dark mode ([data-theme='dark'])",
            "Manipulating CSS variables dynamically with JavaScript",
          ],
          introduction: `CSS Custom Properties (commonly called CSS variables) allow you to store values in one place and reuse them across your entire stylesheet.`,
          whyItMatters: `Unlike Sass/SCSS variables which compile away, CSS variables exist live at runtime in the browser DOM.`,
          mainExample: {
            title: "Dark / Light Mode Theming System",
            language: "css",
            code: `:root {\n  --bg-primary: #ffffff;\n  --text-primary: #0f172a;\n}\n[data-theme="dark"] {\n  --bg-primary: #0f172a;\n  --text-primary: #f8fafc;\n}\nbody {\n  background-color: var(--bg-primary);\n  color: var(--text-primary);\n}`,
            executable: true,
            explanation: ["Switching the data-theme attribute updates the entire UI palette instantly."],
          },
          detailedExplanation: ["CSS variables cascade down the DOM tree, allowing contextual overrides inside specific components."],
          commonMistakes: [],
          bestPractices: ["Organize variables into semantic tokens (--color-bg-card) rather than literal values."],
          summary: ["CSS variables make dynamic theming and design systems simple and performant."],
        },
      ],
    },
    {
      id: "mod-css-10",
      slug: "animations",
      title: "Module 10: Transitions, Keyframe Animations & View Transitions",
      description: "Hardware-accelerated transforms, transitions, cubic-bezier, keyframes, and View Transitions API.",
      lessons: [
        {
          id: "css-motion",
          slug: "transitions-and-keyframe-animations",
          courseSlug: "css",
          moduleSlug: "animations",
          title: "Hardware-Accelerated Transitions & Keyframes",
          description: "Create smooth 60fps animations using transform, opacity, @keyframes, and transition curves.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Hardware-accelerated properties: transform and opacity",
            "Why animating width/margin causes layout thrashing and jank",
            "Defining multi-step keyframe animations with @keyframes",
          ],
          introduction: `CSS animations bring web interfaces to life with micro-interactions, modal reveals, and smooth state transitions. Modern browser engines offload transform and opacity animations directly to the GPU.`,
          whyItMatters: `Animating layout properties (like width or top) triggers expensive Reflow and Repaint operations, causing frame drops on mobile devices.`,
          mainExample: {
            title: "60fps Card Hover Lift Animation",
            language: "css",
            code: `.card {\n  transition: transform 0.25s cubic-bezier(0.4, 0, 0.2, 1), box-shadow 0.25s ease;\n  will-change: transform;\n}\n.card:hover {\n  transform: translateY(-4px);\n  box-shadow: 0 12px 24px -6px rgba(0,0,0,0.15);\n}`,
            executable: true,
            explanation: ["translateY animates on the GPU compositor thread without triggering layout reflow."],
          },
          detailedExplanation: ["Always stick to transform (translate, scale, rotate) and opacity for buttery smooth 60fps motion."],
          commonMistakes: [],
          bestPractices: ["Respect user motion preferences with @media (prefers-reduced-motion: reduce)."],
          summary: ["Hardware-accelerated CSS transforms deliver smooth 60fps interface animations."],
        },
      ],
    },
    {
      id: "mod-css-11",
      slug: "css-architecture",
      title: "Module 11: CSS Architecture, BEM & Modern Layout Patterns",
      description: "BEM naming conventions, utility-first CSS, CSS Modules, and layout scalability.",
      lessons: [
        {
          id: "css-arch",
          slug: "bem-and-css-architecture",
          courseSlug: "css",
          moduleSlug: "css-architecture",
          title: "Scalable CSS Architecture & BEM Methodology",
          description: "Structure large enterprise stylesheets cleanly using Block Element Modifier (BEM) and CSS Modules.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "BEM syntax: .block__element--modifier",
            "Preventing selector collision in large team codebases",
            "Integrating CSS Modules with modern React/Next.js frameworks",
          ],
          introduction: `As web applications grow to hundreds of components, organizing CSS prevents namespace clashes, dead code accumulation, and specificity wars.`,
          whyItMatters: `BEM (Block, Element, Modifier) creates self-documenting class names that make component relationships instantly clear.`,
          mainExample: {
            title: "BEM Component Structure",
            language: "css",
            code: `/* Block */\n.card { border-radius: 8px; }\n\n/* Element */\n.card__title { font-size: 1.25rem; }\n.card__body { padding: 16px; }\n\n/* Modifier */\n.card--featured { border: 2px solid #2563eb; }`,
            executable: true,
            explanation: ["BEM ensures every selector has equal (single-class) specificity."],
          },
          detailedExplanation: ["In modern Next.js/React applications, CSS Modules automatically scope class names locally."],
          commonMistakes: [],
          bestPractices: ["Keep selector nesting to a maximum of 1 level to avoid high specificity."],
          summary: ["Structured CSS architecture guarantees maintainable, scalable design systems."],
        },
      ],
    },
  ],
};
