import { Course } from "@/types";

export const cybersecurityCourse: Course = {
  id: "course-cybersecurity",
  slug: "cybersecurity",
  title: "Cybersecurity & Defensive Web Engineering",
  tagline: "OWASP Top 10 defenses, secure authentication, cryptographic hashing, and threat modeling.",
  description: "Learn defensive web security: OWASP Top 10 vulnerabilities (SQLi, XSS, CSRF, SSRF, Broken Access Control), cryptographic algorithms (symmetric vs asymmetric), bcrypt password hashing, JWT security, HTTPS/TLS certificates, Content Security Policy (CSP), and secure coding standards.",
  category: "Cybersecurity",
  level: "Intermediate",
  estimatedHours: 26,
  icon: "Shield",
  badgeColor: "red",
  prerequisites: ["Web development basics"],
  skillsGained: [
    "OWASP Top 10 Vulnerability Mitigation & Penetration Defense",
    "SQL Injection & Cross-Site Scripting (XSS) Prevention",
    "Cryptographic Hashing (bcrypt, argon2) & Salt Mechanics",
    "HTTPS/TLS Handshake Protocols & Public Key Infrastructure",
    "HTTP Security Headers (CSP, HSTS, CORS)",
  ],
  featured: false,
  modules: [
    {
      id: "mod-sec-1",
      slug: "infosec-principles",
      title: "Module 1: Information Security Principles (CIA Triad)",
      description: "Confidentiality, Integrity, Availability, Defense-in-Depth, and Principle of Least Privilege.",
      lessons: [
        {
          id: "sec-cia",
          slug: "cia-triad-and-security-principles",
          courseSlug: "cybersecurity",
          moduleSlug: "infosec-principles",
          title: "The CIA Triad & Core Defensive Principles",
          description: "Understand the foundational pillars of information security: Confidentiality, Integrity, and Availability.",
          durationMinutes: 14,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "The CIA Triad: Confidentiality (encryption), Integrity (hashes), Availability (redundancy)",
            "The Defense-in-Depth layered security model",
            "Principle of Least Privilege (PoLP) across accounts and services",
          ],
          introduction: `Information Security is the practice of protecting information by mitigating information risks. The CIA Triad serves as the guiding model for evaluating and building secure systems.`,
          whyItMatters: `Every security control in existence—from firewalls to cryptographic signatures—serves to protect at least one aspect of the CIA triad.`,
          mainExample: {
            title: "CIA Triad Mapping",
            language: "text",
            code: `Confidentiality: Data is hidden from unauthorized parties (TLS, AES-256 Encryption)\nIntegrity: Data is unaltered and trustworthy (SHA-256 Hashes, Digital Signatures)\nAvailability: Data is accessible to authorized users when needed (DDoS Mitigation, Backups)`,
            takeaway: "A comprehensive security posture balances all three pillars simultaneously.",
          },
          detailedExplanation: ["Defense-in-depth requires multiple redundant layers of security controls so no single failure compromises the system."],
          commonMistakes: [],
          bestPractices: ["Always apply the principle of least privilege to database users, API keys, and IAM roles."],
          summary: ["The CIA triad guides secure software architecture and risk mitigation."],
        },
      ],
    },
    {
      id: "mod-sec-2",
      slug: "network-security",
      title: "Module 2: Network Security & TCP/IP Protocols",
      description: "OSI model, TCP 3-way handshake, DNS security, firewalls, and port scanning.",
      lessons: [
        {
          id: "sec-network",
          slug: "tcp-ip-and-network-defense",
          courseSlug: "cybersecurity",
          moduleSlug: "network-security",
          title: "Network Defense: TCP Handshake, DNS & Firewalls",
          description: "Understand network packet flow, TCP 3-way handshake (SYN, SYN-ACK, ACK), and packet filtering firewalls.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "The TCP 3-Way Handshake mechanism and SYN Flood DDoS attacks",
            "DNS resolution, DNS Spoofing, and DNSSEC protection",
            "Stateful packet inspection firewalls and network segmentation",
          ],
          introduction: `Network security involves policies, processes, and practices adopted to prevent, detect and monitor unauthorized access, misuse, modification, or denial of a computer network.`,
          whyItMatters: `Understanding TCP packet headers allows security engineers to detect port scanning, spoofing, and DDoS attacks.`,
          mainExample: {
            title: "TCP 3-Way Handshake Flow",
            language: "text",
            code: `Client ------------ [SYN: Synchronize Sequence] -----------> Server\nClient <----------- [SYN-ACK: Acknowledge & Sync] ---------- Server\nClient ------------ [ACK: Connection Established] ---------> Server`,
            takeaway: "TCP guarantees reliable bidirectional stream delivery before application data transmits.",
          },
          detailedExplanation: ["SYN cookies defend servers against SYN flood denial-of-service attacks."],
          commonMistakes: [],
          bestPractices: ["Close all unused server ports and segment networks with strict firewall rules."],
          summary: ["Network protocols require defensive configuration to repel automated scans and flood attacks."],
        },
      ],
    },
    {
      id: "mod-sec-3",
      slug: "cryptography",
      title: "Module 3: Cryptography: Symmetric vs Asymmetric",
      description: "AES-256 encryption, RSA/ECC public-key cryptography, key exchange, and digital signatures.",
      lessons: [
        {
          id: "sec-crypto",
          slug: "symmetric-and-asymmetric-cryptography",
          courseSlug: "cybersecurity",
          moduleSlug: "cryptography",
          title: "Symmetric (AES) vs Asymmetric (RSA/ECC) Cryptography",
          description: "Master symmetric bulk encryption (AES-256-GCM) and asymmetric public/private key pairs (RSA, Elliptic Curve).",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Symmetric encryption (same shared key for encrypt/decrypt) with AES-256",
            "Asymmetric cryptography (Public Key encrypts, Private Key decrypts) with RSA/ECC",
            "Digital signatures for non-repudiation and authenticity verification",
          ],
          introduction: `Cryptography is the science of securing communication and data from adversaries through mathematical algorithms.`,
          whyItMatters: `Modern secure systems combine both: asymmetric crypto (Diffie-Hellman) establishes shared keys securely, and symmetric AES encrypts the high-speed data stream.`,
          mainExample: {
            title: "Symmetric vs Asymmetric Roles",
            language: "text",
            code: `Symmetric (AES-GCM): 1 Secret Key | Ultra Fast | Used for database data-at-rest encryption\nAsymmetric (RSA/ECC): Public + Private Key Pair | Used for SSH logins, TLS handshake, and JWT signing`,
            takeaway: "Hybrid cryptography combines asymmetric key exchange with symmetric bulk data speed.",
          },
          detailedExplanation: ["Elliptic Curve Cryptography (ECC) provides the same security as RSA with much smaller key sizes (256-bit ECC ≈ 3072-bit RSA)."],
          commonMistakes: [],
          bestPractices: ["Never implement custom cryptographic algorithms; always use established standard libraries."],
          summary: ["Cryptography protects data confidentiality, integrity, and authenticity."],
        },
      ],
    },
    {
      id: "mod-sec-4",
      slug: "hashing-passwords",
      title: "Module 4: Hashing & Secure Password Storage",
      description: "Cryptographic hash functions (SHA-256), Rainbow Tables, Salts, and bcrypt/Argon2.",
      lessons: [
        {
          id: "sec-hashing",
          slug: "password-hashing-bcrypt-and-argon2",
          courseSlug: "cybersecurity",
          moduleSlug: "hashing-passwords",
          title: "Password Hashing with Bcrypt & Argon2",
          description: "Understand why fast hashes (MD5, SHA-256) are dangerous for passwords, and use adaptive salted hashes (bcrypt, Argon2).",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Why cryptographic hashes (SHA-256) are one-way and irreversible",
            "How unique random salts defeat Rainbow Table lookup attacks",
            "Adaptive work factors in bcrypt and Argon2 to resist GPU brute-forcing",
          ],
          introduction: `Passwords must NEVER be stored in plain text or encrypted with reversible keys. Passwords must be hashed using slow, salted, adaptive cryptographic algorithms like bcrypt or Argon2id.`,
          whyItMatters: `GPUs can compute 10,000,000,000 SHA-256 hashes per second. Bcrypt forces work factor delays, limiting attackers to a few hundred attempts per second.`,
          mainExample: {
            title: "Bcrypt Password Hashing & Verification",
            language: "javascript",
            code: `const bcrypt = require("bcryptjs");\n\nasync function hashPassword(plainPassword) {\n  const saltRounds = 12; // 2^12 computational cost iterations\n  const hash = await bcrypt.hash(plainPassword, saltRounds);\n  return hash;\n}\n\nasync function verify(plain, hash) {\n  return await bcrypt.compare(plain, hash);\n}`,
            executable: false,
            explanation: ["bcrypt automatically embeds a unique random 128-bit salt in the output hash."],
          },
          detailedExplanation: ["Argon2id is the winner of the Password Hashing Competition (PHC) and adds memory-hardness against custom ASIC cracking hardware."],
          commonMistakes: [],
          bestPractices: ["Use a minimum of 12 rounds for bcrypt in production authentication systems."],
          summary: ["Slow, salted hashes protect user credentials against data breach cracking."],
        },
      ],
    },
    {
      id: "mod-sec-5",
      slug: "https-tls",
      title: "Module 5: HTTPS, TLS Handshakes & SSL Certificates",
      description: "HTTP vs HTTPS, TLS 1.3 handshake, Certificate Authorities (Let's Encrypt), and Public Key Infrastructure.",
      lessons: [
        {
          id: "sec-tls",
          slug: "https-and-tls-handshake",
          courseSlug: "cybersecurity",
          moduleSlug: "https-tls",
          title: "HTTPS & The TLS 1.3 Handshake Protocol",
          description: "Learn how Transport Layer Security (TLS 1.3) encrypts web traffic and verifies server identity via SSL certificates.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Why unencrypted HTTP exposes credentials to Man-in-the-Middle (MitM) sniffing",
            "The 1-RTT TLS 1.3 cryptographic handshake",
            "Certificate Authorities (CAs) and Public Key Infrastructure (PKI) chains of trust",
          ],
          introduction: `HTTPS (Hypertext Transfer Protocol Secure) encrypts all communication between your browser and the website using TLS, protecting sensitive data like passwords and credit card numbers.`,
          whyItMatters: `On open public Wi-Fi networks, unencrypted HTTP traffic can be intercepted and modified by any attacker on the same network.`,
          mainExample: {
            title: "TLS 1.3 Handshake Timeline",
            language: "text",
            code: `Client -> [ClientHello + Key Share] -> Server\nClient <- [ServerHello + Certificate + Server Key Share + Finished] <- Server\nClient -> [Finished + Encrypted Application Data (HTTP GET)] -> Server`,
            takeaway: "TLS 1.3 completes secure key exchange in just 1 network round-trip (1-RTT).",
          },
          detailedExplanation: ["Let's Encrypt automates free SSL/TLS certificate issuance via the ACME protocol."],
          commonMistakes: [],
          bestPractices: ["Always enforce HTTPS and enable HTTP Strict Transport Security (HSTS)."],
          summary: ["HTTPS/TLS encrypts web traffic and guarantees authentic server identity."],
        },
      ],
    },
    {
      id: "mod-sec-6",
      slug: "owasp-top-10",
      title: "Module 6: Web App Security & OWASP Top 10",
      description: "The Open Web Application Security Project (OWASP) Top 10 vulnerabilities overview.",
      lessons: [
        {
          id: "sec-owasp-intro",
          slug: "owasp-top-10",
          courseSlug: "cybersecurity",
          moduleSlug: "owasp-top-10",
          title: "OWASP Top 10 & Web Application Defenses",
          description: "Understand the most critical web security vulnerabilities and how to write defensive, secure code.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "The OWASP Top 10 risk categories",
            "Broken Access Control (#1 most common web vulnerability)",
            "Security misconfigurations and vulnerable third-party dependencies",
          ],
          introduction: `The Open Web Application Security Project (OWASP) Top 10 is the universally recognized standard awareness document for developers and web application security.`,
          whyItMatters: `Knowing the OWASP Top 10 allows engineering teams to build security into their software development lifecycle (DevSecOps) from day one.`,
          mainExample: {
            title: "OWASP Top 10 Core Highlights",
            language: "text",
            code: `A01: Broken Access Control (Unauthorized data access / IDOR)\nA02: Cryptographic Failures (Plaintext passwords, weak ciphers)\nA03: Injection (SQLi, Command Injection, XSS)\nA04: Insecure Design (Missing rate limits, architectural flaws)\nA05: Security Misconfiguration (Default passwords, debug modes enabled)`,
            takeaway: "Designing security controls upfront prevents costly retrofits post-breach.",
          },
          detailedExplanation: ["Automated dependency scanners (npm audit, Snyk, Dependabot) detect known CVE vulnerabilities in packages."],
          commonMistakes: [],
          bestPractices: ["Run automated security scanners in CI pipelines on every pull request."],
          summary: ["OWASP Top 10 provides the baseline checklist for application security."],
        },
      ],
    },
    {
      id: "mod-sec-7",
      slug: "sql-injection",
      title: "Module 7: SQL Injection (SQLi) & Parameterization",
      description: "Classic SQL injection, blind SQLi, OR 1=1 exploits, and parameterized prepared statements.",
      lessons: [
        {
          id: "sec-sqli",
          slug: "sql-injection-and-parameterized-queries",
          courseSlug: "cybersecurity",
          moduleSlug: "sql-injection",
          title: "SQL Injection (SQLi) & Parameterized Queries",
          description: "Prevent catastrophic SQL injection attacks by replacing string concatenation with parameterized prepared statements.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How attackers exploit unescaped string concatenation (' OR '1'='1)",
            "Why parameterized prepared statements completely eliminate SQLi",
            "Object-Relational Mapping (ORM) query safety",
          ],
          introduction: `SQL Injection occurs when untrusted user input is directly concatenated into a database SQL query string, allowing attackers to manipulate the query structure.`,
          whyItMatters: `A single SQL injection vulnerability can allow an attacker to bypass authentication, dump the entire user database, or delete all records.`,
          mainExample: {
            title: "Vulnerable vs Parameterized SQL",
            language: "javascript",
            code: `// VULNERABLE (DO NOT DO THIS!):\n// const query = "SELECT * FROM users WHERE email = '" + userInput + "'";\n\n// SECURE (Parameterized Prepared Statement):\nconst query = "SELECT id, email FROM users WHERE email = $1";\nconst result = await db.query(query, [userInput]);`,
            executable: false,
            explanation: ["Database treats $1 strictly as a literal data parameter, never as executable SQL code."],
          },
          detailedExplanation: ["Prepared statements compile the SQL query template first, then pass data parameters separately."],
          commonMistakes: [],
          bestPractices: ["Never concatenate strings into SQL queries; always use parameterized queries or type-safe ORMs."],
          summary: ["Parameterized queries permanently eliminate SQL injection vulnerabilities."],
        },
      ],
    },
    {
      id: "mod-sec-8",
      slug: "xss-defense",
      title: "Module 8: Cross-Site Scripting (XSS) & Mitigation",
      description: "Stored XSS, Reflected XSS, DOM-based XSS, context escaping, and React auto-escaping.",
      lessons: [
        {
          id: "sec-xss",
          slug: "cross-site-scripting-and-mitigation",
          courseSlug: "cybersecurity",
          moduleSlug: "xss-defense",
          title: "Cross-Site Scripting (XSS): Stored, Reflected & DOM",
          description: "Defend web apps against malicious JavaScript execution using HTML escaping, sanitized inputs, and DOMPurify.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "The 3 types of XSS: Stored, Reflected, and DOM-based",
            "How attackers steal session cookies using document.cookie in XSS payloads",
            "Why dangerouslySetInnerHTML requires DOMPurify sanitization in React",
          ],
          introduction: `Cross-Site Scripting (XSS) attacks occur when an attacker injects malicious client-side executable JavaScript scripts into web pages viewed by other users.`,
          whyItMatters: `Malicious JavaScript executing in a victim's browser can steal session tokens, log keystrokes, or perform actions on behalf of the user.`,
          mainExample: {
            title: "Safe React Escaping vs dangerouslySetInnerHTML",
            language: "javascript",
            code: `// SAFE: React automatically escapes HTML entities in JSX\nfunction SafeComment({ text }) {\n  return <p>{text}</p>; // '<script>...' is rendered harmlessly as plain text\n}\n\n// If raw HTML is required, ALWAYS sanitize with DOMPurify first:\n// import DOMPurify from 'dompurify';\n// <div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(userHTML) }} />`,
            executable: false,
            explanation: ["React escapes text by default, converting < and > into safe &lt; and &gt; entities."],
          },
          detailedExplanation: ["Mark authentication session cookies as HttpOnly so client JavaScript cannot access them via document.cookie."],
          commonMistakes: [],
          bestPractices: ["Set HttpOnly flags on authentication cookies and sanitize all raw HTML inputs."],
          summary: ["Context-aware output escaping and input sanitization neutralize XSS attacks."],
        },
      ],
    },
    {
      id: "mod-sec-9",
      slug: "csrf-ssrf-bac",
      title: "Module 9: CSRF, SSRF & Broken Access Control",
      description: "Cross-Site Request Forgery, SameSite cookie attributes, SSRF, and Insecure Direct Object References (IDOR).",
      lessons: [
        {
          id: "sec-csrf-idor",
          slug: "csrf-ssrf-and-broken-access-control",
          courseSlug: "cybersecurity",
          moduleSlug: "csrf-ssrf-bac",
          title: "CSRF, IDOR & Server-Side Request Forgery (SSRF)",
          description: "Protect against forged cross-site requests with SameSite cookies, anti-CSRF tokens, and prevent IDOR with authorization checks.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Cross-Site Request Forgery (CSRF) and SameSite=Lax/Strict cookie protection",
            "Insecure Direct Object References (IDOR) when authorization checks are missing (GET /api/user/123)",
            "Server-Side Request Forgery (SSRF) cloud metadata theft prevention",
          ],
          introduction: `Broken Access Control occurs when users can act outside of their intended permissions. CSRF tricks authenticated users into executing unwanted actions on web apps where they are logged in.`,
          whyItMatters: `IDOR happens when an API endpoint looks up records by ID without checking whether the requesting user actually owns that record.`,
          mainExample: {
            title: "IDOR Authorization Guard Pattern",
            language: "javascript",
            code: `async function getInvoice(invoiceId, requestingUserId) {\n  const invoice = await db.invoices.findById(invoiceId);\n  // MANDATORY: Verify ownership!\n  if (!invoice || invoice.userId !== requestingUserId) {\n    throw new ForbiddenError("You do not have permission to view this invoice.");\n  }\n  return invoice;\n}`,
            executable: false,
            explanation: ["Explicitly checks that requestingUserId matches the owner before returning data."],
          },
          detailedExplanation: ["SameSite=Lax prevents browsers from sending cookies along with cross-site third-party requests."],
          commonMistakes: [],
          bestPractices: ["Always enforce ownership authorization checks at the database query level (WHERE id = $1 AND user_id = $2)."],
          summary: ["Access control and SameSite cookie protections prevent unauthorized cross-site actions."],
        },
      ],
    },
    {
      id: "mod-sec-10",
      slug: "security-headers",
      title: "Module 10: HTTP Security Headers (CSP, HSTS, CORS)",
      description: "Content Security Policy (CSP), Strict-Transport-Security (HSTS), X-Frame-Options, and CORS.",
      lessons: [
        {
          id: "sec-headers",
          slug: "http-security-headers-and-csp",
          courseSlug: "cybersecurity",
          moduleSlug: "security-headers",
          title: "Content Security Policy (CSP) & HTTP Security Headers",
          description: "Harden browsers against clickjacking, script injection, and protocol downgrade with CSP, HSTS, and X-Frame-Options.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Content-Security-Policy (CSP) headers to restrict script/image execution sources",
            "HTTP Strict Transport Security (HSTS) to force HTTPS permanently",
            "X-Frame-Options: DENY to prevent iframe clickjacking",
          ],
          introduction: `HTTP Security Headers are response headers sent by the server that instruct the client's web browser on how to behave securely when rendering the application.`,
          whyItMatters: `A strict CSP header blocks unauthorized third-party scripts from executing even if an attacker successfully injects an XSS script tag!`,
          mainExample: {
            title: "Production Security Headers Configuration",
            language: "http",
            code: `Strict-Transport-Security: max-age=63072000; includeSubDomains; preload\nX-Content-Type-Options: nosniff\nX-Frame-Options: DENY\nContent-Security-Policy: default-src 'self'; script-src 'self' https://trusted.cdn.com; img-src 'self' data: https:; object-src 'none';`,
            executable: false,
            explanation: ["Headers instruct the browser to enforce strict sandboxing boundaries."],
          },
          detailedExplanation: ["HSTS preload tells browsers to never attempt unencrypted HTTP connections to your domain."],
          commonMistakes: [],
          bestPractices: ["Deploy CSP in 'Content-Security-Policy-Report-Only' mode first to monitor violations before enforcement."],
          summary: ["Security headers turn standard browsers into active defense shields."],
        },
      ],
    },
    {
      id: "mod-sec-11",
      slug: "auth-threat-model",
      title: "Module 11: Authentication, OAuth 2.0 & Threat Modeling",
      description: "OAuth 2.0 / OpenID Connect authorization code flow, PKCE, STRIDE threat modeling, and zero trust.",
      lessons: [
        {
          id: "sec-oauth-stride",
          slug: "oauth2-and-stride-threat-modeling",
          courseSlug: "cybersecurity",
          moduleSlug: "auth-threat-model",
          title: "OAuth 2.0 (PKCE), Multi-Factor Auth & STRIDE Threat Modeling",
          description: "Implement delegated authorization with OAuth 2.0 + PKCE and systematically analyze architecture risks with STRIDE.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "OAuth 2.0 Authorization Code Flow with PKCE (Proof Key for Code Exchange)",
            "Multi-Factor Authentication (TOTP / WebAuthn FIDO2 keys)",
            "The STRIDE Threat Modeling framework (Spoofing, Tampering, Repudiation, Info Disclosure, DoS, Elevation of Privilege)",
          ],
          introduction: `OAuth 2.0 is the industry-standard authorization framework enabling third-party applications to obtain limited access to user accounts without sharing passwords. STRIDE provides a structured method to find vulnerabilities during architectural design.`,
          whyItMatters: `Threat modeling before writing code prevents fundamental architectural security flaws that cost millions to fix post-launch.`,
          mainExample: {
            title: "STRIDE Threat Modeling Taxonomy",
            language: "text",
            code: `S - Spoofing Identity (Prevent with MFA & Digital Signatures)\nT - Tampering with Data (Prevent with Hashes & TLS)\nR - Repudiation (Prevent with Audit Logs & WORM Storage)\nI - Information Disclosure (Prevent with Encryption & Least Privilege)\nD - Denial of Service (Prevent with Rate Limiting & Autoscaling)\nE - Elevation of Privilege (Prevent with Role-Based Access Control RBAC)`,
            takeaway: "STRIDE systematically identifies every category of security threat across application components.",
          },
          detailedExplanation: ["PKCE (RFC 7636) prevents authorization code interception attacks on single-page apps and mobile devices."],
          commonMistakes: [],
          bestPractices: ["Perform STRIDE threat modeling on all new system architecture diagrams before implementation."],
          summary: ["Threat modeling and modern OAuth standards build secure-by-design software systems."],
        },
      ],
    },
  ],
};
