import { Course } from "@/types";

export const devopsCourse: Course = {
  id: "course-devops",
  slug: "devops",
  title: "DevOps, Docker, Kubernetes & Cloud Engineering",
  tagline: "Containerization, automated CI/CD pipelines, Kubernetes orchestration, and cloud infrastructure.",
  description: "Master modern DevOps practices: Linux CLI, Docker container packaging, multi-stage Dockerfiles, Docker Compose, Kubernetes pods, deployments, services, ingress, CI/CD with GitHub Actions, Terraform Infrastructure as Code (IaC), and AWS/GCP cloud platforms.",
  category: "DevOps & Cloud",
  level: "Intermediate",
  estimatedHours: 30,
  icon: "Server",
  badgeColor: "blue",
  prerequisites: ["Linux basics or programming knowledge"],
  skillsGained: [
    "Docker Containerization & Image Optimization",
    "Kubernetes (K8s) Cluster Orchestration & Helm Charts",
    "Automated CI/CD Pipelines with GitHub Actions",
    "Terraform Declarative Infrastructure as Code (IaC)",
    "Cloud Security, Monitoring & Observability (Prometheus/Grafana)",
  ],
  featured: true,
  modules: [
    {
      id: "mod-devops-1",
      slug: "linux-shell",
      title: "Module 1: Linux Administration & Shell Scripting",
      description: "Linux file permissions (chmod, chown), process management (systemd, ps, top), SSH keys, and bash scripts.",
      lessons: [
        {
          id: "devops-linux",
          slug: "linux-administration-and-bash",
          courseSlug: "devops",
          moduleSlug: "linux-shell",
          title: "Linux Administration, Permissions & Bash Automation",
          description: "Master Linux CLI commands, manage systemd services, configure SSH keys, and write automated bash scripts.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Linux file permissions (rwx, octal chmod 755)",
            "Managing background system services with systemctl (systemd)",
            "Writing resilient bash deployment automation scripts with set -euo pipefail",
          ],
          introduction: `Linux powers over 90% of cloud servers and container runtimes. Mastering the Linux command line is the foundational prerequisite for all DevOps and cloud engineering.`,
          whyItMatters: `Bash scripts automate server provisioning, log rotation, and build pipelines with native operating system speed.`,
          mainExample: {
            title: "Safe Production Bash Script Template",
            language: "bash",
            code: `#!/usr/bin/env bash\nset -euo pipefail # Exit on error, undefined var, and pipeline failure\n\necho "=== Deploying KWAS Platform ==="\nCURRENT_USER=$(whoami)\necho "Executing deploy as user: \${CURRENT_USER}"\n\nmkdir -p /var/log/kwas\necho "Deployment initialized successfully."`,
            executable: false,
            explanation: ["set -euo pipefail ensures script aborts immediately if any command fails."],
          },
          detailedExplanation: ["SSH key authentication (ssh-keygen, authorized_keys) replaces insecure password logins."],
          commonMistakes: [],
          bestPractices: ["Always include 'set -euo pipefail' at the top of all production bash scripts."],
          summary: ["Linux is the universal operating foundation of cloud and containerized computing."],
        },
      ],
    },
    {
      id: "mod-devops-2",
      slug: "git-workflows",
      title: "Module 2: Git Version Control & Branching Workflows",
      description: "Git commit graphs, interactive rebasing, merge strategies, Trunk-Based Development, and GitOps.",
      lessons: [
        {
          id: "devops-git",
          slug: "git-branching-and-trunk-based-development",
          courseSlug: "devops",
          moduleSlug: "git-workflows",
          title: "Git Internals, Interactive Rebase & Trunk-Based Dev",
          description: "Master Git commits, resolve merge conflicts, squash commits with interactive rebase, and practice Trunk-Based Development.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How Git stores snapshots as directed acyclic graph (DAG) objects (blobs, trees, commits)",
            "Interactive rebasing (git rebase -i) to maintain clean commit history",
            "Trunk-Based Development vs GitFlow for rapid continuous integration",
          ],
          introduction: `Git is the distributed version control system that tracks changes in source code during software development.`,
          whyItMatters: `Trunk-Based Development (short-lived feature branches merged to main daily) enables 10x faster deployment frequencies than slow long-lived branch models.`,
          mainExample: {
            title: "Interactive Rebase Command",
            language: "bash",
            code: `# Rebase and squash the last 3 commits into 1 clean commit\ngit rebase -i HEAD~3`,
            executable: false,
            explanation: ["Interactive rebase squashes noisy wip commits into a clean descriptive change."],
          },
          detailedExplanation: ["git cherry-pick allows applying a specific commit from one branch to another."],
          commonMistakes: [],
          bestPractices: ["Keep feature branches small and merge into main within 24-48 hours."],
          summary: ["Disciplined Git workflows form the backbone of automated CI/CD release pipelines."],
        },
      ],
    },
    {
      id: "mod-devops-3",
      slug: "docker-containers",
      title: "Module 3: Docker Containerization & Images",
      description: "Containers vs VMs, Docker daemon, container lifecycle, Docker Hub, and port mapping.",
      lessons: [
        {
          id: "devops-docker-intro",
          slug: "docker-introduction",
          courseSlug: "devops",
          moduleSlug: "docker-containers",
          title: "Docker & Containerization Fundamentals",
          description: "Learn how Docker solves 'it works on my machine' by packaging code and dependencies into isolated container images.",
          durationMinutes: 15,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Containers vs Virtual Machines architecture",
            "Writing production Dockerfiles",
            "Docker networking and volume mounts for persistent data",
          ],
          introduction: `Docker is an open-source platform for building, shipping, and running applications inside lightweight, isolated containers.`,
          whyItMatters: `Docker guarantees that your code runs identically on your laptop, in CI tests, and across cloud clusters.`,
          mainExample: {
            title: "Basic Node.js Dockerfile",
            language: "dockerfile",
            code: `FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]`,
            executable: false,
            explanation: ["FROM node:20-alpine uses a lightweight 40MB base OS image."],
          },
          detailedExplanation: ["Containers share the host Linux kernel while isolating processes with namespaces and cgroups."],
          commonMistakes: [],
          bestPractices: ["Always use specific image version tags (node:20-alpine) rather than 'latest'."],
          summary: ["Docker provides consistency, portability, and isolation across the software lifecycle."],
        },
      ],
    },
    {
      id: "mod-devops-4",
      slug: "dockerfile-opt",
      title: "Module 4: Multi-Stage Dockerfiles & Optimization",
      description: "Layer caching, multi-stage builds, non-root users, .dockerignore, and slimming image sizes.",
      lessons: [
        {
          id: "devops-docker-multistage",
          slug: "multi-stage-dockerfiles-and-security",
          courseSlug: "devops",
          moduleSlug: "dockerfile-opt",
          title: "Multi-Stage Builds & Container Image Hardening",
          description: "Shrink Docker image sizes by 90% and eliminate vulnerabilities using multi-stage builds and non-root users.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Multi-stage Docker builds: separating build environment from minimal runtime",
            "Docker layer caching order optimization",
            "Running containers as unprivileged non-root users (USER node)",
          ],
          introduction: `Multi-stage builds allow you to use multiple FROM statements in your Dockerfile. You can selectively copy artifacts from one stage to another, leaving behind everything you don't need in the final image.`,
          whyItMatters: `Multi-stage builds prevent compilers, build tools, and source code from bloating production images and creating security attack vectors.`,
          mainExample: {
            title: "Production Next.js Multi-Stage Dockerfile",
            language: "dockerfile",
            code: `# Stage 1: Build\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\n# Stage 2: Minimal Production Runner (Under 90MB)\nFROM node:20-alpine AS runner\nWORKDIR /app\nENV NODE_ENV=production\nCOPY --from=builder /app/.next ./.next\nCOPY --from=builder /app/package*.json ./\nRUN npm ci --only=production\nUSER node\nCMD ["npm", "start"]`,
            executable: false,
            explanation: ["Runner stage discards devDependencies, keeping only production bundles."],
          },
          detailedExplanation: ["Copying package.json before source files leverages Docker layer caching to prevent re-installing dependencies on code changes."],
          commonMistakes: [],
          bestPractices: ["Always include a .dockerignore file containing node_modules, .git, and .env."],
          summary: ["Multi-stage builds produce tiny, secure, and fast-starting container images."],
        },
      ],
    },
    {
      id: "mod-devops-5",
      slug: "docker-compose",
      title: "Module 5: Docker Compose Multi-Container Stacks",
      description: "docker-compose.yml, multi-container networking, persistent volumes, and environment variables.",
      lessons: [
        {
          id: "devops-compose",
          slug: "docker-compose-multi-service-stacks",
          courseSlug: "devops",
          moduleSlug: "docker-compose",
          title: "Docker Compose: Multi-Service Local Stacks",
          description: "Spin up full-stack local development environments (App + PostgreSQL + Redis) with a single command.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Defining multi-container services in docker-compose.yml",
            "Automatic bridge networking and service name DNS resolution",
            "Persisting database data using named volumes",
          ],
          introduction: `Docker Compose is a tool for defining and running multi-container Docker applications using a YAML configuration file.`,
          whyItMatters: `Instead of manually configuring and installing PostgreSQL, Redis, and Node, new developers run 'docker compose up' and have a full local stack ready in seconds.`,
          mainExample: {
            title: "Multi-Service docker-compose.yml",
            language: "yaml",
            code: `services:\n  web:\n    build: .\n    ports: ["3000:3000"]\n    environment:\n      - DATABASE_URL=postgres://user:pass@db:5432/app\n    depends_on:\n      - db\n  db:\n    image: postgres:16-alpine\n    environment:\n      - POSTGRES_PASSWORD=pass\n    volumes:\n      - pgdata:/var/lib/postgresql/data\nvolumes:\n  pgdata:`,
            executable: false,
            explanation: ["The web service reaches the database using the hostname 'db' automatically."],
          },
          detailedExplanation: ["depends_on ensures the database container starts before the web application."],
          commonMistakes: [],
          bestPractices: ["Always use named volumes for database containers to prevent data loss on container restarts."],
          summary: ["Docker Compose delivers instant, reproducible multi-container development environments."],
        },
      ],
    },
    {
      id: "mod-devops-6",
      slug: "kk8s-architecture",
      title: "Module 6: Kubernetes Architecture & Pods",
      description: "Control Plane (API Server, etcd, scheduler), Worker Nodes (kubelet, kube-proxy), and Pod lifecycle.",
      lessons: [
        {
          id: "devops-k8s-arch",
          slug: "kubernetes-architecture-and-pods",
          courseSlug: "devops",
          moduleSlug: "k8s-architecture",
          title: "Kubernetes (K8s) Architecture & Pod Fundamentals",
          description: "Understand the Kubernetes Control Plane, Worker Nodes, and the fundamental Pod compute primitive.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Kubernetes Control Plane components (kube-apiserver, etcd, kube-scheduler)",
            "Worker Node components (kubelet, container runtime, kube-proxy)",
            "What a Pod is: the smallest deployable compute unit in Kubernetes",
          ],
          introduction: `Kubernetes (K8s) is an open-source container orchestration system for automating application deployment, scaling, and management across fleets of servers.`,
          whyItMatters: `Kubernetes automatically restarts crashed containers, scales pods up during traffic spikes, and coordinates zero-downtime rolling updates.`,
          mainExample: {
            title: "Basic Kubernetes Pod Manifest",
            language: "yaml",
            code: `apiVersion: v1\nkind: Pod\nmetadata:\n  name: kwas-web-pod\n  labels:\n    app: kwas-web\nspec:\n  containers:\n    - name: web\n      image: kwasacademy/web:2.0.0\n      ports:\n        - containerPort: 3000`,
            executable: false,
            explanation: ["Declarative YAML describes the desired state to the Kubernetes API server."],
          },
          detailedExplanation: ["Pods group one or more containers that share network namespaces and storage volumes."],
          commonMistakes: [],
          bestPractices: ["Never deploy raw naked Pods in production; always manage Pods with Deployments."],
          summary: ["Kubernetes provides resilient container orchestration at cluster scale."],
        },
      ],
    },
    {
      id: "mod-devops-7",
      slug: "k8s-deployments",
      title: "Module 7: Kubernetes Deployments, Services & Ingress",
      description: "Deployments (replicas, rolling updates), ClusterIP/NodePort/LoadBalancer Services, and Ingress routing.",
      lessons: [
        {
          id: "devops-k8s-deploy",
          slug: "kubernetes-deployments-and-ingress",
          courseSlug: "devops",
          moduleSlug: "k8s-deployments",
          title: "Deployments, Services & Ingress Controllers",
          description: "Orchestrate zero-downtime rolling updates with Deployments and expose services to internet traffic via Ingress.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Deployments for managing replica sets and rolling zero-downtime updates",
            "Kubernetes Services (ClusterIP, NodePort, LoadBalancer) for stable internal DNS",
            "Ingress Controllers (NGINX/Traefik) for SSL termination and HTTP path routing",
          ],
          introduction: `Deployments maintain a specified number of Pod replicas, automatically replacing failed instances. Services provide stable virtual IPs and load balancing across dynamic pods.`,
          whyItMatters: `During a new version release, Kubernetes Deployments spin up new pods and health-check them before terminating old pods, achieving 0 downtime.`,
          mainExample: {
            title: "Kubernetes Deployment & Service Manifest",
            language: "yaml",
            code: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: kwas-web-deployment\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: kwas-web\n  template:\n    metadata:\n      labels:\n        app: kwas-web\n    spec:\n      containers:\n        - name: web\n          image: kwasacademy/web:2.0.0\n          ports:\n            - containerPort: 3000\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: kwas-web-service\nspec:\n  type: ClusterIP\n  selector:\n    app: kwas-web\n  ports:\n    - port: 80\n      targetPort: 3000`,
            executable: false,
            explanation: ["Deployment ensures exactly 3 healthy replicas are running at all times."],
          },
          detailedExplanation: ["Readiness and Liveness probes prevent traffic from being sent to starting or unhealthy containers."],
          commonMistakes: [],
          bestPractices: ["Always configure livenessProbe and readinessProbe on container specs."],
          summary: ["Deployments and Services provide self-healing, zero-downtime container management."],
        },
      ],
    },
    {
      id: "mod-devops-8",
      slug: "cicd-actions",
      title: "Module 8: CI/CD Pipelines with GitHub Actions",
      description: "Continuous Integration, automated testing, continuous deployment workflows (.github/workflows), and secrets.",
      lessons: [
        {
          id: "devops-cicd",
          slug: "github-actions-cicd-pipelines",
          courseSlug: "devops",
          moduleSlug: "cicd-actions",
          title: "Automated CI/CD Pipelines with GitHub Actions",
          description: "Build automated testing, linting, Docker build, and cloud deployment pipelines triggered on git push.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "GitHub Actions workflow syntax (triggers, jobs, steps, runners)",
            "Automating test suites (npm test) on pull requests",
            "Securely deploying to production with GitHub Repository Secrets",
          ],
          introduction: `Continuous Integration (CI) and Continuous Deployment (CD) automate the building, testing, and shipping of software upon every git commit.`,
          whyItMatters: `Automated CI pipelines catch breaking changes and test failures before bad code is ever merged to main.`,
          mainExample: {
            title: "GitHub Actions CI Pipeline (.github/workflows/ci.yml)",
            language: "yaml",
            code: `name: Build & Test CI\non: [push, pull_request]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm ci\n      - run: npm run lint\n      - run: npm test\n      - run: npm run build`,
            executable: false,
            explanation: ["Workflow runs tests automatically on every push to verify code quality."],
          },
          detailedExplanation: ["Secrets (API tokens, AWS keys) are encrypted and masked in CI logs."],
          commonMistakes: [],
          bestPractices: ["Never hardcode credentials in workflow files; always use secrets.SECRET_NAME."],
          summary: ["CI/CD pipelines automate testing and deployment with absolute consistency."],
        },
      ],
    },
    {
      id: "mod-devops-9",
      slug: "terraform-iac",
      title: "Module 9: Infrastructure as Code (IaC) with Terraform",
      description: "HCL syntax, providers, state management (s3 backend), terraform plan, and apply.",
      lessons: [
        {
          id: "devops-terraform",
          slug: "terraform-infrastructure-as-code",
          courseSlug: "devops",
          moduleSlug: "terraform-iac",
          title: "Terraform & Declarative Infrastructure as Code",
          description: "Provision cloud infrastructure (AWS/GCP VPCs, databases, clusters) declaratively using HashiCorp Terraform.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "HashiCorp Configuration Language (HCL) syntax and providers",
            "The Terraform workflow: init, plan (dry-run preview), and apply",
            "Managing remote state files (terraform.tfstate) in S3 with DynamoDB state locking",
          ],
          introduction: `Infrastructure as Code (IaC) allows you to define, provision, and manage cloud servers, networks, and databases using human-readable configuration files.`,
          whyItMatters: `IaC eliminates manual console clicking errors, allows infrastructure changes to be reviewed in PRs, and enables rebuilding an entire cloud region in minutes.`,
          mainExample: {
            title: "Terraform AWS S3 Bucket Provisioning",
            language: "hcl",
            code: `terraform {\n  required_providers {\n    aws = {\n      source  = "hashicorp/aws"\n      version = "~> 5.0"\n    }\n  }\n}\n\nprovider "aws" {\n  region = "us-east-1"\n}\n\nresource "aws_s3_bucket" "kwas_assets" {\n  bucket = "kwas-academy-production-assets"\n}`,
            executable: false,
            explanation: ["terraform apply creates the S3 bucket exactly as declared in HCL."],
          },
          detailedExplanation: ["terraform plan computes the diff between real cloud state and desired configuration."],
          commonMistakes: [],
          bestPractices: ["Always run 'terraform plan' and verify the execution plan before running 'terraform apply'."],
          summary: ["Terraform turns cloud infrastructure into version-controlled, reproducible software."],
        },
      ],
    },
    {
      id: "mod-devops-10",
      slug: "cloud-fundamentals",
      title: "Module 10: Cloud Computing Fundamentals (AWS & GCP)",
      description: "Compute (EC2), Networking (VPC, Subnets, Security Groups), IAM roles, and CloudFront CDN.",
      lessons: [
        {
          id: "devops-cloud",
          slug: "cloud-networking-and-iam-security",
          courseSlug: "devops",
          moduleSlug: "cloud-fundamentals",
          title: "Cloud Architecture (AWS VPC, IAM & CDN)",
          description: "Design secure cloud networks with Virtual Private Clouds (VPCs), subnets, IAM least privilege roles, and CDNs.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "VPC architecture: Public subnets vs isolated Private database subnets",
            "Security Groups and Network Access Control Lists (NACLs)",
            "IAM (Identity and Access Management) Principle of Least Privilege",
          ],
          introduction: `Cloud platforms like AWS and Google Cloud provide scalable on-demand compute, storage, database, and networking services.`,
          whyItMatters: `Placing databases inside private subnets without public internet IPs prevents 99% of automated external scanning attacks.`,
          mainExample: {
            title: "Secure Cloud Subnet Architecture",
            language: "text",
            code: `Internet Gateway -> Public Subnet (Load Balancer & NAT Gateway) -> Private Subnet (App Servers) -> Isolated Subnet (PostgreSQL)`,
            takeaway: "Multi-tier VPC layout insulates sensitive databases from direct public internet exposure.",
          },
          detailedExplanation: ["IAM roles grant temporary credentials to EC2 and ECS instances without hardcoding secret keys."],
          commonMistakes: [],
          bestPractices: ["Never grant '*' admin access in IAM policies; adhere strictly to least privilege."],
          summary: ["Secure cloud architectures separate public ingress from private data layers."],
        },
      ],
    },
    {
      id: "mod-devops-11",
      slug: "observability",
      title: "Module 11: Monitoring & Logging with Prometheus & Grafana",
      description: "PromQL metrics, Prometheus scraping, Grafana dashboards, and Alertmanager notifications.",
      lessons: [
        {
          id: "devops-monitoring",
          slug: "prometheus-and-grafana-dashboards",
          courseSlug: "devops",
          moduleSlug: "observability",
          title: "Cloud Monitoring with Prometheus & Grafana",
          description: "Scrape application metrics with Prometheus, query with PromQL, and build visual dashboards with Grafana.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Pull-based metrics collection with Prometheus /metrics endpoints",
            "Writing PromQL queries (e.g. rate(http_requests_total[5m]))",
            "Building visual incident dashboards and Slack alerts with Grafana Alertmanager",
          ],
          introduction: `Prometheus is an open-source systems monitoring and alerting toolkit that collects and stores metrics as time series data. Grafana provides visualization dashboards.`,
          whyItMatters: `Visual dashboards display live CPU utilization, memory pressure, and HTTP 5xx error rate spikes in real time.`,
          mainExample: {
            title: "PromQL Error Rate Query",
            language: "promql",
            code: `# Calculate HTTP 5xx error percentage over the last 5 minutes\nsum(rate(http_requests_total{status=~"5.."}[5m])) \n/ \nsum(rate(http_requests_total[5m])) * 100`,
            executable: false,
            explanation: ["PromQL calculates error rate percentage for alerting rules."],
          },
          detailedExplanation: ["Grafana Alertmanager sends instant alerts to on-call engineers via Slack or PagerDuty when thresholds trigger."],
          commonMistakes: [],
          bestPractices: ["Define Service Level Objectives (SLOs) and alert on error budget consumption."],
          summary: ["Continuous monitoring and metrics ensure reliable, high-uptime operations."],
        },
      ],
    },
  ],
};
