import { Course } from "@/types";

export const dsaCourse: Course = {
  id: "course-dsa",
  slug: "dsa",
  title: "Data Structures & Algorithms (DSA) Mastery",
  tagline: "From Big-O complexity to Arrays, Trees, Graphs, Sorting, and Dynamic Programming.",
  description: "Master foundational and advanced computer science algorithms: Asymptotic Big-O analysis, Arrays, Linked Lists, Stacks, Queues, Hash Tables, Binary Search Trees (BST), Heaps, Graphs (BFS/DFS, Dijkstra), Sorting algorithms, and Dynamic Programming.",
  category: "Data Structures & Algorithms",
  level: "Beginner",
  estimatedHours: 36,
  icon: "Cpu",
  badgeColor: "purple",
  prerequisites: ["Basic Programming Syntax"],
  skillsGained: [
    "Big-O Time & Space Complexity Analysis",
    "Linear Structures (Arrays, Linked Lists, Stacks, Queues)",
    "Non-Linear Structures (Binary Trees, BST, Heaps, Graphs)",
    "Graph Traversal (BFS, DFS) & Shortest Path (Dijkstra)",
    "Dynamic Programming (Memoization, Tabulation)",
  ],
  featured: true,
  modules: [
    {
      id: "mod-dsa-1",
      slug: "big-o",
      title: "Module 1: Asymptotic Analysis & Big-O Notation",
      description: "Time complexity, space complexity, Big-O classes, and asymptotic growth.",
      lessons: [
        {
          id: "dsa-big-o",
          slug: "big-o-notation",
          courseSlug: "dsa",
          moduleSlug: "big-o",
          title: "Big-O Notation & Complexity Analysis",
          description: "Learn how to analyze and compare algorithmic efficiency: O(1), O(log n), O(n), O(n log n), and O(n²).",
          durationMinutes: 15,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "What Big-O notation measures (worst-case growth rate)",
            "Common complexity classes from O(1) to O(2ⁿ)",
            "How to calculate time and space complexity of code",
          ],
          introduction: `Big-O notation describes the limiting behavior of an algorithm as input size (n) approaches infinity. It allows engineers to quantify efficiency independent of hardware clock speeds.`,
          whyItMatters: `An O(n²) algorithm running in 1s for 1,000 items takes 11+ days for 1,000,000 items. Big-O helps you write code that scales.`,
          mainExample: {
            title: "Comparing O(n) vs O(1) Lookup",
            language: "javascript",
            code: `// O(n) Linear Search\nfunction linearFind(arr, target) {\n  for (let i = 0; i < arr.length; i++) {\n    if (arr[i] === target) return i;\n  }\n  return -1;\n}\n\n// O(1) Constant Time Map Lookup\nconst hashLookup = new Map([["usr_1", "Alex"]]);\nconsole.log(hashLookup.get("usr_1")); // O(1)`,
            executable: true,
            explanation: ["Linear search scans one-by-one; Hash Map computes direct hash index in O(1)."],
          },
          detailedExplanation: ["Always evaluate both time complexity (CPU cycles) and space complexity (auxiliary memory)."],
          commonMistakes: [],
          bestPractices: ["Aim for O(1) lookups and O(n log n) sorting in production algorithms."],
          summary: ["Big-O is the universal standard for algorithm performance analysis."],
        },
      ],
    },
    {
      id: "mod-dsa-2",
      slug: "arrays-strings",
      title: "Module 2: Dynamic Arrays & String Algorithms",
      description: "Dynamic array amortization, two pointers technique, and sliding window algorithms.",
      lessons: [
        {
          id: "dsa-two-pointers",
          slug: "two-pointers-and-sliding-window",
          courseSlug: "dsa",
          moduleSlug: "arrays-strings",
          title: "Two Pointers Technique & Sliding Window",
          description: "Optimize array and string algorithms from O(n²) to O(n) using Two Pointers and Sliding Window patterns.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Two Pointers convergence technique on sorted arrays",
            "Sliding Window pattern for maximum sum subarray problems",
            "Reducing polynomial O(n²) loops to linear O(n) time",
          ],
          introduction: `Two Pointers and Sliding Window are fundamental algorithmic patterns used to process contiguous subarrays or pairs in linear time.`,
          whyItMatters: `Solving the Two Sum problem on sorted inputs takes O(n) time with two pointers instead of O(n²) with nested loops.`,
          mainExample: {
            title: "Two Sum on Sorted Array (O(n))",
            language: "javascript",
            code: `function twoSumSorted(numbers, target) {\n  let left = 0, right = numbers.length - 1;\n  while (left < right) {\n    const sum = numbers[left] + numbers[right];\n    if (sum === target) return [left + 1, right + 1];\n    if (sum < target) left++;\n    else right--;\n  }\n  return [];\n}\n\nconsole.log("Two Sum Result:", twoSumSorted([2, 7, 11, 15], 9));`,
            executable: true,
            explanation: ["Pointers move inward based on sum comparison, eliminating nested loops."],
          },
          detailedExplanation: ["Sliding Window maintains a running window sum/count as it shifts across the array."],
          commonMistakes: [],
          bestPractices: ["Look for sorted array inputs to apply two pointers instantly."],
          summary: ["Two pointers and sliding windows convert quadratic searches into linear algorithms."],
        },
      ],
    },
    {
      id: "mod-dsa-3",
      slug: "linked-lists",
      title: "Module 3: Singly & Doubly Linked Lists",
      description: "Node pointers, traversal, in-place list reversal, and Floyd's cycle detection algorithm.",
      lessons: [
        {
          id: "dsa-linked-list",
          slug: "singly-linked-lists-and-cycle-detection",
          courseSlug: "dsa",
          moduleSlug: "linked-lists",
          title: "Linked Lists & Floyd's Cycle Detection (Tortoise & Hare)",
          description: "Implement linked list nodes, reverse lists in-place in O(n) time, and detect circular loops.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Node pointer chaining (val, next)",
            "In-place iterative reversal of a linked list in O(n) time and O(1) space",
            "Floyd's Tortoise and Hare two-pointer cycle detection algorithm",
          ],
          introduction: `A Linked List is a linear data structure where elements are not stored at contiguous memory locations. Instead, each node contains data and a pointer to the next node.`,
          whyItMatters: `Linked lists allow O(1) constant-time insertions at the head without shifting array memory.`,
          mainExample: {
            title: "Linked List In-Place Reversal",
            language: "javascript",
            code: `class ListNode {\n  constructor(val, next = null) { this.val = val; this.next = next; }\n}\n\nfunction reverseList(head) {\n  let prev = null, current = head;\n  while (current) {\n    const nextTemp = current.next;\n    current.next = prev;\n    prev = current;\n    current = nextTemp;\n  }\n  return prev;\n}\n\nconst list = new ListNode(1, new ListNode(2, new ListNode(3)));\nconsole.log("Reversed Head Val:", reverseList(list).val);`,
            executable: true,
            explanation: ["Iteratively rewires pointers in O(n) time and O(1) auxiliary space."],
          },
          detailedExplanation: ["Fast pointer moves 2 steps while slow moves 1 step; if they meet, a cycle exists."],
          commonMistakes: [],
          bestPractices: ["Always use dummy head pointers to simplify edge cases in linked list mutations."],
          summary: ["Linked lists provide flexible pointer-based dynamic node structures."],
        },
      ],
    },
    {
      id: "mod-dsa-4",
      slug: "stacks-queues",
      title: "Module 4: Stacks & Queues",
      description: "LIFO Stacks, FIFO Queues, monotonic stacks, and circular queue buffers.",
      lessons: [
        {
          id: "dsa-stack-queue",
          slug: "stacks-queues-and-monotonic-stack",
          courseSlug: "dsa",
          moduleSlug: "stacks-queues",
          title: "Stacks (LIFO), Queues (FIFO) & Monotonic Stacks",
          description: "Master LIFO stacks (call stack, undo/redo), FIFO queues (task scheduling), and valid parenthesis matching.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Stack LIFO (push, pop, peek) in O(1) time",
            "Queue FIFO (enqueue, dequeue) in O(1) time",
            "Valid Parentheses algorithm using a stack",
          ],
          introduction: `Stacks and Queues are constrained linear data structures with strict insertion and removal order rules.`,
          whyItMatters: `Stacks power browser Back/Forward history, recursive function call stacks, and expression evaluators.`,
          mainExample: {
            title: "Valid Parentheses with Stack",
            language: "javascript",
            code: `function isValid(s) {\n  const stack = [];\n  const map = { ")": "(", "}": "{", "]": "[" };\n  for (const char of s) {\n    if (char in map) {\n      if (stack.pop() !== map[char]) return false;\n    } else {\n      stack.push(char);\n    }\n  }\n  return stack.length === 0;\n}\n\nconsole.log("Valid '()[]{}':", isValid("()[]{}"));\nconsole.log("Valid '(]':", isValid("(]"));`,
            executable: true,
            explanation: ["Opening brackets push to stack; closing brackets pop and verify matching pair."],
          },
          detailedExplanation: ["Monotonic stacks maintain elements in strictly ascending or descending order for Next Greater Element queries."],
          commonMistakes: [],
          bestPractices: ["Use stacks for parsing nested expressions, HTML tags, and bracket matching."],
          summary: ["Stacks and queues enforce disciplined sequential access ordering."],
        },
      ],
    },
    {
      id: "mod-dsa-5",
      slug: "hash-tables",
      title: "Module 5: Hash Tables & Hash Sets",
      description: "Hash functions, collision resolution (chaining vs open addressing), and load factor resizing.",
      lessons: [
        {
          id: "dsa-hash-tables",
          slug: "hash-tables-and-collision-resolution",
          courseSlug: "dsa",
          moduleSlug: "hash-tables",
          title: "Hash Tables, Collision Resolution & O(1) Lookups",
          description: "Understand hash functions, separate chaining, open addressing, and achieving O(1) average time complexity.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How hash functions map arbitrary string keys to numeric array indices",
            "Collision resolution strategies (Separate Chaining vs Linear Probing)",
            "Load factor thresholds and dynamic array resizing",
          ],
          introduction: `A Hash Table is a data structure that implements an associative array abstract data type, a structure that can map keys to values with O(1) average lookup time.`,
          whyItMatters: `Hash tables power database indexes, in-memory caches (Redis), and associative arrays in all modern programming languages.`,
          mainExample: {
            title: "O(n) Two Sum with Hash Map",
            language: "javascript",
            code: `function twoSum(nums, target) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (seen.has(complement)) {\n      return [seen.get(complement), i];\n    }\n    seen.set(nums[i], i);\n  }\n  return [];\n}\n\nconsole.log("Indices:", twoSum([3, 2, 4], 6));`,
            executable: true,
            explanation: ["Map lookup checks complement presence in O(1) time per element."],
          },
          detailedExplanation: ["Poor hash functions cause clustering, degrading lookup performance from O(1) to O(n)."],
          commonMistakes: [],
          bestPractices: ["Use Hash Maps whenever you need instant O(1) key lookups."],
          summary: ["Hash tables provide near-instant data retrieval through efficient hashing."],
        },
      ],
    },
    {
      id: "mod-dsa-6",
      slug: "recursion",
      title: "Module 6: Recursion & Backtracking",
      description: "Base cases, recursive call stacks, tail call optimization, and backtracking algorithms (N-Queens).",
      lessons: [
        {
          id: "dsa-recursion",
          slug: "recursion-and-backtracking",
          courseSlug: "dsa",
          moduleSlug: "recursion",
          title: "Recursion, Base Cases & Backtracking",
          description: "Solve complex combinatorial search problems using recursion, call stack frames, and backtracking.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Formulating base cases to prevent stack overflow errors",
            "How the CPU call stack tracks recursive function frames",
            "The Backtracking algorithm template (Choose, Explore, Unchoose)",
          ],
          introduction: `Recursion is a method of solving problems where the solution depends on solutions to smaller instances of the same problem. Backtracking prunes invalid exploration branches early.`,
          whyItMatters: `Backtracking powers Sudoku solvers, maze exploration, and combinatorial subset generation.`,
          mainExample: {
            title: "Subsets Generation with Backtracking",
            language: "javascript",
            code: `function subsets(nums) {\n  const result = [];\n  function backtrack(start, current) {\n    result.push([...current]);\n    for (let i = start; i < nums.length; i++) {\n      current.push(nums[i]);     // Choose\n      backtrack(i + 1, current); // Explore\n      current.pop();             // Unchoose (Backtrack)\n    }\n  }\n  backtrack(0, []);\n  return result;\n}\n\nconsole.log("Subsets of [1, 2]:", subsets([1, 2]));`,
            executable: true,
            explanation: ["Backtrack explores every combination by choosing and undoing steps."],
          },
          detailedExplanation: ["Always establish the base case as the very first check in recursive functions."],
          commonMistakes: [],
          bestPractices: ["Identify base cases before writing any recursive logic."],
          summary: ["Recursion and backtracking break complex combinatorial problems into manageable steps."],
        },
      ],
    },
    {
      id: "mod-dsa-7",
      slug: "binary-trees",
      title: "Module 7: Binary Trees & Binary Search Trees (BST)",
      description: "Tree traversals (Pre/In/Post/Level-order), BST search/insert/delete, and balanced AVL trees.",
      lessons: [
        {
          id: "dsa-bst",
          slug: "binary-search-trees-and-traversals",
          courseSlug: "dsa",
          moduleSlug: "binary-trees",
          title: "Binary Search Trees (BST) & Tree Traversals",
          description: "Perform O(log n) searches, insertions, and in-order traversals on Binary Search Trees.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "The BST invariant: Left child < Root < Right child",
            "Tree traversals: In-Order (sorted), Pre-Order, and Post-Order",
            "Binary search tree insertion and lookup in O(h) time",
          ],
          introduction: `A Binary Search Tree (BST) is a rooted binary tree data structure whose internal nodes each store a key greater than all the keys in the node's left subtree and less than those in its right subtree.`,
          whyItMatters: `In-Order traversal on a BST produces elements in strictly ascending sorted order automatically in O(n) time!`,
          mainExample: {
            title: "BST Node & In-Order Traversal",
            language: "javascript",
            code: `class TreeNode {\n  constructor(val, left = null, right = null) {\n    this.val = val; this.left = left; this.right = right;\n  }\n}\n\nfunction inOrder(root, result = []) {\n  if (!root) return result;\n  inOrder(root.left, result);\n  result.push(root.val);\n  inOrder(root.right, result);\n  return result;\n}\n\nconst tree = new TreeNode(20, new TreeNode(10), new TreeNode(30));\nconsole.log("Sorted Traversal:", inOrder(tree));`,
            executable: true,
            explanation: ["In-order traversal visits left subtree, root, then right subtree."],
          },
          detailedExplanation: ["Unbalanced BSTs can degenerate into O(n) linked lists; self-balancing trees (AVL, Red-Black) maintain O(log n) height."],
          commonMistakes: [],
          bestPractices: ["Use tree structures for hierarchical data like DOM trees and file systems."],
          summary: ["BSTs combine the rapid search of sorted arrays with the dynamic insertion of linked lists."],
        },
      ],
    },
    {
      id: "mod-dsa-8",
      slug: "heaps",
      title: "Module 8: Heaps & Priority Queues",
      description: "Min-Heaps, Max-Heaps, binary heap array representation, Heapify, and Heap Sort.",
      lessons: [
        {
          id: "dsa-heaps",
          slug: "heaps-and-priority-queues",
          courseSlug: "dsa",
          moduleSlug: "heaps",
          title: "Binary Heaps & Priority Queues (O(log n))",
          description: "Extract minimum or maximum elements in O(1) time and maintain heap invariants in O(log n) with Min/Max Heaps.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Min-Heap and Max-Heap invariants",
            "Array representation of binary trees (parent = (i-1)/2, children = 2i+1, 2i+2)",
            "Building Priority Queues for top-K problems and event scheduling",
          ],
          introduction: `A Heap is a specialized tree-based data structure that satisfies the heap property: in a max heap, for any given node C, if P is a parent node of C, then the key of P is greater than or equal to the key of C.`,
          whyItMatters: `Heaps find the K largest elements in a stream of 1,000,000,000 items in O(N log K) time using only K memory.`,
          mainExample: {
            title: "Priority Queue Concept",
            language: "javascript",
            code: `// Array representation of Min-Heap: [10, 20, 15, 30, 40]\n// Root (index 0) always contains the minimum element\nconst minHeap = [10, 20, 15, 30, 40];\nconsole.log("Minimum Element O(1) Access:", minHeap[0]);`,
            executable: true,
            explanation: ["Root index 0 always guarantees constant time O(1) minimum access."],
          },
          detailedExplanation: ["Insertion and extraction take O(log n) time by bubbling elements up or down."],
          commonMistakes: [],
          bestPractices: ["Use Min-Heaps to find Top-K largest elements efficiently."],
          summary: ["Heaps power priority queues, Dijkstra's algorithm, and event simulation systems."],
        },
      ],
    },
    {
      id: "mod-dsa-9",
      slug: "graphs",
      title: "Module 9: Graph Representations, BFS & DFS",
      description: "Adjacency list vs adjacency matrix, Breadth-First Search (BFS), and Depth-First Search (DFS).",
      lessons: [
        {
          id: "dsa-graphs",
          slug: "breadth-first-and-depth-first-search",
          courseSlug: "dsa",
          moduleSlug: "graphs",
          title: "Graph Traversal: BFS (Shortest Path) & DFS",
          description: "Represent graphs via adjacency lists and traverse networks using BFS (Queue) and DFS (Stack/Recursion).",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Adjacency list vs adjacency matrix memory tradeoffs",
            "Breadth-First Search (BFS) using a Queue to find shortest paths in unweighted graphs",
            "Depth-First Search (DFS) for connected components and cycle detection",
          ],
          introduction: `A Graph is a non-linear data structure consisting of vertices (nodes) and edges that connect pairs of vertices.`,
          whyItMatters: `Graphs model social networks (friend connections), maps (GPS navigation), recommendation engines, and dependency trees.`,
          mainExample: {
            title: "Breadth-First Search (BFS) on Graph",
            language: "javascript",
            code: `function bfs(graph, start) {\n  const visited = new Set([start]);\n  const queue = [start];\n  const traversal = [];\n  \n  while (queue.length > 0) {\n    const node = queue.shift();\n    traversal.push(node);\n    for (const neighbor of graph[node] || []) {\n      if (!visited.has(neighbor)) {\n        visited.add(neighbor);\n        queue.push(neighbor);\n      }\n    }\n  }\n  return traversal;\n}\n\nconst graph = { A: ["B", "C"], B: ["D"], C: ["E"], D: [], E: [] };\nconsole.log("BFS Order:", bfs(graph, "A"));`,
            executable: true,
            explanation: ["BFS visits nodes layer-by-layer using a queue."],
          },
          detailedExplanation: ["Always track visited nodes with a Set to prevent infinite loops in cyclic graphs."],
          commonMistakes: [],
          bestPractices: ["Use BFS for shortest path in unweighted graphs; use DFS for topological sorting."],
          summary: ["BFS and DFS form the foundation of all network and pathfinding algorithms."],
        },
      ],
    },
    {
      id: "mod-dsa-10",
      slug: "advanced-graphs",
      title: "Module 10: Shortest Path & Minimum Spanning Trees (Dijkstra, Prim)",
      description: "Dijkstra's shortest path algorithm with priority queues, Bellman-Ford, and Union-Find (Disjoint Set).",
      lessons: [
        {
          id: "dsa-dijkstra",
          slug: "dijkstras-algorithm-and-union-find",
          courseSlug: "dsa",
          moduleSlug: "advanced-graphs",
          title: "Dijkstra's Shortest Path & Disjoint Set (Union-Find)",
          description: "Find shortest paths on weighted graphs with Dijkstra's algorithm and detect cycles with Union-Find.",
          durationMinutes: 24,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Dijkstra's greedy shortest path algorithm with Min-Heap in O((V + E) log V)",
            "Disjoint Set Union (DSU) with path compression and union by rank",
            "Kruskal's algorithm for Minimum Spanning Trees (MST)",
          ],
          introduction: `Dijkstra's algorithm finds the shortest path between nodes in a graph with non-negative edge weights (like highway travel times).`,
          whyItMatters: `Dijkstra's algorithm powers Google Maps routing, internet network packet routing (OSPF), and airline flight schedulers.`,
          mainExample: {
            title: "Dijkstra Shortest Path Concept",
            language: "javascript",
            code: `// Dijkstra computes min distance from source to all destinations\nconsole.log("Dijkstra Algorithm computes optimal weighted paths in O(E log V).");`,
            executable: true,
            explanation: ["Greedily relaxes shortest known distance using a priority queue."],
          },
          detailedExplanation: ["Union-Find with path compression achieves nearly constant O(α(n)) inverse Ackermann time."],
          commonMistakes: [],
          bestPractices: ["Use Dijkstra when edges are weighted positively; use Bellman-Ford if negative weights exist."],
          summary: ["Dijkstra and Union-Find solve complex routing and network connectivity problems."],
        },
      ],
    },
    {
      id: "mod-dsa-11",
      slug: "dynamic-programming",
      title: "Module 11: Dynamic Programming (Memoization & Tabulation)",
      description: "Overlapping subproblems, optimal substructure, top-down memoization, bottom-up tabulation, and knapsack.",
      lessons: [
        {
          id: "dsa-dp",
          slug: "dynamic-programming-patterns",
          courseSlug: "dsa",
          moduleSlug: "dynamic-programming",
          title: "Dynamic Programming: Top-Down & Bottom-Up Patterns",
          description: "Turn exponential O(2ⁿ) recursive algorithms into linear O(n) solutions using memoization and bottom-up tabulation.",
          durationMinutes: 24,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Identifying DP problems: Overlapping Subproblems & Optimal Substructure",
            "Top-down Memoization (recursion + cache Map)",
            "Bottom-up Tabulation (iterative DP array) and space optimization",
          ],
          introduction: `Dynamic Programming (DP) is an algorithmic technique for solving optimization problems by breaking them down into simpler subproblems and storing the results to avoid duplicate computation.`,
          whyItMatters: `Calculating the 50th Fibonacci number with raw recursion takes ~11 days (2⁵⁰ operations). With DP, it takes 50 operations (<1 millisecond!).`,
          mainExample: {
            title: "Climbing Stairs DP (Bottom-Up Tabulation)",
            language: "javascript",
            code: `function climbStairs(n) {\n  if (n <= 2) return n;\n  let prev2 = 1, prev1 = 2;\n  for (let i = 3; i <= n; i++) {\n    const current = prev1 + prev2;\n    prev2 = prev1;\n    prev1 = current;\n  }\n  return prev1;\n}\n\nconsole.log("Distinct ways to climb 10 stairs:", climbStairs(10));`,
            executable: true,
            explanation: ["Space optimized bottom-up DP runs in O(n) time and O(1) space."],
          },
          detailedExplanation: ["The 0/1 Knapsack problem demonstrates optimal decision making under capacity constraints."],
          commonMistakes: [],
          bestPractices: ["Always write the recursive recurrence relation first before optimizing to iterative DP."],
          summary: ["Dynamic programming turns intractable exponential problems into blazing fast polynomial algorithms."],
        },
      ],
    },
  ],
};
