import { Course } from "@/types";

export const goCourse: Course = {
  id: "course-go",
  slug: "go",
  title: "Go (Golang) Cloud-Native Microservices",
  tagline: "Concurrency with Goroutines & Channels, fast compiled binaries, and high-throughput microservices.",
  description: "Master Go: syntax simplicity, structs, interfaces, error handling idioms, goroutines, channels, sync primitives (Mutex, WaitGroup), HTTP web servers, and building cloud-native distributed microservices.",
  category: "Programming Languages",
  level: "Intermediate",
  estimatedHours: 24,
  icon: "Server",
  badgeColor: "blue",
  prerequisites: ["Basic Programming Knowledge"],
  skillsGained: [
    "Go Idiomatic Syntax & Explicit Error Handling (val, err := ...)",
    "Structs, Methods & Implicit Interface Composition",
    "Lightweight Concurrency with Goroutines & Channels",
    "High-Performance Native HTTP Web Services",
    "Building Fast, Self-Contained Static Cloud Binaries",
  ],
  featured: false,
  modules: [
    {
      id: "mod-go-1",
      slug: "intro",
      title: "Module 1: Go Philosophy & Toolchain",
      description: "Go compiler (go build), formatting (gofmt), packages, and main package.",
      lessons: [
        {
          id: "go-intro",
          slug: "go-introduction",
          courseSlug: "go",
          moduleSlug: "intro",
          title: "Go Introduction & The Go Toolchain",
          description: "Discover Go's design philosophy, simple orthogonal syntax, and the go CLI toolchain.",
          durationMinutes: 14,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Why Go was created at Google for scalable systems",
            "Compiling static binaries with 'go build'",
            "Package main and the func main() entry point",
          ],
          introduction: `Go (Golang) is an open-source programming language developed by Google to build simple, fast, and reliable software at enterprise scale.`,
          whyItMatters: `Go is the language of cloud infrastructure, powering Docker, Kubernetes, Terraform, Prometheus, and CockroachDB.`,
          mainExample: {
            title: "Hello Go Program",
            language: "go",
            code: `package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("KWAS Academy: Cloud-Native Go Engineering")\n}`,
            executable: true,
            explanation: ["package main and func main() declare an executable application."],
          },
          detailedExplanation: ["Go compiles into a single, self-contained binary with zero dynamic library dependencies."],
          commonMistakes: [],
          bestPractices: ["Always run 'gofmt' or 'go fmt' on code before committing."],
          summary: ["Go emphasizes simplicity, readability, and rapid compilation."],
        },
      ],
    },
    {
      id: "mod-go-2",
      slug: "syntax-variables",
      title: "Module 2: Basic Syntax, Variables & Constants",
      description: "Short variable declaration (:=), explicit var, typed constants (iota), and zero values.",
      lessons: [
        {
          id: "go-variables",
          slug: "variables-and-zero-values",
          courseSlug: "go",
          moduleSlug: "syntax-variables",
          title: "Variables, Short Declaration (:=) & Zero Values",
          description: "Declare variables with short assignment (:=), understand default zero values (0, '', nil), and use iota for enums.",
          durationMinutes: 14,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Short variable declaration (name := 'Alex') inside functions",
            "Go's guaranteed zero values (0 for numbers, false for booleans, nil for pointers)",
            "Auto-incrementing enum constants with iota",
          ],
          introduction: `Go is statically typed with strong type inference. Uninitialized variables in Go are automatically set to their zero value, preventing uninitialized memory bugs.`,
          whyItMatters: `Zero values eliminate null pointer bugs in basic variables, ensuring predictable initialization across all types.`,
          mainExample: {
            title: "Short Declarations & iota Constants",
            language: "go",
            code: `package main\nimport "fmt"\n\nconst (\n    RoleStudent = iota // 0\n    RoleTeacher        // 1\n    RoleAdmin          // 2\n)\n\nfunc main() {\n    name := "Alex Dev"\n    var count int // Zero value: 0\n    fmt.Printf("User: %s | Count: %d | Role: %d\\n", name, count, RoleAdmin)\n}`,
            executable: true,
            explanation: [":= infers the type automatically inside function bodies."],
          },
          detailedExplanation: ["Constants must be resolvable at compile time."],
          commonMistakes: [],
          bestPractices: ["Use := for local variables; use explicit var for package-level declarations."],
          summary: ["Guaranteed zero values make Go initialization predictable and safe."],
        },
      ],
    },
    {
      id: "mod-go-3",
      slug: "control-flow",
      title: "Module 3: Control Flow (if, switch, for)",
      description: "if with short statement, switch with automatic break, and for as the only loop keyword.",
      lessons: [
        {
          id: "go-control",
          slug: "control-flow-and-loops",
          courseSlug: "go",
          moduleSlug: "control-flow",
          title: "If Initializers, Switch & The Unified 'for' Loop",
          description: "Master if statements with inline initializers (if err := ...; err != nil) and unified for loops.",
          durationMinutes: 15,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "If statements with local variable initialization scope",
            "Why Go has only one loop keyword ('for') that handles while, infinite, and range loops",
            "Switch statements without explicit break requirements",
          ],
          introduction: `Go intentionally simplifies control flow: 'for' is the only loop construct, and 'switch' breaks automatically without fallthrough.`,
          whyItMatters: `The 'if err := doWork(); err != nil' pattern scopes the error variable strictly to the conditional block.`,
          mainExample: {
            title: "If with Initializer & For-Range Loop",
            language: "go",
            code: `package main\nimport "fmt"\n\nfunc main() {\n    scores := []int{95, 88, 92}\n    for idx, score := range scores {\n        fmt.Printf("Student #%d Score: %d\\n", idx+1, score)\n    }\n}`,
            executable: true,
            explanation: ["for...range iterates over slices, arrays, maps, and channels."],
          },
          detailedExplanation: ["Go switch statements support multiple case matches (case 1, 2, 3:)."],
          commonMistakes: [],
          bestPractices: ["Use if initializers to scope temporary variables cleanly."],
          summary: ["Go's unified control flow constructs keep codebases simple and readable."],
        },
      ],
    },
    {
      id: "mod-go-4",
      slug: "slices-maps",
      title: "Module 4: Arrays, Slices & Maps",
      description: "Fixed arrays, dynamic slices (make, append), slice internals (ptr, len, cap), and key-value maps.",
      lessons: [
        {
          id: "go-slices-maps",
          slug: "slices-and-maps-internals",
          courseSlug: "go",
          moduleSlug: "slices-maps",
          title: "Slices Header Architecture & Maps",
          description: "Understand slice internals (pointer, length, capacity), make(), append(), and map lookups (val, ok := map[key]).",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "The 3-word slice header: Pointer to backing array, Length, and Capacity",
            "Dynamically growing slices with append() and pre-allocating with make()",
            "The comma-ok idiom for verifying map key presence (val, ok := m[key])",
          ],
          introduction: `Slices are dynamically-sized, flexible views into the elements of an array. In practice, slices are much more common than fixed-length arrays.`,
          whyItMatters: `Pre-allocating slice capacity with make([]T, 0, 1000) prevents expensive backing array reallocations during loops.`,
          mainExample: {
            title: "Slice Append & Comma-OK Map Lookup",
            language: "go",
            code: `package main\nimport "fmt"\n\nfunc main() {\n    // Dynamic slice\n    skills := make([]string, 0, 4)\n    skills = append(skills, "Go", "Docker", "Postgres")\n\n    // Map with comma-ok idiom\n    metrics := map[string]int{"cpu": 45, "ram": 60}\n    if val, ok := metrics["cpu"]; ok {\n        fmt.Printf("CPU Metric: %d%% | Skills: %v\\n", val, skills)\n    }\n}`,
            executable: true,
            explanation: ["comma-ok idiom verifies if a key actually exists in the map."],
          },
          detailedExplanation: ["When a slice exceeds its capacity during append, Go doubles the backing array size automatically."],
          commonMistakes: [],
          bestPractices: ["Always use the comma-ok idiom to test for map key existence."],
          summary: ["Slices and maps provide high-speed, dynamic data management in Go."],
        },
      ],
    },
    {
      id: "mod-go-5",
      slug: "functions",
      title: "Module 5: Functions, Multiple Returns & Named Returns",
      description: "Multiple return values, named returns, variadic parameters, defer statement, and first-class functions.",
      lessons: [
        {
          id: "go-functions",
          slug: "multiple-returns-and-defer",
          courseSlug: "go",
          moduleSlug: "functions",
          title: "Multiple Return Values & The 'defer' Statement",
          description: "Return multiple values (result, error) and guarantee resource cleanup with LIFO 'defer' statements.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Functions returning multiple values (value, error)",
            "The 'defer' statement for guaranteed cleanup before function exit",
            "LIFO (Last In, First Out) execution order of multiple defers",
          ],
          introduction: `Go functions can return any number of results. The 'defer' keyword schedules a function call to run immediately before the enclosing function returns.`,
          whyItMatters: `Placing 'defer file.Close()' immediately after opening a file guarantees the file descriptor closes, preventing leaks.`,
          mainExample: {
            title: "Multiple Returns & Defer Cleanup",
            language: "go",
            code: `package main\nimport "fmt"\n\nfunc divide(a, b float64) (float64, error) {\n    if b == 0 {\n        return 0, fmt.Errorf("division by zero")\n    }\n    return a / b, nil\n}\n\nfunc main() {\n    defer fmt.Println("Cleanup: Execution completed.")\n    res, err := divide(100, 4)\n    if err == nil {\n        fmt.Println("Result:", res)\n    }\n}`,
            executable: true,
            explanation: ["defer runs right before main() returns."],
          },
          detailedExplanation: ["Defer statements evaluate their arguments immediately when encountered."],
          commonMistakes: [],
          bestPractices: ["Always pair resource acquisition (opening files/locks) with an immediate defer cleanup."],
          summary: ["Multiple returns and defer make resource management explicit and clean."],
        },
      ],
    },
    {
      id: "mod-go-6",
      slug: "structs-methods",
      title: "Module 6: Structs, Methods & Pointer Receivers",
      description: "Struct definitions, embedded structs (composition), value receivers vs pointer receivers (*T).",
      lessons: [
        {
          id: "go-structs",
          slug: "structs-and-pointer-receivers",
          courseSlug: "go",
          moduleSlug: "structs-methods",
          title: "Structs, Composition & Value vs Pointer Receivers",
          description: "Define structured data types, embed structs for composition, and mutate state with pointer receivers (*T).",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Defining struct data structures",
            "Value receivers func (t T) vs Pointer receivers func (t *T)",
            "Struct embedding (composition) instead of classical OOP inheritance",
          ],
          introduction: `Go does not have classes or inheritance. Instead, it uses Structs with Methods, and achieves code reuse through Struct Embedding (Composition).`,
          whyItMatters: `Using a value receiver creates a copy of the struct; a pointer receiver (*T) mutates the original struct in place.`,
          mainExample: {
            title: "Struct with Pointer Receiver Method",
            language: "go",
            code: `package main\nimport "fmt"\n\ntype Developer struct {\n    Name  string\n    Level int\n}\n\n// Pointer receiver mutates the struct\nfunc (d *Developer) Promote() {\n    d.Level++\n}\n\nfunc main() {\n    dev := Developer{Name: "Alex", Level: 1}\n    dev.Promote()\n    fmt.Printf("%s is now Level %d\\n", dev.Name, dev.Level)\n}`,
            executable: true,
            explanation: ["(d *Developer) pointer receiver modifies the Level field directly."],
          },
          detailedExplanation: ["Embedded structs promote their fields to the outer struct automatically."],
          commonMistakes: [],
          bestPractices: ["Use pointer receivers whenever a method needs to mutate the struct or if the struct is large."],
          summary: ["Structs and pointer receivers provide clean, explicit data mutation."],
        },
      ],
    },
    {
      id: "mod-go-7",
      slug: "interfaces",
      title: "Module 7: Interfaces & Implicit Composition",
      description: "Implicit interface implementation (duck typing), interface{}, any, and type assertions.",
      lessons: [
        {
          id: "go-interfaces",
          slug: "implicit-interfaces-and-type-switches",
          courseSlug: "go",
          moduleSlug: "interfaces",
          title: "Implicit Interfaces & Type Assertions",
          description: "Implement interfaces implicitly without 'implements' keywords, and inspect dynamic types with type switches.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Implicit interface satisfaction: if a struct implements the methods, it implements the interface",
            "The io.Reader and io.Writer universal interfaces",
            "Type assertions (val, ok := i.(MyType)) and type switches",
          ],
          introduction: `In Go, interfaces are satisfied implicitly. A type implements an interface by simply implementing its methods. There is no explicit 'implements' declaration.`,
          whyItMatters: `Implicit interfaces allow you to define interfaces for third-party packages without modifying their source code.`,
          mainExample: {
            title: "Implicit Interface Implementation",
            language: "go",
            code: `package main\nimport "fmt"\n\ntype Speaker interface {\n    Speak() string\n}\n\ntype Bot struct{}\nfunc (b Bot) Speak() string { return "Beep Boop" }\n\nfunc greet(s Speaker) {\n    fmt.Println(s.Speak())\n}\n\nfunc main() {\n    greet(Bot{}) // Bot implicitly satisfies Speaker\n}`,
            executable: true,
            explanation: ["Bot satisfies Speaker simply by having a Speak() method."],
          },
          detailedExplanation: ["Keep interfaces small: 'The bigger the interface, the weaker the abstraction' (Rob Pike)."],
          commonMistakes: [],
          bestPractices: ["Define 1-method or 2-method interfaces at the consumer site."],
          summary: ["Implicit interfaces decouple Go modules cleanly."],
        },
      ],
    },
    {
      id: "mod-go-8",
      slug: "error-handling",
      title: "Module 8: Explicit Error Handling Idioms",
      description: "Error interface, errors.Is, errors.As, custom error types, and panic/recover.",
      lessons: [
        {
          id: "go-errors",
          slug: "explicit-error-handling-and-errors-is",
          courseSlug: "go",
          moduleSlug: "error-handling",
          title: "Explicit Error Handling & Error Wrapping (errors.Is)",
          description: "Handle errors as values, wrap error context with fmt.Errorf('%w', err), and inspect error chains with errors.Is.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Why Go treats errors as explicit values rather than hidden exceptions",
            "Wrapping error context with %w (fmt.Errorf('failed auth: %w', err))",
            "Checking wrapped errors with errors.Is() and errors.As()",
          ],
          introduction: `Go does not have try/catch exception hierarchies. Errors are simply values that implement the built-in 'error' interface (Error() string).`,
          whyItMatters: `Explicit error handling forces developers to consider failure cases at every step, creating exceptionally resilient backend services.`,
          mainExample: {
            title: "Error Wrapping & errors.Is",
            language: "go",
            code: `package main\nimport (\n    "errors"\n    "fmt"\n)\n\nvar ErrNotFound = errors.New("record not found")\n\nfunc findUser(id int) error {\n    return fmt.Errorf("database query failed: %w", ErrNotFound)\n}\n\nfunc main() {\n    err := findUser(404)\n    if errors.Is(err, ErrNotFound) {\n        fmt.Println("Handled: Specific ErrNotFound matched successfully.")\n    }\n}`,
            executable: true,
            explanation: ["errors.Is unwraps the error chain to check if ErrNotFound is in the stack."],
          },
          detailedExplanation: ["Use panic/recover strictly for truly unrecoverable programmer bugs, never for expected runtime errors."],
          commonMistakes: [],
          bestPractices: ["Always wrap errors with context using fmt.Errorf('...: %w', err)."],
          summary: ["Errors as values make failure modes clear, debuggable, and explicit."],
        },
      ],
    },
    {
      id: "mod-go-9",
      slug: "concurrency",
      title: "Module 9: Goroutines, Channels & Select",
      description: "Lightweight Goroutines, buffered vs unbuffered channels, select multiplexing, and worker pools.",
      lessons: [
        {
          id: "go-concurrency",
          slug: "goroutines-channels-and-select",
          courseSlug: "go",
          moduleSlug: "concurrency",
          title: "Goroutines, Channels & The 'select' Statement",
          description: "Spawn millions of lightweight Goroutines, send data through typed channels, and multiplex with 'select'.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Goroutines: lightweight green threads managed by the Go runtime (2KB stack)",
            "Unbuffered (synchronous rendezvous) vs Buffered channels",
            "The 'select' statement for multiplexing multiple channel operations",
          ],
          introduction: `Concurrency in Go is built around Goroutines and Channels, based on Tony Hoare's Communicating Sequential Processes (CSP) formalism.`,
          whyItMatters: `"Do not communicate by sharing memory; instead, share memory by communicating."`,
          mainExample: {
            title: "Channel Select with Timeout",
            language: "go",
            code: `package main\nimport (\n    "fmt"\n    "time"\n)\n\nfunc main() {\n    ch := make(chan string, 1)\n    go func() {\n        time.Sleep(50 * time.Millisecond)\n        ch <- "Data Payload Ready"\n    }()\n\n    select {\n    case msg := <-ch:\n        fmt.Println("Received:", msg)\n    case <-time.After(100 * time.Millisecond):\n        fmt.Println("Timeout reached!")\n    }\n}`,
            executable: true,
            explanation: ["select waits on whichever channel communication completes first."],
          },
          detailedExplanation: ["Closing a channel signals all listening goroutines that no more data will be sent."],
          commonMistakes: [],
          bestPractices: ["Always ensure channel senders close channels, never channel receivers."],
          summary: ["Goroutines and channels make high-scale concurrency effortless."],
        },
      ],
    },
    {
      id: "mod-go-10",
      slug: "sync-primitives",
      title: "Module 10: Sync Primitives (Mutex, WaitGroup, Once)",
      description: "sync.Mutex, sync.RWMutex, sync.WaitGroup, sync.Once, and the Go Race Detector (-race).",
      lessons: [
        {
          id: "go-sync",
          slug: "sync-waitgroup-and-mutex",
          courseSlug: "go",
          moduleSlug: "sync-primitives",
          title: "sync.WaitGroup, sync.Mutex & Race Detector (-race)",
          description: "Synchronize goroutine completion with WaitGroup, protect shared memory with Mutex, and detect race conditions.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Waiting for N concurrent workers with sync.WaitGroup (Add, Done, Wait)",
            "Protecting critical shared variables with sync.Mutex and sync.RWMutex",
            "Running the Go Race Detector (go test -race) to catch data races",
          ],
          introduction: `When channels are not appropriate, the standard library 'sync' package provides classical low-level synchronization primitives like Mutexes and WaitGroups.`,
          whyItMatters: `Running 'go run -race' detects subtle multithreaded memory corruption before code reaches production.`,
          mainExample: {
            title: "sync.WaitGroup Coordination",
            language: "go",
            code: `package main\nimport (\n    "fmt"\n    "sync"\n)\n\nfunc main() {\n    var wg sync.WaitGroup\n    for i := 1; i <= 3; i++ {\n        wg.Add(1)\n        go func(id int) {\n            defer wg.Done()\n            fmt.Printf("Worker #%d done\\n", id)\n        }(i)\n    }\n    wg.Wait() // Block until all 3 workers call Done()\n    fmt.Println("All workers finished.")\n}`,
            executable: true,
            explanation: ["wg.Wait() blocks until the WaitGroup counter reaches 0."],
          },
          detailedExplanation: ["Always pass WaitGroup pointers (&wg), never pass WaitGroups by value."],
          commonMistakes: [],
          bestPractices: ["Always run tests with the -race flag enabled in CI pipelines."],
          summary: ["Sync primitives coordinate parallel tasks and protect shared state."],
        },
      ],
    },
    {
      id: "mod-go-11",
      slug: "web-microservices",
      title: "Module 11: Building Native Cloud HTTP Microservices",
      description: "net/http, context.Context cancellation, JSON encoding, and building cloud microservices.",
      lessons: [
        {
          id: "go-http",
          slug: "net-http-and-context",
          courseSlug: "go",
          moduleSlug: "web-microservices",
          title: "Production HTTP Services & context.Context Cancellation",
          description: "Build high-throughput HTTP microservices with net/http, serialize JSON, and propagate timeouts via context.Context.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Building REST microservices using standard library net/http",
            "High-speed streaming JSON with json.NewDecoder and json.NewEncoder",
            "Propagating request cancellations and timeouts with context.Context",
          ],
          introduction: `The Go standard library contains a world-class, production-ready HTTP server capable of serving tens of thousands of requests per second.`,
          whyItMatters: `context.Context ensures that if a user cancels an HTTP request, downstream database queries are aborted immediately, saving database CPU.`,
          mainExample: {
            title: "Production HTTP Handler with JSON",
            language: "go",
            code: `package main\nimport (\n    "encoding/json"\n    "net/http"\n)\n\ntype HealthResponse struct {\n    Status string \`json:"status"\`\n}\n\nfunc healthHandler(w http.ResponseWriter, r *http.Request) {\n    w.Header().Set("Content-Type", "application/json")\n    json.NewEncoder(w).Encode(HealthResponse{Status: "healthy"})\n}\n\nfunc main() {\n    http.HandleFunc("/health", healthHandler)\n    http.ListenAndServe(":8080", nil)\n}`,
            executable: false,
            explanation: ["json.NewEncoder streams JSON directly into the HTTP response stream."],
          },
          detailedExplanation: ["Every incoming http.Request contains a r.Context() bound to the client socket lifetime."],
          commonMistakes: [],
          bestPractices: ["Always pass context.Context as the first argument in backend functions (ctx context.Context)."],
          summary: ["Go standard library provides all tools needed to build high-scale cloud microservices."],
        },
      ],
    },
  ],
};
