import { Course } from "@/types";

export const htmlCourse: Course = {
  id: "course-html",
  slug: "html",
  title: "HTML5 Documentation & Architecture",
  tagline: "The foundation of the World Wide Web — master semantics, forms, accessibility, and modern browser APIs.",
  description: "Comprehensive HTML5 curriculum: syntax, document object trees, semantic elements, modern forms, accessible markup (ARIA), canvas 2D, SVG, media streaming, web storage, and SEO optimization.",
  category: "Frontend",
  level: "Beginner",
  estimatedHours: 18,
  icon: "FileCode2",
  badgeColor: "orange",
  prerequisites: ["None — suitable for complete beginners."],
  skillsGained: [
    "Semantic HTML5 Markup & Document Trees",
    "Forms & HTML5 Validation Engines",
    "Web Accessibility (WCAG 2.2 / ARIA)",
    "Canvas 2D & Graphics Rendering",
    "Web Storage APIs (LocalStorage/SessionStorage/IndexedDB)",
    "SEO Meta Architecture & Open Graph Protocols",
  ],
  featured: true,
  modules: [
    {
      id: "mod-html-1",
      slug: "fundamentals",
      title: "Module 1: Getting Started & Web Platform Architecture",
      description: "Understand the web browser engine, document tree, doctype, and foundational tags.",
      lessons: [
        {
          id: "html-intro",
          slug: "html-introduction",
          courseSlug: "html",
          moduleSlug: "fundamentals",
          title: "HTML Introduction & The Web Platform",
          description: "Discover what HTML is, how web browsers render document trees, and write your first valid HTML5 document.",
          durationMinutes: 10,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "What HTML (HyperText Markup Language) is and how it powers the web",
            "The role of the DOM (Document Object Model) and browser rendering engines",
            "The required structure of a standards-compliant HTML5 document",
            "How to write and run your first HTML webpage",
          ],
          introduction: `HTML (HyperText Markup Language) is the standard markup language used to structure web pages. When you navigate to any website, your browser receives an HTML document, parses its elements into a tree structure called the Document Object Model (DOM), and paints the pixels on your screen.`,
          whyItMatters: `Every web application in existence—from simple blogs to enterprise platforms like Google Docs and Netflix—relies on HTML as its structural backbone. Clean, valid HTML ensures your application is fast, accessible to screen readers, and easily indexed by search engines.`,
          syntax: `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Page Title</title>\n  </head>\n  <body>\n    <!-- Visible content goes here -->\n  </body>\n</html>`,
          mainExample: {
            title: "A Complete Valid HTML5 Webpage",
            language: "html",
            code: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Welcome to KWAS Academy</title>\n</head>\n<body>\n  <header>\n    <h1>KWAS Academy</h1>\n    <p>Learn. Build. Master.</p>\n  </header>\n  <main>\n    <h2>Start Your Developer Journey</h2>\n    <p>Master programming from zero to software engineering.</p>\n  </main>\n  <footer>\n    <p>&copy; 2026 KWAS Academy. All rights reserved.</p>\n  </footer>\n</body>\n</html>`,
            executable: true,
            explanation: [
              "<!DOCTYPE html> tells the browser engine to render in modern standards mode.",
              "<html lang='en'> represents the root element of the document.",
              "<head> contains metadata, viewport instructions, stylesheets, and page title.",
              "<meta name='viewport' content='width=device-width, initial-scale=1.0'> enables mobile responsiveness.",
              "<body> holds all visual content rendered inside the browser viewport.",
            ],
          },
          detailedExplanation: [
            "Line 1: <!DOCTYPE html> is an instruction to the web browser about what version of HTML the page is written in.",
            "Line 2: <html lang='en'> is the root container. The lang attribute helps search engines and screen readers parse pronunciation correctly.",
            "Lines 3-7: <head> holds non-visual configurations such as charset encoding UTF-8.",
            "Lines 8-22: <body> contains the document body. Browsers construct the DOM hierarchy based on nested parent-child relationships here.",
          ],
          commonMistakes: [],
          bestPractices: [
            "Always include <!DOCTYPE html> as the very first line of your document.",
            "Always define the lang attribute on the <html> root element.",
          ],
          realWorldExample: {
            title: "Production Application Shell",
            scenario: "High-performance SaaS web application template with SEO meta tags and accessible landmarks.",
            language: "html",
            code: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>KWAS Academy</title>\n</head>\n<body>\n  <main id="main-content">\n    <h1>Master Engineering</h1>\n  </main>\n</body>\n</html>`,
            takeaway: "Clean landmarks guarantee rapid page rendering and screen reader traversal.",
          },
          summary: ["HTML structures the web through hierarchical element trees called the DOM."],
        },
      ],
    },
    {
      id: "mod-html-2",
      slug: "text-and-structure",
      title: "Module 2: Document Structure, Headings & Text Formatting",
      description: "H1-H6 hierarchy, paragraphs, lists, quotations, and inline text formatting.",
      lessons: [
        {
          id: "html-headings",
          slug: "headings-paragraphs-lists",
          courseSlug: "html",
          moduleSlug: "text-and-structure",
          title: "Headings, Paragraphs & Ordered/Unordered Lists",
          description: "Establish strong typographic hierarchy with h1-h6 headings, paragraphs, and nested lists.",
          durationMinutes: 12,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Proper h1 through h6 heading hierarchy for SEO",
            "Paragraphs, line breaks (<br>), and thematic breaks (<hr>)",
            "Ordered (<ol>), unordered (<ul>), and description lists (<dl>)",
          ],
          introduction: `Text is the core carrier of information on the web. Search engine bots and screen readers rely on heading hierarchy to generate table-of-contents outlines for your web pages.`,
          whyItMatters: `Skipping heading levels (e.g. going from h1 directly to h4) breaks accessibility navigation for blind users and penalizes search engine rankings.`,
          mainExample: {
            title: "Semantic Text & List Structure",
            language: "html",
            code: `<article>\n  <h1>Modern Web Development</h1>\n  <p>Web engineering combines structure, styling, and logic.</p>\n  \n  <h2>Core Technologies</h2>\n  <ul>\n    <li>HTML5 for Structure</li>\n    <li>CSS3 for Presentation</li>\n    <li>JavaScript for Behavior</li>\n  </ul>\n</article>`,
            executable: true,
            explanation: ["H1 is the primary page title.", "H2 represents major sub-sections."],
          },
          detailedExplanation: ["Always have only one <h1> per page representing the central topic."],
          commonMistakes: [],
          bestPractices: ["Never use headings just to make text bigger; use CSS for sizing."],
          summary: ["Headings create the logical outline of web documents."],
        },
      ],
    },
    {
      id: "mod-html-3",
      slug: "semantics",
      title: "Module 3: Semantic Landmarks & Document Outline",
      description: "Master header, nav, main, section, article, aside, and footer for accessibility and SEO.",
      lessons: [
        {
          id: "html-semantics",
          slug: "html-semantics",
          courseSlug: "html",
          moduleSlug: "semantics",
          title: "Semantic Elements & Landmark Navigation",
          description: "Master header, nav, main, section, article, aside, and footer for accessibility and SEO.",
          durationMinutes: 15,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Why semantic elements are superior to div soup",
            "The distinct purpose of section, article, aside, and nav",
            "How screen readers navigate landmarks",
          ],
          introduction: `Semantic HTML refers to tags that carry meaning rather than just appearance. Elements like <article>, <section>, <nav>, and <aside> communicate the type of content they contain.`,
          whyItMatters: `Accessible landmarks allow visually impaired users to jump directly to main content or navigation sections without tabbing through 50 repetitive links.`,
          mainExample: {
            title: "Semantic Page Architecture",
            language: "html",
            code: `<header>\n  <nav aria-label="Primary Navigation">\n    <a href="/">Home</a>\n  </nav>\n</header>\n<main>\n  <article>\n    <h1>Semantic Web Design</h1>\n  </article>\n</main>`,
            executable: true,
            explanation: ["<article> represents a standalone document.", "<nav> holds primary links."],
          },
          detailedExplanation: ["<main> should only appear once per document and contains the central content."],
          commonMistakes: [],
          bestPractices: ["Always prefer semantic tags over generic <div> containers."],
          summary: ["Semantic elements clarify structure for search bots and screen readers."],
        },
      ],
    },
    {
      id: "mod-html-4",
      slug: "hyperlinks",
      title: "Module 4: Links, Anchors & URL Navigation",
      description: "Anchor tags, relative vs absolute paths, target blank security, and fragment identifiers.",
      lessons: [
        {
          id: "html-links",
          slug: "hyperlinks-and-anchors",
          courseSlug: "html",
          moduleSlug: "hyperlinks",
          title: "Hyperlinks, Relative Paths & Target Security",
          description: "Connect web documents with href anchors, mailto links, deep page fragments, and secure target='_blank'.",
          durationMinutes: 12,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Creating links with the <a> anchor element",
            "Relative paths (/about) vs absolute URLs (https://...)",
            "Preventing security vulnerabilities with rel='noopener noreferrer'",
          ],
          introduction: `Hyperlinks are what transform isolated documents into the World Wide Web. The <a> tag creates links to external sites, internal routes, downloadable files, email addresses, and specific section IDs on the same page.`,
          whyItMatters: `Opening external links with target='_blank' without rel='noopener noreferrer' exposes your site to tab-nabbing vulnerabilities.`,
          mainExample: {
            title: "Secure Hyperlinks & Jump Anchors",
            language: "html",
            code: `<!-- Internal Navigation -->\n<a href="/courses">Explore Courses</a>\n\n<!-- Secure External Link -->\n<a href="https://github.com" target="_blank" rel="noopener noreferrer">\n  Visit GitHub (Opens in new tab)\n</a>\n\n<!-- Page Fragment Jump -->\n<a href="#faq-section">Jump to FAQs</a>`,
            executable: true,
            explanation: ["rel='noopener noreferrer' prevents the opened page from hijacking window.opener."],
          },
          detailedExplanation: ["Fragment anchors (#id) scroll the browser window directly to an element with matching id."],
          commonMistakes: [],
          bestPractices: ["Always use meaningful link text rather than 'click here'."],
          summary: ["Anchors link the world's knowledge with accessible, secure references."],
        },
      ],
    },
    {
      id: "mod-html-5",
      slug: "multimedia",
      title: "Module 5: Multimedia, Images, Audio & Video Streaming",
      description: "Responsive images, srcset, picture element, lazy loading, audio, and video codecs.",
      lessons: [
        {
          id: "html-media",
          slug: "responsive-images-audio-video",
          courseSlug: "html",
          moduleSlug: "multimedia",
          title: "Responsive Images, Lazy Loading & Native Media",
          description: "Deliver high-performance media: <img> alt attributes, loading='lazy', srcset, <picture>, and <video>.",
          durationMinutes: 16,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Descriptive alt text for accessibility and SEO",
            "Native lazy loading (loading='lazy') for instant Core Web Vitals speed",
            "Adaptive responsive images with <picture> and srcset",
          ],
          introduction: `Modern web pages rely heavily on images and streaming video. HTML5 provides built-in media elements with hardware-accelerated playback and responsive image resolution switching.`,
          whyItMatters: `Unoptimized images account for over 60% of total page weight. Using loading='lazy' and proper width/height attributes prevents Cumulative Layout Shift (CLS).`,
          mainExample: {
            title: "Responsive Picture Element & Lazy Loading",
            language: "html",
            code: `<picture>\n  <source srcset="hero-large.webp" media="(min-width: 1024px)">\n  <source srcset="hero-medium.webp" media="(min-width: 640px)">\n  <img src="hero-small.webp" alt="KWAS Academy Developer Terminal" loading="lazy" width="800" height="450">\n</picture>`,
            executable: true,
            explanation: ["Browser chooses the optimal image format and resolution automatically."],
          },
          detailedExplanation: ["Always specify width and height attributes to reserve aspect ratio layout space."],
          commonMistakes: [],
          bestPractices: ["Always provide descriptive alt text for non-decorative images."],
          summary: ["Native HTML5 media elements enable rich, responsive multimedia experiences."],
        },
      ],
    },
    {
      id: "mod-html-6",
      slug: "tables",
      title: "Module 6: Tables & Tabular Data Representation",
      description: "Accessible tabular data: table, thead, tbody, th, tr, td, colgroup, and caption.",
      lessons: [
        {
          id: "html-tables",
          slug: "accessible-html-tables",
          courseSlug: "html",
          moduleSlug: "tables",
          title: "Accessible Data Tables & Column Groups",
          description: "Structure complex datasets with accessible tables, captions, headers, and column scopes.",
          durationMinutes: 14,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "When to use tables (tabular data) and when not to (page layout)",
            "The role of <caption>, <thead>, <tbody>, and <tfoot>",
            "Scope attributes (scope='col', scope='row') for screen readers",
          ],
          introduction: `HTML tables are designed specifically to display multi-dimensional tabular data, such as financial reports, schedules, leaderboards, and data grids.`,
          whyItMatters: `Proper table markup with scope='col' allows screen readers to announce both the column header and row cell simultaneously as users navigate through cells.`,
          mainExample: {
            title: "Accessible Product Pricing Table",
            language: "html",
            code: `<table>\n  <caption>KWAS Academy Course Catalog Summary</caption>\n  <thead>\n    <tr>\n      <th scope="col">Course Title</th>\n      <th scope="col">Level</th>\n      <th scope="col">Hours</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th scope="row">HTML5 Architecture</th>\n      <td>Beginner</td>\n      <td>18h</td>\n    </tr>\n  </tbody>\n</table>`,
            executable: true,
            explanation: ["scope='col' identifies column headers.", "caption provides an accessible title."],
          },
          detailedExplanation: ["Never use tables for page layout; use CSS Flexbox or Grid instead."],
          commonMistakes: [],
          bestPractices: ["Always include a <caption> to describe the table content."],
          summary: ["Tables present relational data clearly when paired with accessible header scopes."],
        },
      ],
    },
    {
      id: "mod-html-7",
      slug: "forms",
      title: "Module 7: Forms, Inputs & Constraint Validation",
      description: "Build robust, accessible user input forms with validation, labels, input types, and submission handlers.",
      lessons: [
        {
          id: "html-forms",
          slug: "html-forms",
          courseSlug: "html",
          moduleSlug: "forms",
          title: "HTML Forms & Constraint Validation",
          description: "Build accessible forms with labels, fieldsets, input types (text, email, password, number), and client constraint validation.",
          durationMinutes: 20,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Form attributes: action, method (GET vs POST), and enctype",
            "Binding <label for='...'> with input id for accessibility",
            "HTML5 validation: required, pattern, min, max, type='email'",
          ],
          introduction: `Forms are the foundation of interactive web applications. They allow users to enter data, submit searches, upload files, and authenticate.`,
          whyItMatters: `Proper form markup guarantees that mobile phones automatically show specialized keyboards (e.g. numeric keypad for phone numbers or @ keyboard for email).`,
          mainExample: {
            title: "Accessible Registration Form",
            language: "html",
            code: `<form action="/api/register" method="POST">\n  <div>\n    <label for="username">Username:</label>\n    <input type="text" id="username" name="username" required minlength="3">\n  </div>\n  <button type="submit">Create Account</button>\n</form>`,
            executable: true,
            explanation: ["<label for='...'> explicitly connects label text to the input id."],
          },
          detailedExplanation: ["HTML5 forms prevent submission and show native error bubbles if required constraints fail."],
          commonMistakes: [],
          bestPractices: ["Always include visible <label> tags paired to inputs with the for attribute."],
          summary: ["Forms capture user input securely with native constraint validation."],
        },
      ],
    },
    {
      id: "mod-html-8",
      slug: "accessibility",
      title: "Module 8: Web Accessibility (WCAG 2.2 / ARIA)",
      description: "Master ARIA roles, live regions, focus management, and accessibility testing.",
      lessons: [
        {
          id: "html-accessibility",
          slug: "web-accessibility-and-aria",
          courseSlug: "html",
          moduleSlug: "accessibility",
          title: "Web Accessibility (WCAG 2.2) & ARIA States",
          description: "Master accessible web applications: ARIA roles, aria-expanded, aria-live, tabindex, and focus management.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "The 4 WCAG Principles: Perceivable, Operable, Understandable, Robust (POUR)",
            "When and why to use ARIA roles and attributes",
            "Managing keyboard focus and tab navigation",
          ],
          introduction: `Web Accessibility (a11y) ensures that websites are usable by everyone, including people with visual, auditory, motor, or cognitive disabilities.`,
          whyItMatters: `Building accessible web apps is a legal requirement in many jurisdictions and universally improves UX for all users.`,
          mainExample: {
            title: "Accessible Collapsible Accordion",
            language: "html",
            code: `<button aria-expanded="false" aria-controls="panel-1" id="accordion-btn">\n  What is KWAS Academy?\n</button>\n<div id="panel-1" role="region" aria-labelledby="accordion-btn" hidden>\n  <p>KWAS Academy is a modern engineering platform.</p>\n</div>`,
            executable: true,
            explanation: ["aria-expanded communicates open/closed state to screen readers."],
          },
          detailedExplanation: ["First rule of ARIA: Do not use ARIA if a native HTML element already exists."],
          commonMistakes: [],
          bestPractices: ["Always use native HTML buttons and anchor links instead of clickable divs."],
          summary: ["Accessibility guarantees inclusive software experiences for all users."],
        },
      ],
    },
    {
      id: "mod-html-9",
      slug: "canvas-svg",
      title: "Module 9: HTML5 Canvas 2D & SVG Vector Graphics",
      description: "Render dynamic 2D graphics, games, charts, and scalable vector graphics.",
      lessons: [
        {
          id: "html-canvas",
          slug: "canvas-and-svg-graphics",
          courseSlug: "html",
          moduleSlug: "canvas-svg",
          title: "Canvas 2D API & Scalable Vector Graphics (SVG)",
          description: "Draw dynamic raster graphics via JavaScript Canvas 2D and render crisp scalable SVG vectors.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Canvas 2D context (ctx.fillRect, ctx.arc, requestAnimationFrame)",
            "Inline SVG elements (<circle>, <path>, <rect>) and CSS styling",
            "Choosing between Canvas (pixels/games) vs SVG (crisp resolution-independent icons/charts)",
          ],
          introduction: `HTML5 provides two distinct graphic systems: <canvas> for scriptable bitmap pixel drawing (charts, game rendering) and <svg> for scalable XML vector graphics.`,
          whyItMatters: `SVGs scale infinitely without losing quality on high-DPI Retina displays, making them ideal for logos, icons, and UI charts.`,
          mainExample: {
            title: "Inline SVG Vector Icon & Canvas 2D Box",
            language: "html",
            code: `<!-- Scalable Vector Graphic -->\n<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#2563eb" stroke-width="2">\n  <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>\n</svg>\n\n<!-- 2D Canvas Target -->\n<canvas id="myCanvas" width="300" height="150"></canvas>`,
            executable: true,
            explanation: ["SVG renders crisp vector lines.", "Canvas allows pixel-by-pixel rendering via JavaScript."],
          },
          detailedExplanation: ["Canvas is procedural (raster); SVG is declarative (DOM-based)."],
          commonMistakes: [],
          bestPractices: ["Use SVG for UI icons and data charts; use Canvas for particle systems and games."],
          summary: ["Canvas and SVG provide complete 2D visual rendering capabilities in the browser."],
        },
      ],
    },
    {
      id: "mod-html-10",
      slug: "storage-apis",
      title: "Module 10: Web Storage, Cookies & Client Persistence",
      description: "Persist client data with LocalStorage, SessionStorage, Cookies, and IndexedDB.",
      lessons: [
        {
          id: "html-storage",
          slug: "local-storage-and-indexeddb",
          courseSlug: "html",
          moduleSlug: "storage-apis",
          title: "Web Storage APIs (LocalStorage & IndexedDB)",
          description: "Store persistent user preferences with localStorage and structured relational datasets with IndexedDB.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "localStorage (persists across sessions) vs sessionStorage (tab lifetime)",
            "Synchronous key-value limits (5MB-10MB)",
            "IndexedDB for asynchronous, large-scale offline storage",
          ],
          introduction: `Web Storage APIs allow web applications to store up to several megabytes of key-value data directly in the user's browser, eliminating redundant network round-trips for user preferences.`,
          whyItMatters: `LocalStorage allows you to preserve user theme preferences (light/dark mode) and offline drafts instantly.`,
          mainExample: {
            title: "Theme Preference Persistence with LocalStorage",
            language: "javascript",
            code: `// Save preference\nlocalStorage.setItem("kwas_theme", "dark");\n\n// Retrieve preference\nconst savedTheme = localStorage.getItem("kwas_theme") || "light";\nconsole.log("Current Active Theme:", savedTheme);`,
            executable: true,
            explanation: ["localStorage data persists even when the browser is closed and reopened."],
          },
          detailedExplanation: ["Never store sensitive authentication passwords or credit cards in localStorage due to XSS risks."],
          commonMistakes: [],
          bestPractices: ["Always handle JSON.parse errors when reading complex objects from localStorage."],
          summary: ["Client storage enables offline support, caching, and personalized application states."],
        },
      ],
    },
    {
      id: "mod-html-11",
      slug: "seo-performance",
      title: "Module 11: SEO Metadata, OpenGraph & Performance Optimization",
      description: "Master meta tags, OpenGraph cards, Twitter cards, canonical links, and Core Web Vitals.",
      lessons: [
        {
          id: "html-seo",
          slug: "seo-metadata-and-opengraph",
          courseSlug: "html",
          moduleSlug: "seo-performance",
          title: "SEO Metadata, OpenGraph Cards & Web Vitals",
          description: "Optimize HTML for search engines and social sharing with meta tags, OpenGraph, Twitter cards, and JSON-LD schema.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Essential meta tags (description, canonical, robots)",
            "Open Graph protocol (og:title, og:image, og:description) for social media previews",
            "JSON-LD structured data schema for rich Google search snippets",
          ],
          introduction: `Search Engine Optimization (SEO) in HTML involves structuring metadata and document semantics so search engines like Google can crawl, understand, and rank your content effectively.`,
          whyItMatters: `Pages with proper OpenGraph metadata receive over 40% higher click-through rates when shared across Twitter, LinkedIn, and Discord.`,
          mainExample: {
            title: "Complete Production SEO Head Section",
            language: "html",
            code: `<head>\n  <meta charset="UTF-8">\n  <title>KWAS Academy — Learn Software Engineering</title>\n  <meta name="description" content="Master programming from beginner to advanced with interactive sandboxes.">\n  <link rel="canonical" href="https://kwasacademy.dev/learn">\n  \n  <!-- OpenGraph Social Cards -->\n  <meta property="og:title" content="KWAS Academy">\n  <meta property="og:description" content="Learn. Build. Master.">\n  <meta property="og:image" content="https://kwasacademy.dev/og-cover.png">\n  <meta property="og:type" content="website">\n</head>`,
            executable: true,
            explanation: [
              "Canonical link prevents duplicate content penalties.",
              "OpenGraph tags control link preview images on social apps.",
            ],
          },
          detailedExplanation: ["JSON-LD scripts embedded in the head provide structured schemas for Courses, Articles, and FAQs."],
          commonMistakes: [],
          bestPractices: ["Keep meta descriptions between 140 and 160 characters for maximum search engine snippet visibility."],
          summary: ["Search engine visibility begins with clean, standards-compliant HTML head metadata."],
        },
      ],
    },
  ],
};
