import { Course } from "@/types";

export const javaCourse: Course = {
  id: "course-java",
  slug: "java",
  title: "Java 21 Enterprise Architecture & Spring Boot",
  tagline: "Object-oriented programming, JVM internals, multithreading, and Spring Boot microservices.",
  description: "Master Java 21+: Object-Oriented Programming (OOP), JVM architecture, memory management, garbage collection, Collections framework, Generics, Concurrency & Virtual Threads, Spring Boot microservices, and Maven.",
  category: "Programming Languages",
  level: "Intermediate",
  estimatedHours: 28,
  icon: "Code2",
  badgeColor: "red",
  prerequisites: ["Programming Fundamentals"],
  skillsGained: [
    "Java 21 Syntax, Records & Pattern Matching",
    "Object-Oriented Design & Design Patterns (Singleton, Factory)",
    "Collections Framework (ArrayList, HashMap, ConcurrentHashMap)",
    "JVM Memory & Garbage Collection Tuning",
    "Spring Boot Dependency Injection & REST Microservices",
  ],
  featured: false,
  modules: [
    {
      id: "mod-java-1",
      slug: "intro",
      title: "Module 1: Java Overview & JVM Architecture",
      description: "Bytecode compilation, JVM stack vs heap, and public static void main.",
      lessons: [
        {
          id: "java-intro",
          slug: "java-introduction",
          courseSlug: "java",
          moduleSlug: "intro",
          title: "Java Introduction & JVM Execution Lifecycle",
          description: "Understand the Java Virtual Machine (JVM), bytecode compilation, classes, and main method execution.",
          durationMinutes: 15,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How the JVM executes bytecode across platforms ('Write Once, Run Anywhere')",
            "Class structure and public static void main entry points",
            "Modern Java 21 Records for immutable data containers",
          ],
          introduction: `Java is an enterprise-grade, class-based, object-oriented programming language designed for reliability, portability, and concurrency.`,
          whyItMatters: `Java powers backend banking systems, Android apps, and big data platforms (Apache Spark, Kafka) worldwide.`,
          mainExample: {
            title: "Java 21 Record & Main Application",
            language: "java",
            code: `public record Student(String id, String name, int score) {\n    public boolean isPassing() {\n        return score >= 70;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Student alex = new Student("usr_1", "Alex Dev", 94);\n        System.out.println(alex.name() + " passing: " + alex.isPassing());\n    }\n}`,
            executable: true,
            explanation: ["Record automatically generates constructor, getters, equals, and toString."],
          },
          detailedExplanation: ["JVM memory is split into Stack (method calls) and Heap (dynamic objects)."],
          commonMistakes: [],
          bestPractices: ["Use Records for immutable data transfer objects (DTOs)."],
          summary: ["Java provides rock-solid type safety, rich concurrency, and enterprise scalability."],
        },
      ],
    },
    {
      id: "mod-java-2",
      slug: "types-variables",
      title: "Module 2: Data Types, Variables & Operators",
      description: "Primitive types (byte, int, long, double), wrapper classes, and BigDecimal for financial calculations.",
      lessons: [
        {
          id: "java-types",
          slug: "primitive-types-and-bigdecimal",
          courseSlug: "java",
          moduleSlug: "types-variables",
          title: "Primitives, Wrapper Classes & BigDecimal",
          description: "Master Java primitive types, autoboxing, and avoid floating point rounding errors with BigDecimal.",
          durationMinutes: 14,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "8 Primitive types in Java and memory sizes",
            "Autoboxing and unboxing between int and Integer",
            "Why double/float must never be used for money (use BigDecimal)",
          ],
          introduction: `Java has 8 primitive data types (byte, short, int, long, float, double, boolean, char) stored directly on the stack for high speed.`,
          whyItMatters: `Using double for monetary calculations produces rounding errors (0.1 + 0.2 = 0.30000000000000004). BigDecimal guarantees exact decimal precision.`,
          mainExample: {
            title: "Exact Financial Math with BigDecimal",
            language: "java",
            code: `import java.math.BigDecimal;\n\npublic class FinancialApp {\n    public static void main(String[] args) {\n        BigDecimal price = new BigDecimal("19.99");\n        BigDecimal tax = new BigDecimal("0.08");\n        BigDecimal total = price.add(price.multiply(tax));\n        System.out.println("Exact Total: $" + total.setScale(2, BigDecimal.ROUND_HALF_UP));\n    }\n}`,
            executable: false,
            explanation: ["BigDecimal avoids binary floating point rounding inaccuracies."],
          },
          detailedExplanation: ["Wrapper classes (Integer, Double) allow primitives to be used in generic collections like List<Integer>."],
          commonMistakes: [],
          bestPractices: ["Always instantiate BigDecimal using string constructors (new BigDecimal('19.99'))."],
          summary: ["Precise data types prevent subtle calculation bugs in financial software."],
        },
      ],
    },
    {
      id: "mod-java-3",
      slug: "control-flow",
      title: "Module 3: Control Structures & Flow",
      description: "if/else, switch expressions (Java 14+), for/while loops, and enhanced for-each.",
      lessons: [
        {
          id: "java-control",
          slug: "switch-expressions-and-loops",
          courseSlug: "java",
          moduleSlug: "control-flow",
          title: "Enhanced Switch Expressions & Iteration",
          description: "Write arrow switch expressions with pattern matching and iterate collections with enhanced for-each.",
          durationMinutes: 14,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Modern switch expressions returning values directly (case 'A' -> ...)",
            "Enhanced for-each loops over Iterables",
            "Pattern matching in switch statements",
          ],
          introduction: `Modern Java switch expressions eliminate cumbersome break statements and can return values directly as expressions.`,
          whyItMatters: `Arrow switch syntax eliminates accidental fall-through bugs where forgetting a 'break' corrupts program logic.`,
          mainExample: {
            title: "Switch Expression with Arrow Syntax",
            language: "java",
            code: `public class StatusChecker {\n    public static String getStatusDescription(int code) {\n        return switch (code) {\n            case 200 -> "OK (Success)";\n            case 404 -> "Not Found";\n            case 500 -> "Internal Server Error";\n            default  -> "Unknown Status Code";\n        };\n    }\n}`,
            executable: false,
            explanation: ["Switch expression returns value directly without break statements."],
          },
          detailedExplanation: ["Switch expressions must be exhaustive, ensuring every possible input is handled."],
          commonMistakes: [],
          bestPractices: ["Use switch expressions instead of long chains of if-else-if statements."],
          summary: ["Modern control flow in Java is concise, safe, and expressive."],
        },
      ],
    },
    {
      id: "mod-java-4",
      slug: "oop-classes",
      title: "Module 4: Object-Oriented Programming (Classes & Objects)",
      description: "Constructors, getters/setters, encapsulation, static members, and packages.",
      lessons: [
        {
          id: "java-oop-core",
          slug: "classes-constructors-and-encapsulation",
          courseSlug: "java",
          moduleSlug: "oop-classes",
          title: "Classes, Constructors & Encapsulation",
          description: "Design object-oriented classes with private fields, public getters/setters, and overloaded constructors.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Encapsulation: hiding internal state behind accessors",
            "Constructor overloading and the 'this' keyword",
            "Static class members vs instance variables",
          ],
          introduction: `Object-Oriented Programming (OOP) organizes software design around data objects rather than functions and logic.`,
          whyItMatters: `Encapsulation protects class invariants by validating mutations inside setter methods before assignment.`,
          mainExample: {
            title: "Encapsulated Account Class",
            language: "java",
            code: `public class BankAccount {\n    private final String accountNumber;\n    private double balance;\n\n    public BankAccount(String accNum, double initial) {\n        this.accountNumber = accNum;\n        this.balance = Math.max(0, initial);\n    }\n\n    public void deposit(double amount) {\n        if (amount > 0) this.balance += amount;\n    }\n\n    public double getBalance() { return this.balance; }\n}`,
            executable: false,
            explanation: ["private fields cannot be mutated directly by external classes."],
          },
          detailedExplanation: ["static fields belong to the class itself, shared across all instantiated objects."],
          commonMistakes: [],
          bestPractices: ["Always make fields private final whenever possible."],
          summary: ["Encapsulation and constructors form the foundation of robust Java design."],
        },
      ],
    },
    {
      id: "mod-java-5",
      slug: "inheritance",
      title: "Module 5: Inheritance, Polymorphism & Abstract Classes",
      description: "Extending classes (extends), super(), method overriding (@Override), and abstract classes.",
      lessons: [
        {
          id: "java-inheritance",
          slug: "inheritance-and-polymorphism",
          courseSlug: "java",
          moduleSlug: "inheritance",
          title: "Inheritance, Dynamic Polymorphism & @Override",
          description: "Extend parent classes, override methods dynamically, and define abstract templates.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Extending classes with the 'extends' keyword",
            "Runtime dynamic method dispatch (polymorphism)",
            "Abstract classes that cannot be directly instantiated",
          ],
          introduction: `Inheritance allows child classes to inherit attributes and methods from a parent class, promoting code reuse. Polymorphism allows subclasses to provide customized method implementations.`,
          whyItMatters: `Polymorphism lets you write code that operates on a generic PaymentMethod base class without caring whether it is CreditCard or PayPal.`,
          mainExample: {
            title: "Polymorphic Payment Processing",
            language: "java",
            code: `public abstract class PaymentMethod {\n    public abstract void processPayment(double amount);\n}\n\npublic class CreditCardPayment extends PaymentMethod {\n    @Override\n    public void processPayment(double amount) {\n        System.out.println("Processing credit card charge: $" + amount);\n    }\n}`,
            executable: false,
            explanation: ["@Override verifies at compile time that a parent method is actually being overridden."],
          },
          detailedExplanation: ["Java supports single inheritance for classes (a class can only extend one parent class)."],
          commonMistakes: [],
          bestPractices: ["Prefer composition over inheritance for sharing code between unrelated classes."],
          summary: ["Polymorphism enables flexible, extensible object-oriented architectures."],
        },
      ],
    },
    {
      id: "mod-java-6",
      slug: "records-sealed",
      title: "Module 6: Interfaces, Records & Sealed Classes",
      description: "Interface contracts, default methods, Java 21 Records, and sealed class hierarchies.",
      lessons: [
        {
          id: "java-sealed-records",
          slug: "interfaces-records-and-sealed-classes",
          courseSlug: "java",
          moduleSlug: "records-sealed",
          title: "Interfaces, Default Methods & Sealed Classes",
          description: "Implement multiple interfaces, declare immutable Records, and restrict subclassing with 'sealed'.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Multiple interface implementation (implements A, B)",
            "Default method implementations in interfaces",
            "Sealed classes (sealed class Shape permits Circle, Square) for exhaustive pattern matching",
          ],
          introduction: `Interfaces define behavioral contracts. Sealed classes allow authors to explicitly declare which classes are permitted to extend them, enabling compiler-enforced exhaustiveness.`,
          whyItMatters: `Sealed classes prevent third-party code from extending internal domain models in unexpected ways.`,
          mainExample: {
            title: "Sealed Class Hierarchy",
            language: "java",
            code: `public sealed interface Result permits Success, Failure {}\n\npublic record Success(String data) implements Result {}\npublic record Failure(String error) implements Result {}\n\n// Pattern matching in Java 21\n// switch (result) { case Success s -> ... case Failure f -> ... }`,
            executable: false,
            explanation: ["The compiler knows Result can ONLY be Success or Failure, enabling exhaustive switches."],
          },
          detailedExplanation: ["Interfaces can have static methods and private helper methods as well as default methods."],
          commonMistakes: [],
          bestPractices: ["Use sealed interfaces to model algebraic data types (ADTs) in Java."],
          summary: ["Interfaces and sealed classes provide total control over class contracts and hierarchies."],
        },
      ],
    },
    {
      id: "mod-java-7",
      slug: "collections",
      title: "Module 7: Java Collections Framework",
      description: "List (ArrayList, LinkedList), Set (HashSet, TreeSet), and Map (HashMap, ConcurrentHashMap).",
      lessons: [
        {
          id: "java-collections",
          slug: "lists-sets-and-hashmaps",
          courseSlug: "java",
          moduleSlug: "collections",
          title: "Collections Framework (ArrayList, HashSet, HashMap)",
          description: "Master high-performance data structures: dynamic arrays (ArrayList), O(1) sets (HashSet), and key-value maps (HashMap).",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Choosing between ArrayList (fast indexing) vs LinkedList",
            "HashSet mechanics (hashCode() and equals() contract)",
            "HashMap key-value storage and ConcurrentHashMap for multithreading",
          ],
          introduction: `The Java Collections Framework provides an architecture to store and manipulate a group of objects through unified interfaces (List, Set, Map).`,
          whyItMatters: `Overriding equals() without overriding hashCode() breaks HashMap lookups, causing objects to be lost in the map.`,
          mainExample: {
            title: "HashMap & ArrayList Operations",
            language: "java",
            code: `import java.util.*;\n\npublic class CollectionDemo {\n    public static void main(String[] args) {\n        Map<String, Integer> scores = new HashMap<>();\n        scores.put("Alex", 95);\n        scores.put("Sarah", 98);\n\n        System.out.println("Alex Score: " + scores.getOrDefault("Alex", 0));\n        System.out.println("Total Students: " + scores.size());\n    }\n}`,
            executable: true,
            explanation: ["HashMap computes the hash index of the string key for O(1) instant lookup."],
          },
          detailedExplanation: ["ConcurrentHashMap allows multiple threads to read and write concurrently without locking the entire map."],
          commonMistakes: [],
          bestPractices: ["Always override both hashCode() and equals() together on custom key classes."],
          summary: ["The Collections Framework provides high-performance data structures for enterprise software."],
        },
      ],
    },
    {
      id: "mod-java-8",
      slug: "generics",
      title: "Module 8: Generics & Type Constraints",
      description: "Generic classes <T>, bounded type parameters (<T extends Comparable>), and wildcards (? extends Number).",
      lessons: [
        {
          id: "java-generics",
          slug: "generics-and-wildcards",
          courseSlug: "java",
          moduleSlug: "generics",
          title: "Generics (<T>), Type Erasure & Wildcards (? extends)",
          description: "Write type-safe generic classes and use PECS (Producer Extends, Consumer Super) wildcard rules.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Generic classes, interfaces, and methods (<T>)",
            "Bounded type parameters (<T extends Comparable<T>>)",
            "The PECS rule: Producer Extends, Consumer Super (? extends T vs ? super T)",
          ],
          introduction: `Generics enable types (classes and interfaces) to be parameters when defining classes, interfaces, and methods.`,
          whyItMatters: `Generics catch type mismatch bugs at compile time rather than throwing ClassCastException at runtime in production.`,
          mainExample: {
            title: "Generic Box Container",
            language: "java",
            code: `public class Box<T> {\n    private T content;\n    public void set(T item) { this.content = item; }\n    public T get() { return this.content; }\n}\n\n// Box<String> stringBox = new Box<>();`,
            executable: false,
            explanation: ["Box<T> guarantees type safety for any contained object."],
          },
          detailedExplanation: ["Java uses Type Erasure: generic type metadata is verified at compile time and removed in bytecode for backward compatibility."],
          commonMistakes: [],
          bestPractices: ["Remember the PECS rule for generic collection arguments in utility libraries."],
          summary: ["Generics enable reusable, type-safe data structures across Java applications."],
        },
      ],
    },
    {
      id: "mod-java-9",
      slug: "streams",
      title: "Module 9: Streams API & Functional Programming",
      description: "Stream pipelines, map, filter, reduce, collect (Collectors.toList), and parallel streams.",
      lessons: [
        {
          id: "java-streams",
          slug: "streams-api-and-lambdas",
          courseSlug: "java",
          moduleSlug: "streams",
          title: "The Java Streams API & Lambda Expressions",
          description: "Process collections declaratively with filter(), map(), reduce(), and Collectors.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Stream pipeline phases: Source -> Intermediate Operations -> Terminal Operation",
            "Transforming data with .filter() and .map()",
            "Aggregating into collections with .collect(Collectors.toList())",
          ],
          introduction: `The Java Streams API (introduced in Java 8) allows developers to process sequences of elements in a functional, declarative style.`,
          whyItMatters: `Streams replace 15 lines of nested for-loops and if-conditions with 3 lines of readable, chainable transformations.`,
          mainExample: {
            title: "Stream Pipeline with Filter & Map",
            language: "java",
            code: `import java.util.*;\nimport java.util.stream.Collectors;\n\npublic class StreamDemo {\n    public static void main(String[] args) {\n        List<String> names = List.of("Alex", "Sarah", "Kenneth", "Elena", "Bob");\n        List<String> result = names.stream()\n            .filter(n -> n.length() > 4)\n            .map(String::toUpperCase)\n            .sorted()\n            .collect(Collectors.toList());\n        System.out.println("Filtered: " + result);\n    }\n}`,
            executable: true,
            explanation: ["Streams evaluate lazily: intermediate operations only execute when the terminal collect() runs."],
          },
          detailedExplanation: [".parallelStream() automatically splits work across multi-core CPU threads for large datasets."],
          commonMistakes: [],
          bestPractices: ["Do not mutate external state inside Stream lambda functions."],
          summary: ["The Streams API delivers elegant, functional collection processing in Java."],
        },
      ],
    },
    {
      id: "mod-java-10",
      slug: "concurrency",
      title: "Module 10: Concurrency, Threads & Virtual Threads (Project Loom)",
      description: "Thread synchronization, ExecutorService, CompletableFuture, and Java 21 Virtual Threads.",
      lessons: [
        {
          id: "java-virtual-threads",
          slug: "virtual-threads-and-concurrency",
          courseSlug: "java",
          moduleSlug: "concurrency",
          title: "Java 21 Virtual Threads & Concurrency",
          description: "Scale to 1,000,000 concurrent tasks effortlessly using lightweight Java 21 Virtual Threads (Project Loom).",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "OS Platform Threads (1MB memory) vs Virtual Threads (KB memory)",
            "Spawning virtual threads with Executors.newVirtualThreadPerTaskExecutor()",
            "CompletableFuture for asynchronous pipeline composition",
          ],
          introduction: `Virtual Threads are lightweight threads that dramatically reduce the effort of writing, maintaining, and observing high-throughput concurrent applications.`,
          whyItMatters: `Traditional OS threads hit memory limits at ~5,000 threads. Virtual threads allow a single JVM to easily manage 1,000,000 concurrent HTTP connections!`,
          mainExample: {
            title: "Spawning 10,000 Virtual Threads",
            language: "java",
            code: `import java.util.concurrent.Executors;\n\npublic class VirtualThreadDemo {\n    public static void main(String[] args) {\n        try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {\n            for (int i = 1; i <= 5; i++) {\n                final int id = i;\n                executor.submit(() -> {\n                    System.out.println("Virtual Thread Task #" + id + " running.");\n                });\n            }\n        }\n    }\n}`,
            executable: true,
            explanation: ["Virtual threads unmount from carrier OS threads during blocking I/O automatically."],
          },
          detailedExplanation: ["Virtual threads eliminate the need for complex reactive programming (like WebFlux/RxJava) for high-throughput I/O."],
          commonMistakes: [],
          bestPractices: ["Never pool virtual threads; spawn a new virtual thread per task."],
          summary: ["Virtual Threads bring effortless, high-throughput concurrency to modern Java."],
        },
      ],
    },
    {
      id: "mod-java-11",
      slug: "spring-boot",
      title: "Module 11: Spring Boot Microservices Architecture",
      description: "Spring Boot 3, Dependency Injection, Spring Data JPA, and secure REST APIs.",
      lessons: [
        {
          id: "java-spring",
          slug: "spring-boot-and-microservices",
          courseSlug: "java",
          moduleSlug: "spring-boot",
          title: "Spring Boot 3 REST Microservices & Dependency Injection",
          description: "Build enterprise microservices with Spring Boot, @RestController, @Service, and Spring Data JPA repositories.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Spring Inversion of Control (IoC) and @Autowired Dependency Injection",
            "Building REST endpoints with @RestController and @GetMapping",
            "Database persistence with Spring Data JPA interfaces",
          ],
          introduction: `Spring Boot is the premier Java enterprise framework for building production-grade, standalone microservices and web APIs.`,
          whyItMatters: `Spring Boot powers the core backend transaction engines of financial institutions, Fortune 500 enterprises, and e-commerce platforms.`,
          mainExample: {
            title: "Spring Boot REST Controller",
            language: "java",
            code: `@RestController\n@RequestMapping("/api/courses")\npublic class CourseController {\n    @GetMapping\n    public List<String> listCourses() {\n        return List.of("HTML5", "TypeScript", "Java 21");\n    }\n}`,
            executable: false,
            explanation: ["Spring Boot automatically serializes Java objects to JSON HTTP responses."],
          },
          detailedExplanation: ["Spring Data JPA generates SQL queries automatically based on repository method names (findByEmail)."],
          commonMistakes: [],
          bestPractices: ["Use constructor injection instead of field @Autowired for better testability."],
          summary: ["Spring Boot delivers enterprise-grade scalability, security, and cloud deployment."],
        },
      ],
    },
  ],
};
