import { Course } from "@/types";

export const javascriptCourse: Course = {
  id: "course-javascript",
  slug: "javascript",
  title: "JavaScript Complete Professional Reference",
  tagline: "Master modern ECMAScript from core syntax to closures, asynchronous programming, event loop, and web APIs.",
  description: "The complete JavaScript curriculum: variables, data types, scoping, functions, array methods, DOM manipulation, promises, async/await, closures, prototypes, event loop mechanics, and modular software architecture.",
  category: "Programming Languages",
  level: "Beginner",
  estimatedHours: 30,
  icon: "Code2",
  badgeColor: "amber",
  prerequisites: ["HTML & CSS Fundamentals"],
  skillsGained: [
    "Modern ES6+ Syntax (let/const, arrow functions, destructuring)",
    "Asynchronous JS (Promises, async/await, Fetch API)",
    "DOM & Event-Driven Architecture",
    "Closures & Scope Chain Execution Contexts",
    "The Event Loop, Microtasks & Macrotasks",
    "Object-Oriented & Functional JavaScript Patterns",
  ],
  featured: true,
  modules: [
    {
      id: "mod-js-1",
      slug: "intro",
      title: "Module 1: JavaScript Engine & V8 Architecture",
      description: "How V8 parses, compiles (JIT), and executes JavaScript code.",
      lessons: [
        {
          id: "js-intro",
          slug: "js-introduction",
          courseSlug: "javascript",
          moduleSlug: "intro",
          title: "JavaScript Introduction & Execution Engine",
          description: "Understand how JavaScript runs inside the browser and Node.js runtime engines.",
          durationMinutes: 12,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "How the V8 JavaScript engine parses and compiles code",
            "Variable declarations: const vs let vs var",
            "Template literals and string interpolation",
          ],
          introduction: `JavaScript is the ubiquitous programming language of the web platform. It executes inside web browsers, server environments, and mobile runtimes.`,
          whyItMatters: `JavaScript transforms static documents into living, interactive applications.`,
          mainExample: {
            title: "Modern JavaScript Script",
            language: "javascript",
            code: `const platform = "KWAS Academy";\nconst studentCount = 12000;\n\nfunction getWelcomeMessage(user) {\n  return \`Welcome to \${platform}, \${user}! Join \${studentCount.toLocaleString()} engineers.\`;\n}\n\nconsole.log(getWelcomeMessage("Alex Developer"));`,
            executable: true,
            explanation: ["const declares block-scoped variables.", "Template literals interpolate values."],
          },
          detailedExplanation: ["JavaScript engines use JIT compilation to optimize hot code paths during runtime."],
          commonMistakes: [],
          bestPractices: ["Use const by default for all variable declarations."],
          summary: ["JavaScript powers the interactive computing layer of the web."],
        },
      ],
    },
    {
      id: "mod-js-2",
      slug: "variables-types",
      title: "Module 2: Variables, Data Types & Immutability",
      description: "Primitives, heap references, memory pointers, type coercion, and immutability.",
      lessons: [
        {
          id: "js-variables",
          slug: "js-variables",
          courseSlug: "javascript",
          moduleSlug: "variables-types",
          title: "Primitives vs References & Immutability",
          description: "Deep dive into 7 primitive types, reference pointers, memory management, and immutability.",
          durationMinutes: 18,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "The 7 JavaScript primitives",
            "How reference types (objects, arrays) point to heap memory",
            "Cloning objects immutably using spread and structuredClone()",
          ],
          introduction: `Data in JavaScript is divided into stack-stored Primitives and heap-stored Reference Types.`,
          whyItMatters: `Accidentally mutating a reference object in React or Vue state causes bugs where UI fails to re-render.`,
          mainExample: {
            title: "Immutable Array & Object Updates",
            language: "javascript",
            code: `const original = { user: "Alex", tasks: ["HTML", "CSS"] };\nconst updated = { ...original, tasks: [...original.tasks, "JS"] };\nconsole.log("Original tasks:", original.tasks.length);\nconsole.log("Updated tasks:", updated.tasks.length);`,
            executable: true,
            explanation: ["Spread operator creates shallow clones, preserving original immutability."],
          },
          detailedExplanation: ["Primitives are compared by value; reference types by memory address."],
          commonMistakes: [],
          bestPractices: ["Always use strict equality === instead of loose ==."],
          summary: ["Understanding memory references is essential for state-driven application development."],
        },
      ],
    },
    {
      id: "mod-js-3",
      slug: "control-flow",
      title: "Module 3: Operators, Conditionals & Control Flow",
      description: "Arithmetic, logical short-circuiting, ternary operator, switch, and loops.",
      lessons: [
        {
          id: "js-control",
          slug: "operators-and-control-flow",
          courseSlug: "javascript",
          moduleSlug: "control-flow",
          title: "Logical Short-Circuiting & Modern Control Flow",
          description: "Master ternary operators, nullish coalescing (??), optional chaining (?.), and modern loops.",
          durationMinutes: 15,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Short-circuit evaluation with && and ||",
            "Nullish coalescing (??) vs OR (||) fallback",
            "Safe property access with optional chaining (?.)",
          ],
          introduction: `Modern JavaScript provides expressive operators for safe property navigation and default fallback handling.`,
          whyItMatters: `Optional chaining (?.) prevents fatal 'Cannot read properties of undefined' crashes when navigating nested API payloads.`,
          mainExample: {
            title: "Optional Chaining & Nullish Coalescing",
            language: "javascript",
            code: `const userResponse = { profile: { name: "Alex" } };\nconst city = userResponse.profile?.address?.city ?? "Remote / Unknown";\nconsole.log("City:", city);`,
            executable: true,
            explanation: ["Optional chaining prevents crashes on missing address object."],
          },
          detailedExplanation: ["?? only falls back for null or undefined, preserving valid values like 0 or false."],
          commonMistakes: [],
          bestPractices: ["Use ?? instead of || when default numeric 0 or boolean false values are valid."],
          summary: ["Modern operators streamline conditional logic and prevent null pointer crashes."],
        },
      ],
    },
    {
      id: "mod-js-4",
      slug: "functions-scope",
      title: "Module 4: Functions, Arrow Syntax & Scopes",
      description: "Function declarations, expressions, arrow functions, lexical this, and default parameters.",
      lessons: [
        {
          id: "js-functions",
          slug: "functions-and-arrow-syntax",
          courseSlug: "javascript",
          moduleSlug: "functions-scope",
          title: "Functions, Arrow Functions & Lexical 'this'",
          description: "Understand higher-order functions, arrow syntax, rest parameters, and lexical 'this' binding.",
          durationMinutes: 16,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Standard function declarations vs concise arrow functions",
            "How arrow functions inherit 'this' from surrounding lexical scope",
            "Rest parameters (...args) and default argument values",
          ],
          introduction: `Functions are first-class citizens in JavaScript: they can be assigned to variables, passed as arguments, and returned from other functions.`,
          whyItMatters: `Arrow functions simplify functional programming methods like .map(), .filter(), and .reduce().`,
          mainExample: {
            title: "Higher-Order Function with Arrow Syntax",
            language: "javascript",
            code: `const calculateTotal = (taxRate = 0.08, ...prices) => {\n  const subtotal = prices.reduce((acc, p) => acc + p, 0);\n  return subtotal * (1 + taxRate);\n};\n\nconsole.log("Total: $" + calculateTotal(0.08, 100, 50, 25).toFixed(2));`,
            executable: true,
            explanation: ["Rest parameters (...prices) gather arguments into an array."],
          },
          detailedExplanation: ["Arrow functions do not have their own 'this', 'arguments', or 'prototype' bindings."],
          commonMistakes: [],
          bestPractices: ["Use arrow functions for callbacks and pure utility helpers."],
          summary: ["First-class functions empower functional programming patterns in JavaScript."],
        },
      ],
    },
    {
      id: "mod-js-5",
      slug: "data-structures",
      title: "Module 5: Objects, Arrays & Modern ES6+ Methods",
      description: "Array iteration (map, filter, reduce, find), Sets, Maps, and object destructuring.",
      lessons: [
        {
          id: "js-arrays-objects",
          slug: "arrays-maps-and-sets",
          courseSlug: "javascript",
          moduleSlug: "data-structures",
          title: "Array Methods (map/filter/reduce), Maps & Sets",
          description: "Transform collections with map, filter, and reduce, and leverage high-performance Map and Set collections.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Data transformation pipelines with .map(), .filter(), and .reduce()",
            "Unique collections with Set for O(1) deduplication",
            "Key-value indexing with Map supporting non-string keys",
          ],
          introduction: `Modern JavaScript provides high-performance data structures: Arrays for ordered sequences, Sets for unique values, and Maps for arbitrary key-value mappings.`,
          whyItMatters: `Deduplicating an array with new Set(arr) runs in O(n) time compared to O(n²) nested loop searches.`,
          mainExample: {
            title: "Array Transformation & Set Deduplication",
            language: "javascript",
            code: `const rawTags = ["react", "nextjs", "react", "typescript", "nextjs"];\nconst uniqueTags = [...new Set(rawTags)];\nconsole.log("Unique Tags:", uniqueTags);\n\nconst scores = [85, 92, 78, 96];\nconst avg = scores.reduce((acc, s) => acc + s, 0) / scores.length;\nconsole.log("Average Score:", avg);`,
            executable: true,
            explanation: ["new Set() automatically removes duplicate values."],
          },
          detailedExplanation: ["Map and Set provide O(1) average time complexity for insertions and lookups."],
          commonMistakes: [],
          bestPractices: ["Use Map over plain objects when keys are dynamic or non-string types."],
          summary: ["Collections and functional methods enable concise, expressive data transformations."],
        },
      ],
    },
    {
      id: "mod-js-6",
      slug: "dom-events",
      title: "Module 6: DOM Manipulation & Event-Driven Programming",
      description: "querySelector, element creation, event bubbling, capturing, and delegation.",
      lessons: [
        {
          id: "js-dom",
          slug: "dom-manipulation-and-events",
          courseSlug: "javascript",
          moduleSlug: "dom-events",
          title: "DOM Traversal & Event Delegation Architecture",
          description: "Manipulate DOM nodes, listen for user interactions, and optimize event listeners with event delegation.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Traversing and mutating DOM nodes efficiently",
            "Event bubbling and capturing phases",
            "Event delegation to manage 1,000+ dynamic child elements with 1 listener",
          ],
          introduction: `The Document Object Model (DOM) is an object-oriented representation of the web page. JavaScript uses events to react to user clicks, keyboard strokes, and scroll interactions.`,
          whyItMatters: `Event delegation attaches a single listener to a parent element rather than attaching hundreds of listeners to individual children, saving significant memory.`,
          mainExample: {
            title: "Event Delegation on Dynamic List",
            language: "javascript",
            code: `// Single listener on parent\ndocument.getElementById("todo-list")?.addEventListener("click", (e) => {\n  const target = e.target;\n  if (target.matches("button.delete-btn")) {\n    target.closest("li")?.remove();\n    console.log("Task deleted.");\n  }\n});`,
            executable: false,
            explanation: ["Event bubbles up from button to parent ul, triggering the delegated handler."],
          },
          detailedExplanation: ["Event delegation works automatically for newly inserted dynamic elements."],
          commonMistakes: [],
          bestPractices: ["Always prefer addEventListener over inline onclick attributes."],
          summary: ["Event delegation provides scalable, high-performance DOM event handling."],
        },
      ],
    },
    {
      id: "mod-js-7",
      slug: "async-js",
      title: "Module 7: Asynchronous JavaScript, Promises & Async/Await",
      description: "The Event Loop, Microtasks, Promises, and async/await error handling.",
      lessons: [
        {
          id: "js-async-await",
          slug: "async-await-and-promises",
          courseSlug: "javascript",
          moduleSlug: "async-js",
          title: "Promises, Async/Await & Error Handling",
          description: "Understand asynchronous programming, Promise states (pending, fulfilled, rejected), and clean async/await try/catch patterns.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How asynchronous operations avoid freezing the main browser thread",
            "Promise chaining vs modern async/await syntax",
            "Robust error handling with try/catch blocks",
          ],
          introduction: `JavaScript is single-threaded. To perform time-consuming tasks like network requests without freezing the UI, JavaScript relies on asynchronous Promises.`,
          whyItMatters: `Async/await is the industry standard for communicating with backend APIs and databases.`,
          mainExample: {
            title: "Async API Request with try/catch",
            language: "javascript",
            code: `async function fetchUserProfile(userId) {\n  try {\n    console.log(\`Fetching profile for user \${userId}...\`);\n    const mockUser = { id: userId, name: "Alex Dev" };\n    return mockUser;\n  } catch (error) {\n    console.error("Network request failed:", error.message);\n  }\n}`,
            executable: true,
            explanation: ["await pauses execution of the async function until the promise settles."],
          },
          detailedExplanation: ["Promises exist in 1 of 3 states: Pending, Fulfilled, or Rejected."],
          commonMistakes: [],
          bestPractices: ["Always wrap await calls in try/catch blocks to handle network failures."],
          summary: ["async/await provides clean, readable asynchronous JavaScript code."],
        },
      ],
    },
    {
      id: "mod-js-8",
      slug: "closures",
      title: "Module 8: Closures, Lexical Scope & Private Variables",
      description: "Execution contexts, call stack, closures, and data encapsulation.",
      lessons: [
        {
          id: "js-closures",
          slug: "closures-and-scope",
          courseSlug: "javascript",
          moduleSlug: "closures",
          title: "Closures, Lexical Scope & Private Variables",
          description: "Master lexical scope, closure mechanics, function factories, and encapsulating private state.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "What a closure is and how it preserves its lexical scope chain",
            "Creating encapsulated private state without classes",
            "Memory lifecycle and avoiding closure memory leaks",
          ],
          introduction: `A closure is the combination of a function bundled together with references to its surrounding state.`,
          whyItMatters: `Closures power React hooks (like useState), currying, and private state across modern JavaScript architectures.`,
          mainExample: {
            title: "Private Counter with Closure",
            language: "javascript",
            code: `function createAccount(initialBalance) {\n  let balance = initialBalance; // Private encapsulated variable\n  return {\n    deposit(amount) {\n      balance += amount;\n      return \`Balance: $\${balance}\`;\n    },\n    getBalance() { return balance; }\n  };\n}\n\nconst acc = createAccount(100);\nconsole.log(acc.deposit(50)); // $150\nconsole.log(acc.balance); // undefined (Private)`,
            executable: true,
            explanation: ["balance is encapsulated securely in the closure."],
          },
          detailedExplanation: ["Inner functions retain references to outer scope variables even after the outer function finishes."],
          commonMistakes: [],
          bestPractices: ["Use closures for private state encapsulation and memoization."],
          summary: ["Closures enable powerful state encapsulation in JavaScript."],
        },
      ],
    },
    {
      id: "mod-js-9",
      slug: "oop-prototypes",
      title: "Module 9: Object-Oriented JS, Prototypes & Classes",
      description: "Prototype chain, ES6 class syntax, inheritance, getters/setters, and static methods.",
      lessons: [
        {
          id: "js-classes",
          slug: "classes-and-prototypes",
          courseSlug: "javascript",
          moduleSlug: "oop-prototypes",
          title: "ES6 Classes, Inheritance & Prototype Chains",
          description: "Design modular object-oriented systems with ES6 classes, super constructors, and static methods.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How JavaScript's prototypal inheritance works under the hood",
            "Class syntax: constructor, methods, getters, and setters",
            "Extending base classes with extends and super()",
          ],
          introduction: `JavaScript classes provide clean syntactic sugar over prototype-based inheritance. Classes allow you to define structured blueprints for creating object instances.`,
          whyItMatters: `Classes are widely used in backend ORMs, game development, and enterprise data models.`,
          mainExample: {
            title: "Class Hierarchy with Inheritance",
            language: "javascript",
            code: `class User {\n  constructor(name, email) {\n    this.name = name;\n    this.email = email;\n  }\n  getInfo() {\n    return \`\${this.name} (\${this.email})\`;\n  }\n}\n\nclass AdminUser extends User {\n  constructor(name, email, permissions) {\n    super(name, email);\n    this.permissions = permissions;\n  }\n}\n\nconst admin = new AdminUser("Kenneth", "ken@kwas.dev", ["ALL"]);\nconsole.log(admin.getInfo());`,
            executable: true,
            explanation: ["super() calls the parent constructor, establishing inheritance."],
          },
          detailedExplanation: ["Every JavaScript object has an internal [[Prototype]] link to its parent prototype object."],
          commonMistakes: [],
          bestPractices: ["Use class syntax over manual Object.prototype mutation."],
          summary: ["Classes provide clean, structured blueprints for object-oriented systems."],
        },
      ],
    },
    {
      id: "mod-js-10",
      slug: "web-apis",
      title: "Module 10: Web APIs, Fetch & Browser Storage",
      description: "Fetch API, AbortController, URLSearchParams, IntersectionObserver, and Web Workers.",
      lessons: [
        {
          id: "js-fetch-apis",
          slug: "fetch-api-and-browser-features",
          courseSlug: "javascript",
          moduleSlug: "web-apis",
          title: "The Fetch API, AbortController & Web APIs",
          description: "Perform HTTP network requests, cancel requests with AbortController, and observe element visibility with IntersectionObserver.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Making GET/POST requests with fetch() and headers",
            "Canceling stale requests with AbortController",
            "IntersectionObserver for infinite scroll and lazy loading",
          ],
          introduction: `Browsers provide powerful Web APIs for networking, device sensor access, audio manipulation, and background multithreading.`,
          whyItMatters: `Using AbortController prevents race conditions in search input autocomplete where fast typers receive out-of-order responses.`,
          mainExample: {
            title: "Cancellable Fetch Request with AbortController",
            language: "javascript",
            code: `const controller = new AbortController();\n\nasync function searchData(query) {\n  try {\n    // Cancel previous pending request\n    controller.abort();\n    console.log("Searching for:", query);\n  } catch (err) {\n    console.log("Request aborted safely.");\n  }\n}\n\nsearchData("TypeScript");`,
            executable: true,
            explanation: ["AbortController cancels in-flight network requests cleanly."],
          },
          detailedExplanation: ["IntersectionObserver notifies your script when elements enter the screen without polling onScroll."],
          commonMistakes: [],
          bestPractices: ["Always check response.ok on fetch calls before parsing JSON."],
          summary: ["Web APIs expand JavaScript with high-performance browser platform capabilities."],
        },
      ],
    },
    {
      id: "mod-js-11",
      slug: "modules-performance",
      title: "Module 11: Modular JavaScript, Tooling & Performance",
      description: "ES Modules (import/export), tree-shaking, memory leak prevention, and performance profiling.",
      lessons: [
        {
          id: "js-modules",
          slug: "es-modules-and-performance",
          courseSlug: "javascript",
          moduleSlug: "modules-performance",
          title: "ES Modules & Memory Optimization",
          description: "Organize large software systems with ES Modules (import/export), avoid memory leaks, and profile execution performance.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Named exports vs default exports in ES Modules",
            "How bundlers (Webpack, Vite, Turbopack) perform tree-shaking to eliminate dead code",
            "Identifying and fixing memory leaks (dangling event listeners, detached DOM nodes)",
          ],
          introduction: `ES Modules (ESM) are the official standard module format in JavaScript. They allow codebases to be partitioned into independent, reusable files with explicit dependency trees.`,
          whyItMatters: `Static import/export syntax allows modern bundlers to remove unused functions (tree-shaking), reducing client bundle size by up to 70%.`,
          mainExample: {
            title: "ES Module Named Exports",
            language: "javascript",
            code: `// mathUtils.js\nexport const add = (a, b) => a + b;\nexport const multiply = (a, b) => a * b;\n\n// main.js\n// import { add } from './mathUtils.js';\nconsole.log("Modules enable isolated, reusable software packages.");`,
            executable: true,
            explanation: ["Named exports allow bundlers to tree-shake and include only imported functions."],
          },
          detailedExplanation: ["Always remove event listeners when components unmount to avoid detached DOM node memory leaks."],
          commonMistakes: [],
          bestPractices: ["Favor named exports over default exports for better refactoring tools and autocompletion."],
          summary: ["Modular architecture and memory hygiene ensure fast, maintainable applications."],
        },
      ],
    },
  ],
};
