import { Course } from "@/types";

export const nextjsCourse: Course = {
  id: "course-nextjs",
  slug: "nextjs",
  title: "Next.js Full-Stack App Router Architecture",
  tagline: "Master Server Components, Server Actions, dynamic routing, streaming SSR, and SEO.",
  description: "Build full-stack applications with Next.js App Router: React Server Components (RSC), Client Components, Server Actions, dynamic route segments, metadata SEO, caching layers, and Vercel cloud deployment.",
  category: "Frontend",
  level: "Advanced",
  estimatedHours: 26,
  icon: "Zap",
  badgeColor: "purple",
  prerequisites: ["React", "TypeScript"],
  skillsGained: [
    "App Router Architecture (layout.tsx, page.tsx, loading.tsx)",
    "React Server Components (RSC) vs Client Components ('use client')",
    "Server Actions for Mutations with Zero Client Bundles",
    "Incremental Static Regeneration (ISR) & Route Caching",
    "Dynamic OpenGraph & Metadata Generation",
  ],
  featured: true,
  modules: [
    {
      id: "mod-next-1",
      slug: "intro",
      title: "Module 1: Next.js Overview & App Router Architecture",
      description: "Understand the Next.js App Router architecture and server-first paradigm.",
      lessons: [
        {
          id: "nextjs-intro",
          slug: "nextjs-introduction",
          courseSlug: "nextjs",
          moduleSlug: "intro",
          title: "Next.js Introduction & React Server Components",
          description: "Discover why Next.js is the premier React full-stack framework and understand Server Components.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Server-side rendering vs static generation (SSG) vs streaming SSR",
            "The App Router folder hierarchy (layout, page, error, not-found)",
            "How React Server Components eliminate client JavaScript bundle size",
          ],
          introduction: `Next.js is a full-stack React framework that provides hybrid static and server rendering, automatic code splitting, optimized image loading, and backend Server Actions.`,
          whyItMatters: `Server Components query databases directly without exposing API controllers or secrets to the client.`,
          mainExample: {
            title: "Async React Server Component",
            language: "typescript",
            code: `export default async function CoursesPage() {\n  return (\n    <main className="p-8">\n      <h1 className="text-2xl font-bold">KWAS Full-Stack Academy</h1>\n    </main>\n  );\n}`,
            executable: true,
            explanation: ["Server Components can be async functions directly."],
          },
          detailedExplanation: ["Use 'use client' only when components require browser state or interactivity."],
          commonMistakes: [],
          bestPractices: ["Keep components as Server Components by default."],
          summary: ["Next.js bridges React UI with server computation seamlessly."],
        },
      ],
    },
    {
      id: "mod-next-2",
      slug: "routing-layouts",
      title: "Module 2: Routing, Layouts & Nested Route Segments",
      description: "Folder-based routing, dynamic segments [slug], catch-all [...slug], and nested layout persistence.",
      lessons: [
        {
          id: "next-routing",
          slug: "routing-and-nested-layouts",
          courseSlug: "nextjs",
          moduleSlug: "routing-layouts",
          title: "File-System Routing & Nested Layouts",
          description: "Master folder-based routing, route groups (group), parallel routes (@slot), and persistent layouts.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Folder hierarchy mapping to URL path segments",
            "Persistent layouts that do not re-render during page transitions",
            "Route groups (marketing) that organize folders without changing URLs",
          ],
          introduction: `Next.js uses a file-system based router where folders define routes. Special file conventions (layout.tsx, page.tsx, loading.tsx, not-found.tsx) control segment behavior.`,
          whyItMatters: `Nested layouts preserve UI state (like audio playback, video scroll, or form drafts) across route changes.`,
          mainExample: {
            title: "Nested Course Layout Component",
            language: "typescript",
            code: `// app/learn/[courseSlug]/layout.tsx\nexport default function CourseLayout({\n  children,\n  params,\n}: { children: React.ReactNode; params: { courseSlug: string } }) {\n  return (\n    <div className="flex">\n      <aside className="w-64">Sidebar: {params.courseSlug}</aside>\n      <main className="flex-1">{children}</main>\n    </div>\n  );\n}`,
            executable: false,
            explanation: ["Layout wraps all nested child pages inside [courseSlug] seamlessly."],
          },
          detailedExplanation: ["Catch-all routes [...slug] match arbitrary nested paths (/docs/a/b/c)."],
          commonMistakes: [],
          bestPractices: ["Use Route Groups (auth) to create distinct layouts for marketing vs dashboard."],
          summary: ["File-system routing makes web application architectures intuitive and structured."],
        },
      ],
    },
    {
      id: "mod-next-3",
      slug: "server-components",
      title: "Module 3: React Server Components (RSC) vs Client Components",
      description: "When to use 'use client', component boundaries, and serialization rules.",
      lessons: [
        {
          id: "next-rsc",
          slug: "rsc-vs-client-components",
          courseSlug: "nextjs",
          moduleSlug: "server-components",
          title: "Server vs Client Component Boundaries",
          description: "Understand the 'use client' directive, component composition, passing server props, and serialization.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Why Server Components cannot use useState, useEffect, or onClick",
            "Pushing 'use client' leaves to the edges of the component tree",
            "Passing Server Components as children to Client Components",
          ],
          introduction: `React Server Components (RSC) execute exclusively on the server and never ship JavaScript to the client browser. Client Components ('use client') hydrate in the browser to provide interactivity.`,
          whyItMatters: `Structuring 80%+ of your application as Server Components cuts user JavaScript bundle sizes dramatically, improving mobile Core Web Vitals.`,
          mainExample: {
            title: "Composing Server & Client Components",
            language: "typescript",
            code: `// Server Component (Default)\nimport InteractiveHeartButton from "./InteractiveHeartButton"; // Client Component\n\nexport default function BlogPost({ post }) {\n  return (\n    <article>\n      <h1>{post.title}</h1>\n      <p>{post.content}</p>\n      {/* Interactive client leaf */}\n      <InteractiveHeartButton postId={post.id} />\n    </article>\n  );\n}`,
            executable: false,
            explanation: ["Only the interactive button downloads client JavaScript."],
          },
          detailedExplanation: ["Props passed from Server Components to Client Components must be serializable (no functions)."],
          commonMistakes: [],
          bestPractices: ["Never put 'use client' at the top of a page.tsx unless strictly required."],
          summary: ["RSC allows full-stack applications to ship minimal JavaScript bundles to clients."],
        },
      ],
    },
    {
      id: "mod-next-4",
      slug: "data-fetching",
      title: "Module 4: Data Fetching, Caching & Revalidation",
      description: "fetch() caching, cache: 'no-store', revalidateTag(), and ISR.",
      lessons: [
        {
          id: "next-caching",
          slug: "caching-and-revalidation",
          courseSlug: "nextjs",
          moduleSlug: "data-fetching",
          title: "Incremental Static Regeneration (ISR) & Caching",
          description: "Master Next.js cache layers: Request Memoization, Data Cache, Full Route Cache, and on-demand revalidation.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Time-based revalidation (next: { revalidate: 3600 })",
            "On-demand cache purging with revalidateTag('courses')",
            "Dynamic rendering (export const dynamic = 'force-dynamic')",
          ],
          introduction: `Next.js provides a multi-layer caching system that combines the speed of static HTML with the freshness of real-time database updates.`,
          whyItMatters: `ISR allows a page with 1,000,000 views to be served from CDN cache in 10ms, while refreshing in the background when database content updates.`,
          mainExample: {
            title: "Data Fetching with ISR Caching",
            language: "typescript",
            code: `export async function getCourses() {\n  const res = await fetch("https://api.kwas.dev/courses", {\n    next: { revalidate: 300, tags: ["courses"] }, // Revalidate every 5 minutes\n  });\n  return res.json();\n}`,
            executable: false,
            explanation: ["next.tags allows targeted cache invalidation when content changes."],
          },
          detailedExplanation: ["revalidatePath('/courses') purges the Full Route Cache on the server instantly."],
          commonMistakes: [],
          bestPractices: ["Tag your fetch requests for granular on-demand cache invalidation."],
          summary: ["Next.js caching delivers sub-millisecond global CDN speeds with dynamic data freshness."],
        },
      ],
    },
    {
      id: "mod-next-5",
      slug: "server-actions",
      title: "Module 5: Server Actions & Form Mutations",
      description: "Mutate backend database records directly from React forms with Server Actions.",
      lessons: [
        {
          id: "nextjs-server-actions",
          slug: "server-actions-and-mutations",
          courseSlug: "nextjs",
          moduleSlug: "server-actions",
          title: "Next.js Server Actions & Form Mutations",
          description: "Execute secure backend functions directly from client forms without dedicated API routes.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Defining Server Actions with 'use server'",
            "Form submission with FormData and useActionState",
            "Revalidating cached paths with revalidatePath()",
          ],
          introduction: `Server Actions are asynchronous functions executed on the server that can be called directly from forms or buttons.`,
          whyItMatters: `Server Actions eliminate boilerplate REST API controller endpoints for CRUD operations.`,
          mainExample: {
            title: "Server Action Form Mutation",
            language: "typescript",
            code: `"use server";\nimport { revalidatePath } from "next/cache";\n\nexport async function createComment(formData: FormData) {\n  const text = formData.get("text") as string;\n  console.log("Saving comment to database:", text);\n  revalidatePath("/courses");\n}`,
            executable: false,
            explanation: ["'use server' ensures function executes strictly on the backend."],
          },
          detailedExplanation: ["Server Actions work with standard HTML forms even before client JavaScript hydrates."],
          commonMistakes: [],
          bestPractices: ["Always validate form data with Zod schemas inside Server Actions."],
          summary: ["Server Actions streamline full-stack data mutation in Next.js."],
        },
      ],
    },
    {
      id: "mod-next-6",
      slug: "route-handlers",
      title: "Module 6: Route Handlers & REST API Endpoints",
      description: "Building public REST APIs with route.ts, GET/POST/PUT/DELETE, and NextResponse.",
      lessons: [
        {
          id: "next-routes",
          slug: "route-handlers-and-rest",
          courseSlug: "nextjs",
          moduleSlug: "route-handlers",
          title: "Building REST Endpoints with route.ts",
          description: "Implement custom HTTP endpoints using Web standard Request and Response objects.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Exporting HTTP method handlers: GET, POST, PUT, PATCH, DELETE",
            "Extracting query parameters and JSON request bodies",
            "Returning structured JSON with NextResponse.json()",
          ],
          introduction: `Route Handlers allow you to create custom request handlers for a given route using the Web Request and Response APIs.`,
          whyItMatters: `Route Handlers are used for external webhooks (Stripe, GitHub), third-party REST APIs, and mobile app integrations.`,
          mainExample: {
            title: "GET & POST Route Handler",
            language: "typescript",
            code: `// app/api/courses/route.ts\nimport { NextResponse } from "next/server";\n\nexport async function GET(request: Request) {\n  return NextResponse.json({ status: "success", timestamp: new Date().toISOString() });\n}\n\nexport async function POST(request: Request) {\n  const body = await request.json();\n  return NextResponse.json({ message: "Course created", data: body }, { status: 201 });\n}`,
            executable: false,
            explanation: ["NextResponse returns standard HTTP response headers and status codes."],
          },
          detailedExplanation: ["Route handlers are evaluated dynamically if they read request headers or searchParams."],
          commonMistakes: [],
          bestPractices: ["Use Server Actions for internal UI mutations and Route Handlers for external webhooks."],
          summary: ["Route Handlers provide full-featured REST API engineering inside Next.js."],
        },
      ],
    },
    {
      id: "mod-next-7",
      slug: "streaming-suspense",
      title: "Module 7: Streaming SSR with Suspense & loading.tsx",
      description: "Instant loading skeletons, React Suspense boundaries, and HTTP streaming chunks.",
      lessons: [
        {
          id: "next-streaming",
          slug: "streaming-and-suspense",
          courseSlug: "nextjs",
          moduleSlug: "streaming-suspense",
          title: "Streaming SSR & Suspense Boundaries",
          description: "Deliver instant TTFB with loading.tsx skeletons and stream slow database chunks progressively.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "How HTTP streaming delivers early page shells instantly to the browser",
            "Automatic loading skeletons with loading.tsx",
            "Granular async component wrapping with <Suspense fallback={<Skeleton />}>",
          ],
          introduction: `Streaming allows you to break down the page's HTML into chunks and progressively stream those chunks from the server to the client.`,
          whyItMatters: `Fast parts of the page render in 5ms while slow database widgets stream in progressively without blocking the whole page.`,
          mainExample: {
            title: "Suspense Streamed Component",
            language: "typescript",
            code: `import { Suspense } from "react";\n\nexport default function Dashboard() {\n  return (\n    <div>\n      <h1>Instant Navigation Shell</h1>\n      <Suspense fallback={<div>Loading Analytics Stream...</div>}>\n        <SlowDatabaseFeed />\n      </Suspense>\n    </div>\n  );\n}`,
            executable: false,
            explanation: ["The outer shell renders instantly while SlowDatabaseFeed streams in when resolved."],
          },
          detailedExplanation: ["loading.tsx automatically wraps the corresponding page.tsx in a root Suspense boundary."],
          commonMistakes: [],
          bestPractices: ["Wrap only the slow data-heavy components in Suspense boundaries."],
          summary: ["Streaming SSR eliminates blank loading screens and maximizes perceived speed."],
        },
      ],
    },
    {
      id: "mod-next-8",
      slug: "optimization",
      title: "Module 8: Optimizing Images, Fonts & Scripts",
      description: "next/image, next/font, and next/script for 100/100 Core Web Vitals.",
      lessons: [
        {
          id: "next-opt",
          slug: "image-font-and-script-optimization",
          courseSlug: "nextjs",
          moduleSlug: "optimization",
          title: "Core Web Vitals Optimization (next/image, next/font)",
          description: "Achieve 100/100 Google Lighthouse scores using Next.js automatic image optimization and self-hosted fonts.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Automatic AVIF/WebP image conversion and responsive sizing with <Image />",
            "Zero layout shift (CLS) self-hosted fonts with next/font/google",
            "Third-party script loading strategies with next/script",
          ],
          introduction: `Next.js includes built-in components that automatically optimize media assets, fonts, and scripts to pass Google Core Web Vitals.`,
          whyItMatters: `next/image serves appropriately sized images for each user device, saving over 80% bandwidth on mobile.`,
          mainExample: {
            title: "Optimized Image Component",
            language: "typescript",
            code: `import Image from "next/image";\n\nexport function HeroBanner() {\n  return (\n    <Image\n      src="/hero.png"\n      alt="KWAS Academy Cloud Platform"\n      width={1200}\n      height={630}\n      priority // Preloads for Largest Contentful Paint (LCP)\n    />\n  );\n}`,
            executable: false,
            explanation: ["priority preloads hero images to maximize LCP performance."],
          },
          detailedExplanation: ["next/font automatically downloads and self-hosts Google Fonts at build time with zero external network requests."],
          commonMistakes: [],
          bestPractices: ["Always add 'priority' to above-the-fold hero images."],
          summary: ["Next.js optimizations automate peak performance and Core Web Vitals compliance."],
        },
      ],
    },
    {
      id: "mod-next-9",
      slug: "seo-metadata",
      title: "Module 9: Metadata, OpenGraph & Dynamic SEO",
      description: "Static metadata, generateMetadata(), sitemap.ts, and robots.ts generation.",
      lessons: [
        {
          id: "next-seo",
          slug: "dynamic-metadata-and-sitemaps",
          courseSlug: "nextjs",
          moduleSlug: "seo-metadata",
          title: "Dynamic Metadata & Dynamic Sitemaps (sitemap.ts)",
          description: "Generate dynamic SEO titles, descriptions, OpenGraph social cards, and XML sitemaps programmatically.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Exporting static metadata objects in layout.tsx and page.tsx",
            "Generating dynamic metadata based on URL parameters with generateMetadata()",
            "Creating programmatic sitemap.ts and robots.ts for search indexing",
          ],
          introduction: `Next.js App Router features a unified Metadata API that replaces legacy Head tags with type-safe metadata definitions.`,
          whyItMatters: `generateMetadata allows each course and lesson page to dynamically render customized titles and social share cards.`,
          mainExample: {
            title: "Dynamic generateMetadata API",
            language: "typescript",
            code: `export async function generateMetadata({ params }: { params: { slug: string } }) {\n  const course = await getCourse(params.slug);\n  return {\n    title: \`\${course.title} | KWAS Academy\`,\n    description: course.tagline,\n    openGraph: {\n      images: [\`https://kwas.dev/api/og?title=\${course.title}\`],\n    },\n  };\n}`,
            executable: false,
            explanation: ["Metadata resolves dynamically before the page HTML is sent to the client."],
          },
          detailedExplanation: ["sitemap.ts exports an array of URL entries that Next.js automatically formats into XML."],
          commonMistakes: [],
          bestPractices: ["Always define a metadataBase in root layout.tsx to resolve absolute OpenGraph image URLs."],
          summary: ["The Metadata API delivers full search engine optimization and social preview integration."],
        },
      ],
    },
    {
      id: "mod-next-10",
      slug: "middleware-auth",
      title: "Module 10: Edge Middleware & Authentication",
      description: "middleware.ts, request redirection, authentication cookies, and internationalization (i18n).",
      lessons: [
        {
          id: "next-middleware",
          slug: "edge-middleware-and-auth",
          courseSlug: "nextjs",
          moduleSlug: "middleware-auth",
          title: "Edge Middleware & Request Interception",
          description: "Intercept incoming requests at the Edge before route rendering to protect routes and verify auth cookies.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Creating root middleware.ts with config matchers",
            "Inspecting cookies and redirecting unauthorized users",
            "Rewriting URLs for multi-tenant and localization routing",
          ],
          introduction: `Middleware allows you to run code before a request is completed. Based on the incoming request, you can modify the response by rewriting, redirecting, or modifying headers.`,
          whyItMatters: `Middleware executes at the CDN Edge in <5ms, protecting sensitive admin dashboards before heavy backend rendering starts.`,
          mainExample: {
            title: "Protected Route Auth Middleware",
            language: "typescript",
            code: `// middleware.ts\nimport { NextResponse } from "next/server";\nimport type { NextRequest } from "next/server";\n\nexport function middleware(request: NextRequest) {\n  const token = request.cookies.get("session_token");\n  if (!token && request.nextUrl.pathname.startsWith("/admin")) {\n    return NextResponse.redirect(new URL("/auth/login", request.url));\n  }\n  return NextResponse.next();\n}\n\nexport const config = { matcher: ["/admin/:path*", "/dashboard/:path*"] };`,
            executable: false,
            explanation: ["matcher restricts middleware execution to specific route prefixes."],
          },
          detailedExplanation: ["NextResponse.rewrite() shows different content while preserving the original URL."],
          commonMistakes: [],
          bestPractices: ["Keep middleware lightweight; avoid heavy database queries inside edge middleware."],
          summary: ["Edge Middleware delivers sub-millisecond request protection and routing."],
        },
      ],
    },
    {
      id: "mod-next-11",
      slug: "deployment",
      title: "Module 11: Deploying to Vercel & Production Scaling",
      description: "Environment variables, standalone Docker output, and multi-region deployment.",
      lessons: [
        {
          id: "next-deploy",
          slug: "vercel-deployment-and-docker",
          courseSlug: "nextjs",
          moduleSlug: "deployment",
          title: "Production Deployment & Standalone Docker Builds",
          description: "Deploy Next.js apps with zero-config on Vercel or containerize with output: 'standalone' for Docker.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Deploying full-stack Next.js apps to Vercel with preview environments",
            "Configuring output: 'standalone' in next.config.ts for minimal Docker images",
            "Managing production environment variables and database connection pools",
          ],
          introduction: `Next.js can be deployed to serverless Edge infrastructure like Vercel or packaged into self-contained container images for Kubernetes and AWS ECS.`,
          whyItMatters: `Using output: 'standalone' reduces production Docker container image size from 1.2GB to under 80MB!`,
          mainExample: {
            title: "Standalone Build Configuration",
            language: "typescript",
            code: `// next.config.ts\nimport type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {\n  output: "standalone", // Bundles minimal node_modules for Docker\n};\n\nexport default nextConfig;`,
            executable: false,
            explanation: ["Standalone output produces a self-contained server.js bundle."],
          },
          detailedExplanation: ["Vercel automatically provisions Serverless Functions for API routes and Server Actions."],
          commonMistakes: [],
          bestPractices: ["Use connection poolers like PgBouncer or Neon when connecting serverless routes to PostgreSQL."],
          summary: ["Next.js scales effortlessly from serverless clouds to containerized enterprise clusters."],
        },
      ],
    },
  ],
};
