import { Course } from "@/types";

export const nodejsCourse: Course = {
  id: "course-nodejs",
  slug: "nodejs",
  title: "Node.js & Express REST API Engineering",
  tagline: "Build scalable, asynchronous backend services, middleware pipelines, and secure REST APIs.",
  description: "Master Node.js runtime and Express: asynchronous I/O, event loop, file system, streams, HTTP servers, Express routing, middleware, JWT auth, rate limiting, error handling, and Prisma ORM integration.",
  category: "Backend",
  level: "Intermediate",
  estimatedHours: 26,
  icon: "Server",
  badgeColor: "emerald",
  prerequisites: ["JavaScript Fundamentals"],
  skillsGained: [
    "Node.js Event Loop & Non-Blocking Asynchronous I/O",
    "Express Routing & Middleware Pipeline Architecture",
    "RESTful API Design Standards & HTTP Status Codes",
    "JWT Authentication & Password Hashing with Bcrypt",
    "Database Integration with PostgreSQL & Prisma ORM",
  ],
  featured: true,
  modules: [
    {
      id: "mod-node-1",
      slug: "intro",
      title: "Module 1: Node.js Runtime & Libuv Event Loop",
      description: "How Node.js executes JavaScript on the server with V8 and libuv.",
      lessons: [
        {
          id: "node-intro",
          slug: "nodejs-introduction",
          courseSlug: "nodejs",
          moduleSlug: "intro",
          title: "Node.js Introduction & Server Architecture",
          description: "Understand Node.js runtime, event loop, and build a fast HTTP REST server with Express.",
          durationMinutes: 15,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How Node.js executes JavaScript on the server via the V8 engine",
            "The non-blocking event-driven architecture and libuv thread pool",
            "Creating Express REST route handlers with JSON responses",
          ],
          introduction: `Node.js is an open-source, cross-platform JavaScript runtime built on Chrome's V8 JavaScript engine. It uses an event-driven, non-blocking I/O model.`,
          whyItMatters: `Node.js powers millions of microservices across companies like Netflix, PayPal, LinkedIn, and NASA.`,
          mainExample: {
            title: "Express REST Server",
            language: "javascript",
            code: `const express = require("express");\nconst app = express();\n\napp.use(express.json());\napp.get("/api/health", (req, res) => res.json({ status: "healthy" }));\napp.listen(4000, () => console.log("Server online on port 4000"));`,
            executable: false,
            explanation: ["Express simplifies HTTP server creation and routing."],
          },
          detailedExplanation: ["The single-threaded event loop delegates file and network operations to libuv."],
          commonMistakes: [],
          bestPractices: ["Avoid blocking the main thread with heavy CPU calculations in Node.js."],
          summary: ["Node.js delivers high-throughput backend services using JavaScript."],
        },
      ],
    },
    {
      id: "mod-node-2",
      slug: "core-modules",
      title: "Module 2: Core Modules (fs, path, events, os)",
      description: "Interacting with the operating system, file system promises, and EventEmitter.",
      lessons: [
        {
          id: "node-fs-events",
          slug: "fs-path-and-eventemitter",
          courseSlug: "nodejs",
          moduleSlug: "core-modules",
          title: "File System (fs/promises) & EventEmitter",
          description: "Read and write files asynchronously with fs/promises, resolve cross-platform paths with path, and publish custom events.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Reading/writing files asynchronously with fs.promises",
            "Resolving cross-platform file paths using path.join and path.resolve",
            "Building event-driven architectures with EventEmitter",
          ],
          introduction: `Node.js comes bundled with core standard library modules for interacting directly with the filesystem, operating system, and process environment.`,
          whyItMatters: `Using fs.promises avoids blocking the event loop while reading files from disk.`,
          mainExample: {
            title: "Async File Reading with fs/promises",
            language: "javascript",
            code: `const fs = require("fs/promises");\nconst path = require("path");\n\nasync function loadConfig() {\n  const configPath = path.join(__dirname, "config.json");\n  const rawData = await fs.readFile(configPath, "utf-8");\n  return JSON.parse(rawData);\n}\nconsole.log("File system utilities loaded.");`,
            executable: false,
            explanation: ["path.join safely handles both Windows (\\) and POSIX (/) path separators."],
          },
          detailedExplanation: ["EventEmitter enables decoupled pub/sub architectures across backend subsystems."],
          commonMistakes: [],
          bestPractices: ["Never use synchronous methods like fs.readFileSync in production servers."],
          summary: ["Core modules provide native access to the operating system and filesystem."],
        },
      ],
    },
    {
      id: "mod-node-3",
      slug: "streams-buffers",
      title: "Module 3: Buffers, Streams & Binary Data",
      description: "Handling multi-gigabyte files with readable, writable, and transform streams.",
      lessons: [
        {
          id: "node-streams",
          slug: "streams-and-buffers",
          courseSlug: "nodejs",
          moduleSlug: "streams-buffers",
          title: "Node.js Streams & Memory Optimization (pipeline)",
          description: "Process massive datasets without memory overflow using Readable, Writable, and Transform streams.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Why loading a 2GB file into memory with readFile() crashes the process",
            "Piping streams with stream.pipeline to prevent memory leaks",
            "Transform streams for real-time gzip compression and cryptography",
          ],
          introduction: `Streams are collections of data—just like arrays or strings. The difference is that streams might not be available all at once and don't have to fit in memory.`,
          whyItMatters: `Using streams allows a Node server with 512MB RAM to process 10GB video files smoothly without out-of-memory crashes.`,
          mainExample: {
            title: "Stream Pipeline with Gzip Compression",
            language: "javascript",
            code: `const fs = require("fs");\nconst zlib = require("zlib");\nconst { pipeline } = require("stream/promises");\n\nasync function compressFile(input, output) {\n  await pipeline(\n    fs.createReadStream(input),\n    zlib.createGzip(),\n    fs.createWriteStream(output)\n  );\n  console.log("File compressed successfully.");\n}`,
            executable: false,
            explanation: ["pipeline automatically manages stream backpressure and error destruction."],
          },
          detailedExplanation: ["Backpressure prevents fast read streams from overwhelming slow network write streams."],
          commonMistakes: [],
          bestPractices: ["Always use stream.pipeline instead of .pipe() for robust error cleanup."],
          summary: ["Streams enable memory-efficient processing of massive datasets."],
        },
      ],
    },
    {
      id: "mod-node-4",
      slug: "http-networking",
      title: "Module 4: HTTP Server & Networking Fundamentals",
      description: "The native http/https module, request headers, status codes, and WebSockets.",
      lessons: [
        {
          id: "node-http",
          slug: "native-http-and-websockets",
          courseSlug: "nodejs",
          moduleSlug: "http-networking",
          title: "Native HTTP Server & Real-Time WebSockets",
          description: "Build HTTP servers from scratch using the native 'http' module and establish bidirectional WebSocket connections.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Building low-level HTTP servers with http.createServer",
            "Parsing incoming URL queries and request headers",
            "Establishing persistent bidirectional WebSocket connections (ws)",
          ],
          introduction: `The Node.js 'http' module allows Node to transfer data over the Hyper Text Transfer Protocol (HTTP). WebSockets upgrade HTTP connections to full-duplex real-time channels.`,
          whyItMatters: `Real-time chat apps, multiplayer games, and live stock tickers rely on persistent WebSocket connections.`,
          mainExample: {
            title: "Native HTTP Server",
            language: "javascript",
            code: `const http = require("http");\n\nconst server = http.createServer((req, res) => {\n  res.writeHead(200, { "Content-Type": "application/json" });\n  res.end(JSON.stringify({ message: "Native Node.js Server Response" }));\n});\n\nserver.listen(5000, () => console.log("HTTP server ready."));`,
            executable: false,
            explanation: ["http.createServer handles incoming sockets and constructs request/response streams."],
          },
          detailedExplanation: ["WebSockets upgrade HTTP 1.1 handshake to persistent TCP binary streams."],
          commonMistakes: [],
          bestPractices: ["Use Express or Fastify for production REST apps and 'ws' for WebSocket servers."],
          summary: ["HTTP and WebSockets power web communication and real-time streaming."],
        },
      ],
    },
    {
      id: "mod-node-5",
      slug: "express-routing",
      title: "Module 5: Express Framework & Routing Architecture",
      description: "Express application instance, router chaining, and parameterized routes (:id).",
      lessons: [
        {
          id: "node-express-routes",
          slug: "express-router-and-controllers",
          courseSlug: "nodejs",
          moduleSlug: "express-routing",
          title: "Express Router & MVC Controller Architecture",
          description: "Organize large backend codebases using Express.Router(), modular controllers, and service layers.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Splitting routes with express.Router() into separate files",
            "Route parameters (:courseSlug) and query strings (req.query)",
            "The Model-View-Controller (MVC) architectural pattern",
          ],
          introduction: `Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.`,
          whyItMatters: `Using Express.Router() allows teams to partition large API codebases into clean feature modules (/users, /courses, /payments).`,
          mainExample: {
            title: "Modular Express Router",
            language: "javascript",
            code: `// routes/courseRoutes.js\nconst express = require("express");\nconst router = express.Router();\n\nrouter.get("/", (req, res) => res.json({ courses: [] }));\nrouter.get("/:id", (req, res) => {\n  const { id } = req.params;\n  res.json({ id, title: "HTML5 Architecture" });\n});\n\nmodule.exports = router;`,
            executable: false,
            explanation: ["router mounts cleanly under app.use('/api/courses', courseRouter)."],
          },
          detailedExplanation: ["Controllers hold business logic while routes define endpoint contracts."],
          commonMistakes: [],
          bestPractices: ["Keep route files thin and delegate logic to controller functions."],
          summary: ["Express Router structures backend endpoints cleanly and modularly."],
        },
      ],
    },
    {
      id: "mod-node-6",
      slug: "middleware-errors",
      title: "Module 6: Middleware Pipelines & Global Error Handling",
      description: "The (req, res, next) pipeline, third-party middleware, and centralized error handlers.",
      lessons: [
        {
          id: "node-middleware",
          slug: "middleware-and-global-errors",
          courseSlug: "nodejs",
          moduleSlug: "middleware-errors",
          title: "Middleware Pipelines & Centralized Error Handlers",
          description: "Chain request middleware (req, res, next) and build centralized 4-parameter error handlers (err, req, res, next).",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How Express executes middleware functions in sequential order",
            "Writing custom authentication and request logging middleware",
            "Centralized error handling middleware with 4 parameters",
          ],
          introduction: `Middleware functions are functions that have access to the request object (req), response object (res), and the next middleware function in the application’s request-response cycle.`,
          whyItMatters: `Centralized error middleware prevents duplicated try/catch blocks across 50+ route controllers.`,
          mainExample: {
            title: "Global Error Handling Middleware",
            language: "javascript",
            code: `// Centralized Error Middleware (must have 4 arguments)\napp.use((err, req, res, next) => {\n  console.error("Unhandled API Error:", err.stack);\n  const status = err.statusCode || 500;\n  res.status(status).json({\n    error: {\n      message: err.message || "Internal Server Error",\n      status,\n    },\n  });\n});`,
            executable: false,
            explanation: ["4 parameters signal to Express that this is an error handler."],
          },
          detailedExplanation: ["Call next(error) inside any controller to jump directly to the global error middleware."],
          commonMistakes: [],
          bestPractices: ["Always place the global error handling middleware as the last app.use() statement."],
          summary: ["Middleware pipelines orchestrate request processing and centralized error recovery."],
        },
      ],
    },
    {
      id: "mod-node-7",
      slug: "rest-apis",
      title: "Module 7: REST API Standards & Request Validation",
      description: "RESTful HTTP status codes, Zod schema validation, and OpenAPI documentation.",
      lessons: [
        {
          id: "node-validation",
          slug: "rest-standards-and-zod-validation",
          courseSlug: "nodejs",
          moduleSlug: "rest-apis",
          title: "RESTful API Standards & Schema Validation with Zod",
          description: "Design clean RESTful resources, enforce HTTP status codes (200, 201, 400, 404, 500), and validate payloads with Zod.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Proper HTTP status code usage (201 Created, 204 No Content, 422 Unprocessable)",
            "Validating req.body and req.query with Zod schemas",
            "Preventing malformed or malicious payload injections",
          ],
          introduction: `REST (Representational State Transfer) is an architectural style for providing standards between computer systems on the web. Schema validation guarantees data integrity before reaching your database.`,
          whyItMatters: `Validating inputs with Zod stops invalid email formats or missing fields before SQL queries execute.`,
          mainExample: {
            title: "Zod Schema Validation Middleware",
            language: "javascript",
            code: `const { z } = require("zod");\n\nconst RegisterSchema = z.object({\n  email: z.string().email(),\n  password: z.string().min(8),\n  name: z.string().min(2),\n});\n\nfunction validateRegister(req, res, next) {\n  const result = RegisterSchema.safeParse(req.body);\n  if (!result.success) {\n    return res.status(400).json({ errors: result.error.errors });\n  }\n  req.validatedBody = result.data;\n  next();\n}`,
            executable: false,
            explanation: ["safeParse validates inputs without throwing runtime exceptions."],
          },
          detailedExplanation: ["Return HTTP 400 Bad Request with explicit validation error messages."],
          commonMistakes: [],
          bestPractices: ["Always validate incoming request data at the controller boundary."],
          summary: ["Schema validation ensures secure, predictable RESTful API operations."],
        },
      ],
    },
    {
      id: "mod-node-8",
      slug: "auth-jwt",
      title: "Module 8: Authentication with JWT & Bcrypt Hashing",
      description: "Password salting with bcrypt, signed JSON Web Tokens, and auth guard middleware.",
      lessons: [
        {
          id: "node-auth-jwt",
          slug: "jwt-authentication",
          courseSlug: "nodejs",
          moduleSlug: "auth-jwt",
          title: "JWT Authentication & Password Security",
          description: "Implement secure user registration, bcrypt password hashing, and stateless JSON Web Tokens.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Why plain text passwords must never be stored",
            "Salting and hashing passwords with bcrypt",
            "Signing and verifying JWT access tokens",
          ],
          introduction: `JSON Web Tokens (JWT) are an open standard for securely transmitting information between parties as a JSON object.`,
          whyItMatters: `Stateless JWT authentication enables horizontal scaling across dozens of distributed server containers.`,
          mainExample: {
            title: "User Sign-In & JWT Generation",
            language: "javascript",
            code: `const jwt = require("jsonwebtoken");\nconst bcrypt = require("bcryptjs");\n\nasync function handleLogin(email, password, userRecord) {\n  const isMatch = await bcrypt.compare(password, userRecord.hashedPassword);\n  if (!isMatch) throw new Error("Invalid credentials");\n  const token = jwt.sign({ userId: userRecord.id }, process.env.JWT_SECRET, { expiresIn: "2h" });\n  return { token };\n}`,
            executable: false,
            explanation: ["bcrypt.compare verifies passwords securely without exposing plain text."],
          },
          detailedExplanation: ["Tokens are sent in the Authorization header: Bearer <token>."],
          commonMistakes: [],
          bestPractices: ["Always store JWT secret keys in environment variables (.env)."],
          summary: ["JWT tokens provide secure, stateless identity verification."],
        },
      ],
    },
    {
      id: "mod-node-9",
      slug: "database-orm",
      title: "Module 9: Database ORM with PostgreSQL & Prisma",
      description: "Relational database modeling with Prisma schema, migrations, and type-safe queries.",
      lessons: [
        {
          id: "node-prisma",
          slug: "postgresql-and-prisma-orm",
          courseSlug: "nodejs",
          moduleSlug: "database-orm",
          title: "PostgreSQL & Type-Safe Prisma ORM",
          description: "Model relational database schemas, run migrations with Prisma CLI, and execute type-safe queries.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Defining Prisma data models and 1-to-many relationships",
            "Running database migrations (prisma migrate dev)",
            "Executing CRUD operations with Prisma Client (findMany, create, update)",
          ],
          introduction: `Prisma is a next-generation Node.js and TypeScript ORM that provides an intuitive schema modeling language, automated migrations, and type-safe database queries.`,
          whyItMatters: `Prisma eliminates SQL typos and guarantees that database query results match TypeScript types perfectly.`,
          mainExample: {
            title: "Prisma Query in Express Route",
            language: "typescript",
            code: `// services/courseService.ts\nimport { PrismaClient } from "@prisma/client";\nconst prisma = new PrismaClient();\n\nexport async function getFeaturedCourses() {\n  return prisma.course.findMany({\n    where: { featured: true },\n    include: { modules: true },\n  });\n}`,
            executable: false,
            explanation: ["include: { modules: true } performs an optimized SQL JOIN automatically."],
          },
          detailedExplanation: ["Prisma Client manages connection pooling and query optimization under the hood."],
          commonMistakes: [],
          bestPractices: ["Reuse a single PrismaClient singleton instance across your application."],
          summary: ["Prisma delivers type-safe, ergonomic database access in Node.js applications."],
        },
      ],
    },
    {
      id: "mod-node-10",
      slug: "security",
      title: "Module 10: Rate Limiting, CORS & AppSec Hardening",
      description: "express-rate-limit, cors configuration, helmet security headers, and sanitization.",
      lessons: [
        {
          id: "node-security",
          slug: "rate-limiting-cors-and-helmet",
          courseSlug: "nodejs",
          moduleSlug: "security",
          title: "Production Hardening (Helmet, CORS, Rate Limiting)",
          description: "Protect Express servers against brute-force attacks, unauthorized origins, and cross-site scripting.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Enabling security HTTP headers with helmet()",
            "Configuring strict Cross-Origin Resource Sharing (CORS) whitelists",
            "Rate limiting authentication endpoints with express-rate-limit",
          ],
          introduction: `Securing Node.js APIs requires defense-in-depth: rate limiting against DDoS/brute-force, strict CORS headers against cross-origin data theft, and security headers against clickjacking.`,
          whyItMatters: `Unprotected login routes can be brute-forced with 100,000 dictionary attempts in minutes without rate limiting.`,
          mainExample: {
            title: "Security Middleware Configuration",
            language: "javascript",
            code: `const helmet = require("helmet");\nconst cors = require("cors");\nconst rateLimit = require("express-rate-limit");\n\napp.use(helmet());\napp.use(cors({ origin: "https://kwasacademy.dev" }));\napp.use("/api/auth", rateLimit({\n  windowMs: 15 * 60 * 1000,\n  max: 5,\n  message: "Too many attempts. Try again in 15 minutes.",\n}));`,
            executable: false,
            explanation: ["helmet sets essential security headers (HSTS, CSP, X-Frame-Options)."],
          },
          detailedExplanation: ["CORS whitelisting blocks unauthorized third-party websites from making credentialed API calls."],
          commonMistakes: [],
          bestPractices: ["Never use cors({ origin: '*' }) on authenticated private API endpoints."],
          summary: ["AppSec hardening insulates backend APIs from exploits and abuse."],
        },
      ],
    },
    {
      id: "mod-node-11",
      slug: "production",
      title: "Module 11: Logging, Clustering & Production PM2/Docker",
      description: "Structured logging with Winston, multi-core clustering, PM2 process management, and health checks.",
      lessons: [
        {
          id: "node-production",
          slug: "clustering-pm2-and-logging",
          courseSlug: "nodejs",
          moduleSlug: "production",
          title: "Multi-Core Clustering, PM2 & Structured Logging",
          description: "Utilize all CPU cores with cluster / PM2 and emit structured JSON logs with Winston.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Why single-threaded Node.js uses only 1 CPU core by default",
            "Spawning worker processes across all CPU cores with PM2 Cluster Mode",
            "Structured JSON logging with Winston for cloud monitoring (Datadog/CloudWatch)",
          ],
          introduction: `In production, Node.js applications run across multiple worker processes managed by process managers like PM2 or Docker Kubernetes replicas.`,
          whyItMatters: `PM2 Cluster mode automatically multiplies throughput by 4x to 16x by utilizing all available CPU cores on the host machine.`,
          mainExample: {
            title: "PM2 Ecosystem Config",
            language: "javascript",
            code: `// ecosystem.config.js\nmodule.exports = {\n  apps: [{\n    name: "kwas-api",\n    script: "dist/server.js",\n    instances: "max", // Utilize all CPU cores\n    exec_mode: "cluster",\n    env_production: {\n      NODE_ENV: "production",\n    },\n  }],\n};`,
            executable: false,
            explanation: ["instances: 'max' spawns one process per CPU core with automatic load balancing."],
          },
          detailedExplanation: ["PM2 monitors worker health and restarts crashed processes in milliseconds."],
          commonMistakes: [],
          bestPractices: ["Always log in structured JSON format in production environments."],
          summary: ["Clustering and process managers ensure high availability and maximum hardware throughput."],
        },
      ],
    },
  ],
};
