import { Course } from "@/types";

export const pythonCourse: Course = {
  id: "course-python",
  slug: "python",
  title: "Python Software Engineering & Data Architecture",
  tagline: "From language fundamentals to object-oriented design, async I/O, data pipelines, and AI foundations.",
  description: "Learn Python 3 for modern engineering: syntax, data structures, list comprehensions, object-oriented programming, decorators, generators, context managers, type hints, package management, and backend/AI pipelines.",
  category: "Programming Languages",
  level: "Beginner",
  estimatedHours: 28,
  icon: "Terminal",
  badgeColor: "emerald",
  prerequisites: ["Basic computer fundamentals."],
  skillsGained: [
    "Python 3 Idiomatic Syntax & PEP 8 Standards",
    "Object-Oriented Programming & Dunder Methods",
    "List, Dict & Set Comprehensions",
    "Decorators, Generators & Context Managers",
    "Type Hinting & Static Typing with mypy",
  ],
  featured: true,
  modules: [
    {
      id: "mod-py-1",
      slug: "intro",
      title: "Module 1: Python Overview & The Zen of Python",
      description: "Python philosophy (import this), indentation rules, interpreter, and REPL.",
      lessons: [
        {
          id: "py-intro",
          slug: "python-introduction",
          courseSlug: "python",
          moduleSlug: "intro",
          title: "Python Introduction & Zen of Python",
          description: "Learn Python's philosophy, syntax simplicity, virtual environments, and interpreter architecture.",
          durationMinutes: 12,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Why Python leads automation, backend, and AI",
            "Indentation-based syntax rules",
            "Writing idiomatic, clean Python (PEP 8)",
          ],
          introduction: `Python is a high-level, interpreted programming language known for its clear syntax and readability. Designed by Guido van Rossum, it emphasizes code simplicity.`,
          whyItMatters: `Python is the undisputed standard language for Artificial Intelligence, Machine Learning, Data Engineering, and automation.`,
          mainExample: {
            title: "List Comprehension & Formatting",
            language: "python",
            code: `numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\neven_squares = [n ** 2 for n in numbers if n % 2 == 0]\nprint(f"Even squares: {even_squares}")`,
            executable: true,
            explanation: ["List comprehensions provide concise filtering and mapping in a single line."],
          },
          detailedExplanation: ["Python uses 4 spaces for block indentation instead of curly braces."],
          commonMistakes: [],
          bestPractices: ["Follow PEP 8 styling conventions."],
          summary: ["Python combines simplicity with immense computational power."],
        },
      ],
    },
    {
      id: "mod-py-2",
      slug: "types-strings",
      title: "Module 2: Variables, Data Types & String Formatting",
      description: "int, float, bool, str, f-strings, string methods, and type casting.",
      lessons: [
        {
          id: "py-types",
          slug: "data-types-and-f-strings",
          courseSlug: "python",
          moduleSlug: "types-strings",
          title: "Python Data Types, Type Casting & f-Strings",
          description: "Master numeric types, boolean logic, string methods, and formatted f-strings (f'{var:.2f}').",
          durationMinutes: 14,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Dynamic typing in Python (int, float, str, bool)",
            "Explicit type casting (int('42'), float('3.14'))",
            "Modern f-string interpolation and decimal formatting",
          ],
          introduction: `Python is dynamically and strongly typed: variable types are determined at runtime, but invalid operations (like adding a string to an integer) raise explicit TypeErrors.`,
          whyItMatters: `f-strings (introduced in Python 3.6) provide the fastest and most readable string interpolation syntax in Python.`,
          mainExample: {
            title: "f-String Formatting",
            language: "python",
            code: `course = "KWAS Academy Python"\nprice = 0.00\nrating = 4.982\n\nprint(f"Course: {course} | Price: \${price:.2f} | Rating: {rating:.1f}/5.0")`,
            executable: true,
            explanation: ["f-strings support inline formatting specifiers like :.2f for decimals."],
          },
          detailedExplanation: ["Strings in Python are immutable; string methods return new modified copies."],
          commonMistakes: [],
          bestPractices: ["Always use f-strings instead of old % formatting or str.format()."],
          summary: ["f-strings and dynamic types provide expressive, concise data representation."],
        },
      ],
    },
    {
      id: "mod-py-3",
      slug: "control-flow",
      title: "Module 3: Control Flow, Loops & Conditionals",
      description: "if/elif/else, for loops, while loops, range(), break, continue, and match/case.",
      lessons: [
        {
          id: "py-control",
          slug: "loops-and-pattern-matching",
          courseSlug: "python",
          moduleSlug: "control-flow",
          title: "Loops, range(), and match/case Pattern Matching",
          description: "Iterate with for and while loops, generate sequences with range(), and use Python 3.10 match/case.",
          durationMinutes: 16,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "for loops with range(start, stop, step)",
            "while loops and loop control (break, continue, else)",
            "Structural pattern matching with match/case (Python 3.10+)",
          ],
          introduction: `Control flow dictates the execution path of a program based on conditional evaluations and iterative loops.`,
          whyItMatters: `Structural pattern matching (match/case) allows elegant destructuring and matching on tuples, dicts, and objects.`,
          mainExample: {
            title: "match/case Pattern Matching",
            language: "python",
            code: `def handle_command(command):\n    match command.split():\n        case ["quit"]:\n            return "Exiting system..."\n        case ["load", filename]:\n            return f"Loading file: {filename}"\n        case _:\n            return "Unknown command"\n\nprint(handle_command("load dataset.csv"))`,
            executable: true,
            explanation: ["match/case matches pattern structures and unpacks variables in one step."],
          },
          detailedExplanation: ["The for...else construct in Python executes the else block only if the loop completes without hitting break."],
          commonMistakes: [],
          bestPractices: ["Use enumerate(list) when you need both the index and element in for loops."],
          summary: ["Pattern matching and idiomatic loops provide clean algorithmic control."],
        },
      ],
    },
    {
      id: "mod-py-4",
      slug: "collections",
      title: "Module 4: Collections: Lists, Tuples, Dicts & Sets",
      description: "Mutable lists, immutable tuples, hash-map dictionaries, and unique sets.",
      lessons: [
        {
          id: "py-collections",
          slug: "lists-tuples-dicts-and-sets",
          courseSlug: "python",
          moduleSlug: "collections",
          title: "Python Collections (Lists, Tuples, Dicts, Sets)",
          description: "Master Python's built-in collection types, dictionary lookups, and set operations (union, intersection).",
          durationMinutes: 18,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Lists (mutable ordered) vs Tuples (immutable ordered)",
            "Dictionaries (key-value hash maps) with dict.get(key, default)",
            "Sets for mathematical set operations (union |, intersection &)",
          ],
          introduction: `Python's built-in collection types are highly optimized C implementations designed for speed and flexibility.`,
          whyItMatters: `Dictionary key lookups in Python operate in O(1) average time, making them ideal for high-speed indexing.`,
          mainExample: {
            title: "Dictionary & Set Operations",
            language: "python",
            code: `student = {"id": "S101", "name": "Alex Dev", "gpa": 3.9}\n\n# Safe dictionary lookup with default\nmajor = student.get("major", "Undeclared")\nprint(f"Student: {student['name']} | Major: {major}")\n\nskills_a = {"Python", "SQL", "Docker"}\nskills_b = {"Docker", "Kubernetes", "AWS"}\ncommon = skills_a & skills_b # Set intersection\nprint("Common Skills:", common)`,
            executable: true,
            explanation: ["student.get avoids KeyErrors by returning the default value."],
          },
          detailedExplanation: ["Tuples are hashable and can be used as dictionary keys, whereas lists cannot."],
          commonMistakes: [],
          bestPractices: ["Use set for fast O(1) membership testing (if item in my_set)."],
          summary: ["Collections form the backbone of Python data manipulation."],
        },
      ],
    },
    {
      id: "mod-py-5",
      slug: "comprehensions",
      title: "Module 5: List, Dict & Set Comprehensions",
      description: "Declarative transformations, nested comprehensions, and conditional filtering.",
      lessons: [
        {
          id: "py-comprehensions",
          slug: "comprehensions-mastery",
          courseSlug: "python",
          moduleSlug: "comprehensions",
          title: "Comprehensions Mastery (List, Dict, Set)",
          description: "Write idiomatic Python transformations using list, dictionary, and set comprehensions.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "List comprehensions for inline map and filter operations",
            "Dictionary comprehensions ({k: v for ...}) for key re-mapping",
            "Set comprehensions for filtered unique sets",
          ],
          introduction: `Comprehensions provide a concise syntax to create new collections based on existing iterables.`,
          whyItMatters: `Comprehensions run in optimized C bytecode inside the Python interpreter, executing faster than manual for-loop appends.`,
          mainExample: {
            title: "Dictionary & List Comprehensions",
            language: "python",
            code: `names = ["alex", "sarah", "kenneth", "elena"]\nuppercase_names = [name.upper() for name in names if len(name) > 4]\nprint("Filtered List:", uppercase_names)\n\nname_lengths = {name: len(name) for name in names}\nprint("Dict Mapping:", name_lengths)`,
            executable: true,
            explanation: ["Dictionary comprehension creates key-value pairs in one declarative step."],
          },
          detailedExplanation: ["Avoid writing deeply nested multi-line comprehensions as they degrade code readability."],
          commonMistakes: [],
          bestPractices: ["Keep comprehensions to a single line; if complex logic is required, use a standard for loop."],
          summary: ["Comprehensions deliver fast, expressive collection transformations."],
        },
      ],
    },
    {
      id: "mod-py-6",
      slug: "functions",
      title: "Module 6: Functions, Args, Kwargs & Lambda",
      description: "Positional vs keyword arguments, *args, **kwargs, lambda functions, and type hints.",
      lessons: [
        {
          id: "py-functions",
          slug: "functions-args-kwargs-and-type-hints",
          courseSlug: "python",
          moduleSlug: "functions",
          title: "*args, **kwargs, Lambdas & Type Hints",
          description: "Build flexible functions with variable positional and keyword arguments, and add static type hints.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Variable positional arguments (*args) and keyword arguments (**kwargs)",
            "Anonymous lambda functions for sorting and mapping",
            "Type hints (def fn(x: int) -> str) and verification with mypy",
          ],
          introduction: `Functions in Python support flexible argument passing mechanisms and optional static type hints.`,
          whyItMatters: `Type hints in modern Python power frameworks like FastAPI and Pydantic for automatic data validation.`,
          mainExample: {
            title: "Type-Hinted Function with **kwargs",
            language: "python",
            code: `def build_profile(user_id: str, **metadata: str) -> dict[str, str]:\n    profile = {"id": user_id}\n    profile.update(metadata)\n    return profile\n\nuser = build_profile("usr_101", name="Alex", role="Engineer")\nprint("Profile:", user)`,
            executable: true,
            explanation: ["**metadata captures arbitrary keyword arguments into a dictionary."],
          },
          detailedExplanation: ["Type hints do not impact runtime performance; they are used by IDEs and linters."],
          commonMistakes: [],
          bestPractices: ["Always include type hints on public utility functions."],
          summary: ["Type hints and flexible arguments make Python codebases clean and scalable."],
        },
      ],
    },
    {
      id: "mod-py-7",
      slug: "oop-dunder",
      title: "Module 7: Object-Oriented Python & Dunder Methods",
      description: "Classes, inheritance, encapsulation, @property, and dunder methods (__str__, __repr__, __eq__).",
      lessons: [
        {
          id: "py-oop",
          slug: "oop-and-decorators",
          courseSlug: "python",
          moduleSlug: "oop-dunder",
          title: "OOP, Dunder Methods & Properties (@property)",
          description: "Master classes, __repr__, __eq__, getters/setters with @property, and method overriding.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Object-Oriented classes, constructors (__init__), and inheritance",
            "Special Dunder methods (__str__, __repr__, __len__, __eq__)",
            "Encapsulating getters/setters with the @property decorator",
          ],
          introduction: `In Python, everything is an object. Custom classes define encapsulated data and behavior. Special double-underscore ('dunder') methods allow classes to integrate with Python language features.`,
          whyItMatters: `Implementing __repr__ and __eq__ allows objects to be printed and compared naturally with ==.`,
          mainExample: {
            title: "Custom Class with Dunder Methods",
            language: "python",
            code: `class Developer:\n    def __init__(self, name: str, level: int):\n        self.name = name\n        self.level = level\n\n    def __repr__(self) -> str:\n        return f"Developer(name='{self.name}', level={self.level})"\n\n    def __eq__(self, other) -> bool:\n        return isinstance(other, Developer) and self.level == other.level\n\nd1 = Developer("Alex", 3)\nd2 = Developer("Sarah", 3)\nprint(d1)\nprint(f"Equal Experience Level: {d1 == d2}")`,
            executable: true,
            explanation: ["__repr__ defines the official string representation; __eq__ enables == comparison."],
          },
          detailedExplanation: ["@property allows method calls to look like standard attribute access without breaking public APIs."],
          commonMistakes: [],
          bestPractices: ["Always implement __repr__ on domain data model classes."],
          summary: ["Dunder methods allow custom classes to integrate seamlessly into Python's object model."],
        },
      ],
    },
    {
      id: "mod-py-8",
      slug: "decorators-generators",
      title: "Module 8: Custom Decorators & Generators",
      description: "Higher-order decorators (@decorator), yield keyword, and memory-efficient generator iterators.",
      lessons: [
        {
          id: "py-generators",
          slug: "custom-decorators-and-generators",
          courseSlug: "python",
          moduleSlug: "decorators-generators",
          title: "Custom Function Decorators & Memory Generators (yield)",
          description: "Write timing/caching decorators and stream infinite datasets with generators and the 'yield' keyword.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Writing custom decorators with functools.wraps",
            "Streaming data one item at a time with yield generators",
            "Memory differences: generator expressions vs list comprehensions",
          ],
          introduction: `Decorators modify function behavior without altering their source code. Generators produce items lazily on demand rather than allocating entire collections in memory.`,
          whyItMatters: `Streaming a 10,000,000 row CSV with a generator uses 5KB memory instead of 4GB RAM.`,
          mainExample: {
            title: "Timing Decorator & Generator Stream",
            language: "python",
            code: `import time\nfrom functools import wraps\n\ndef timing(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        t0 = time.time()\n        result = func(*args, **kwargs)\n        print(f"[{func.__name__}] finished in {(time.time() - t0)*1000:.2f}ms")\n        return result\n    return wrapper\n\ndef number_stream(n):\n    for i in range(n):\n        yield i * i\n\n@timing\ndef run():\n    stream = number_stream(5)\n    print("Generator Yields:", list(stream))\n\nrun()`,
            executable: true,
            explanation: ["yield pauses function execution and returns the next value lazily."],
          },
          detailedExplanation: ["Generator expressions (x for x in data) use parentheses instead of square brackets."],
          commonMistakes: [],
          bestPractices: ["Use functools.wraps inside decorators to preserve docstrings and function names."],
          summary: ["Decorators and generators enable clean, memory-efficient software architectures."],
        },
      ],
    },
    {
      id: "mod-py-9",
      slug: "file-io",
      title: "Module 9: File I/O, Context Managers & JSON",
      description: "Reading/writing files with 'with open(...)', custom context managers (__enter__/__exit__), and JSON parsing.",
      lessons: [
        {
          id: "py-files",
          slug: "context-managers-and-json",
          courseSlug: "python",
          moduleSlug: "file-io",
          title: "Context Managers (with) & JSON Serialization",
          description: "Manage file handles safely with context managers and serialize Python structures with the json module.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Why the 'with' statement guarantees files close even on exceptions",
            "Writing custom context managers with contextlib.contextmanager",
            "Serializing and deserializing data with json.dumps and json.loads",
          ],
          introduction: `Context managers in Python handle resource allocation and cleanup automatically, ensuring files, database transactions, and thread locks are released safely.`,
          whyItMatters: `Leaving file handles open causes OS file descriptor exhaustion in production servers.`,
          mainExample: {
            title: "JSON Serialization with Context Manager",
            language: "python",
            code: `import json\n\ndata = {\n    "platform": "KWAS Academy",\n    "courses": 18,\n    "active": True\n}\n\n# Serialize to JSON string\njson_text = json.dumps(data, indent=2)\nprint("JSON Output:\\n", json_text)`,
            executable: true,
            explanation: ["json.dumps serializes dictionaries into formatted JSON strings."],
          },
          detailedExplanation: ["The 'with' statement calls __enter__() on entry and guarantees __exit__() on completion."],
          commonMistakes: [],
          bestPractices: ["Always access files and locks using the 'with' statement."],
          summary: ["Context managers guarantee deterministic resource cleanup."],
        },
      ],
    },
    {
      id: "mod-py-10",
      slug: "asyncio",
      title: "Module 10: Asynchronous Python with AsyncIO",
      description: "AsyncIO event loop, async/await, coroutines, tasks, and asyncio.gather().",
      lessons: [
        {
          id: "py-asyncio",
          slug: "asyncio-and-coroutines",
          courseSlug: "python",
          moduleSlug: "asyncio",
          title: "AsyncIO, Coroutines & Concurrency (async/await)",
          description: "Perform non-blocking I/O operations concurrently using Python's native asyncio library.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The AsyncIO single-threaded event loop model",
            "Defining coroutines with async def and calling with await",
            "Running tasks concurrently with asyncio.gather()",
          ],
          introduction: `AsyncIO is a library to write concurrent code using the async/await syntax. It powers high-speed modern Python web frameworks like FastAPI and aiohttp.`,
          whyItMatters: `Fetching 100 API endpoints concurrently with AsyncIO takes 2 seconds instead of 200 seconds sequentially.`,
          mainExample: {
            title: "Concurrent Tasks with asyncio.gather",
            language: "python",
            code: `import asyncio\n\nasync def fetch_service(name, delay):\n    await asyncio.sleep(delay) # Non-blocking async sleep\n    return f"Service {name} online"\n\nasync def main():\n    results = await asyncio.gather(\n        fetch_service("Auth", 0.05),\n        fetch_service("Database", 0.08),\n        fetch_service("Cache", 0.02),\n    )\n    for r in results:\n        print(r)\n\nasyncio.run(main())`,
            executable: true,
            explanation: ["asyncio.gather executes all three coroutines concurrently."],
          },
          detailedExplanation: ["AsyncIO is ideal for I/O-bound network tasks; use multiprocessing for CPU-bound tasks."],
          commonMistakes: [],
          bestPractices: ["Never call synchronous blocking functions (like time.sleep) inside async coroutines."],
          summary: ["AsyncIO delivers high-throughput non-blocking concurrency in Python."],
        },
      ],
    },
    {
      id: "mod-py-11",
      slug: "packaging",
      title: "Module 11: Package Management with pip & Virtual Environments",
      description: "venv, pip, pyproject.toml, requirements.txt, and publishing packages to PyPI.",
      lessons: [
        {
          id: "py-packaging",
          slug: "virtual-environments-and-packaging",
          courseSlug: "python",
          moduleSlug: "packaging",
          title: "Virtual Environments (venv), pyproject.toml & pip",
          description: "Isolate project dependencies with venv, manage versions, and configure modern pyproject.toml package metadata.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Creating isolated environments with python -m venv .venv",
            "Locking dependencies with pip freeze > requirements.txt",
            "Modern packaging standards with pyproject.toml and hatch/poetry",
          ],
          introduction: `Python virtual environments create isolated folder environments with their own Python interpreter and site-packages, preventing dependency conflicts between projects.`,
          whyItMatters: `Virtual environments guarantee that installing package updates in one project never breaks other projects on your machine.`,
          mainExample: {
            title: "Virtual Environment Setup Commands",
            language: "bash",
            code: `# 1. Create virtual environment\npython -m venv .venv\n\n# 2. Activate environment\n# Windows: .venv\\Scripts\\activate\n# macOS/Linux: source .venv/bin/activate\n\n# 3. Install packages\npip install fastapi uvicorn pydantic`,
            executable: false,
            explanation: ["Virtual environment isolates installed binaries locally."],
          },
          detailedExplanation: ["Modern packaging uses pyproject.toml as defined in PEP 518/621."],
          commonMistakes: [],
          bestPractices: ["Never install packages globally into the system Python; always use a virtual environment."],
          summary: ["Virtual environments guarantee reproducible, conflict-free Python project dependencies."],
        },
      ],
    },
  ],
};
