import { Course } from "@/types";

export const reactCourse: Course = {
  id: "course-react",
  slug: "react",
  title: "React Component Engineering & State Architecture",
  tagline: "Build reactive, high-performance UI components with modern hooks, context, and declarative state.",
  description: "Master React: JSX, functional components, props, hooks (useState, useEffect, useMemo, useCallback, useRef), custom hooks, Context API, state management, and component lifecycles.",
  category: "Frontend",
  level: "Intermediate",
  estimatedHours: 26,
  icon: "Layers",
  badgeColor: "blue",
  prerequisites: ["JavaScript ES6+", "HTML & CSS"],
  skillsGained: [
    "Declarative UI & JSX Syntax Rules",
    "React Hooks (useState, useEffect, useMemo, useCallback, useRef)",
    "Custom Hooks & Component Logic Extraction",
    "Context API & Global State Architecture",
    "Virtual DOM & Reconciliation Performance Optimization",
  ],
  featured: true,
  modules: [
    {
      id: "mod-react-1",
      slug: "intro",
      title: "Module 1: React Foundations & Virtual DOM",
      description: "Declarative programming, component models, and the Virtual DOM reconciliation engine.",
      lessons: [
        {
          id: "react-intro",
          slug: "react-introduction",
          courseSlug: "react",
          moduleSlug: "intro",
          title: "React Introduction, Components & Virtual DOM",
          description: "Discover React's declarative component model, JSX syntax, props data flow, and the Virtual DOM.",
          durationMinutes: 15,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How React declaratively syncs the UI with underlying state",
            "Writing JSX and embedding JavaScript expressions",
            "Passing data down via immutable props",
          ],
          introduction: `React is an open-source JavaScript library developed by Meta for building user interfaces. Instead of manually updating DOM elements with document.getElementById(), React lets you describe what the UI should look like for a given state.`,
          whyItMatters: `React is the most widely used frontend technology in the world, powering web applications for Meta, Airbnb, Uber, and Netflix.`,
          mainExample: {
            title: "Functional Component with State",
            language: "javascript",
            code: `function CounterApp() {\n  const [count, setCount] = React.useState(0);\n  return (\n    <div className="card">\n      <h2>Interactive Counter</h2>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>Increment</button>\n    </div>\n  );\n}`,
            executable: true,
            explanation: ["useState(0) initializes reactive state.", "React re-renders when setCount runs."],
          },
          detailedExplanation: ["React uses a lightweight in-memory Virtual DOM to compute minimal DOM mutations."],
          commonMistakes: [],
          bestPractices: ["Keep components small, focused, and single-purpose."],
          summary: ["React enables declarative, modular user interface development."],
        },
      ],
    },
    {
      id: "mod-react-2",
      slug: "jsx",
      title: "Module 2: JSX Syntax & Element Trees",
      description: "JSX expressions, fragment containers (<>...</>), conditional rendering, and list mapping with keys.",
      lessons: [
        {
          id: "react-jsx",
          slug: "jsx-and-conditional-rendering",
          courseSlug: "react",
          moduleSlug: "jsx",
          title: "JSX Rules, Keys & Conditional Rendering",
          description: "Master JSX expressions, fragment syntax, conditional rendering with && / ternary, and unique list keys.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Embedding JavaScript expressions with curly braces {expr}",
            "Conditional UI rendering with ternary (condition ? A : B) and short-circuit (flag && UI)",
            "Why unique 'key' props are mandatory for array rendering (.map())",
          ],
          introduction: `JSX (JavaScript XML) is a syntax extension for JavaScript that lets you write HTML-like markup directly inside JavaScript files.`,
          whyItMatters: `Using stable unique keys on list items allows React's reconciliation engine to reorder DOM nodes without re-mounting the entire list.`,
          mainExample: {
            title: "List Rendering with Unique Keys",
            language: "javascript",
            code: `function TechList({ technologies }) {\n  return (\n    <ul>\n      {technologies.map(tech => (\n        <li key={tech.id} className="tech-item">\n          <strong>{tech.name}</strong> - {tech.category}\n        </li>\n      ))}\n    </ul>\n  );\n}`,
            executable: false,
            explanation: ["key={tech.id} uniquely identifies each element across re-renders."],
          },
          detailedExplanation: ["Never use array indices (index) as keys if list items can be reordered or filtered."],
          commonMistakes: [],
          bestPractices: ["Always use unique database IDs for key props."],
          summary: ["JSX combines the expressiveness of JavaScript with declarative markup."],
        },
      ],
    },
    {
      id: "mod-react-3",
      slug: "components-props",
      title: "Module 3: Components, Props & Composition",
      description: "Props destructuring, default props, children prop, and component composition patterns.",
      lessons: [
        {
          id: "react-props",
          slug: "props-and-composition",
          courseSlug: "react",
          moduleSlug: "components-props",
          title: "Component Props & Composition (children)",
          description: "Pass data down the component tree via immutable props and leverage the 'children' prop for slots.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Passing and destructuring immutable props",
            "Using the 'children' prop for flexible layout containers",
            "Component composition vs prop drilling",
          ],
          introduction: `Props (short for properties) are the mechanism by which parent components pass data down to child components in a unidirectional data flow.`,
          whyItMatters: `Composition using children allows you to create flexible card and modal wrappers without hardcoding internal content.`,
          mainExample: {
            title: "Card Container with Children Prop",
            language: "javascript",
            code: `function Card({ title, children }) {\n  return (\n    <div className="card-box">\n      <h3 className="card-header">{title}</h3>\n      <div className="card-content">{children}</div>\n    </div>\n  );\n}`,
            executable: false,
            explanation: ["children renders whatever nested JSX is passed between <Card>...</Card>."],
          },
          detailedExplanation: ["Props are read-only; components must never modify their own props directly."],
          commonMistakes: [],
          bestPractices: ["Prefer composition with children over passing large config objects."],
          summary: ["Props enable modular, reusable component hierarchies."],
        },
      ],
    },
    {
      id: "mod-react-4",
      slug: "state",
      title: "Module 4: Reactive State & useState Hook",
      description: "Managing local component state, updater functions, and immutable object/array updates.",
      lessons: [
        {
          id: "react-usestate",
          slug: "usestate-and-immutability",
          courseSlug: "react",
          moduleSlug: "state",
          title: "useState & Functional State Updaters",
          description: "Update component state immutably and use functional updaters (prev => prev + 1) for batched updates.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Declaring state with const [state, setState] = useState(initial)",
            "Why state updates are asynchronous and batched in React",
            "Using functional updater callbacks to avoid stale state bugs",
          ],
          introduction: `State represents the dynamic data in a component that can change over time based on user interactions, network responses, or timers.`,
          whyItMatters: `Using functional updaters (setCount(prev => prev + 1)) ensures state updates calculate from the freshest value even during rapid clicks.`,
          mainExample: {
            title: "Safe Functional State Updates",
            language: "javascript",
            code: `function StepCounter() {\n  const [step, setStep] = React.useState(1);\n\n  const advanceSteps = () => {\n    // Functional updates prevent stale closures\n    setStep(prev => prev + 1);\n    setStep(prev => prev + 1);\n  };\n\n  return <button onClick={advanceSteps}>Step: {step}</button>;\n}`,
            executable: true,
            explanation: ["Functional updaters queue sequential updates deterministically."],
          },
          detailedExplanation: ["Always create new copies when updating arrays or objects in state."],
          commonMistakes: [],
          bestPractices: ["Group related state into a single object or custom hook."],
          summary: ["useState manages local reactive component memory."],
        },
      ],
    },
    {
      id: "mod-react-5",
      slug: "effects-lifecycle",
      title: "Module 5: Component Lifecycle & useEffect Hook",
      description: "Side effects, dependency array mechanics, cleanup functions, and data fetching.",
      lessons: [
        {
          id: "react-effects",
          slug: "hooks-and-lifecycle",
          courseSlug: "react",
          moduleSlug: "effects-lifecycle",
          title: "useEffect, Dependencies & Cleanup Handlers",
          description: "Synchronize components with external systems, manage dependencies, and prevent memory leaks with cleanup handlers.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "How useEffect synchronizes with external APIs, timers, and WebSockets",
            "The 3 dependency array cases: no array, empty array [], and with deps [id]",
            "Writing cleanup return functions to cancel timers and subscriptions",
          ],
          introduction: `useEffect allows you to perform side effects in functional components. Side effects include data fetching, manual DOM mutations, timers, and logging.`,
          whyItMatters: `Failing to clean up event listeners or intervals in useEffect causes memory leaks and performance degradation.`,
          mainExample: {
            title: "useEffect with Timer Cleanup",
            language: "javascript",
            code: `function Clock() {\n  const [seconds, setSeconds] = React.useState(0);\n\n  React.useEffect(() => {\n    const id = setInterval(() => setSeconds(s => s + 1), 1000);\n    // Cleanup on unmount\n    return () => clearInterval(id);\n  }, []);\n\n  return <span>Active Seconds: {seconds}</span>;\n}`,
            executable: true,
            explanation: ["clearInterval runs when component unmounts."],
          },
          detailedExplanation: ["Any variable from component scope used inside the effect must be declared in dependencies."],
          commonMistakes: [],
          bestPractices: ["Always return a cleanup function when creating intervals or event listeners."],
          summary: ["useEffect orchestrates lifecycle synchronization and external side effects."],
        },
      ],
    },
    {
      id: "mod-react-6",
      slug: "performance",
      title: "Module 6: Performance Optimization (useMemo, useCallback, memo)",
      description: "Preventing unnecessary re-renders with React.memo, useMemo, and useCallback.",
      lessons: [
        {
          id: "react-performance",
          slug: "usememo-and-usecallback",
          courseSlug: "react",
          moduleSlug: "performance",
          title: "Memoization with useMemo, useCallback & React.memo",
          description: "Cache expensive computations and stabilize function references to prevent unnecessary child re-renders.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "useMemo to cache expensive mathematical or filtering calculations",
            "useCallback to maintain stable function references between renders",
            "React.memo for shallow prop comparison on child components",
          ],
          introduction: `React re-renders a component and all its children whenever state or props change. Memoization hooks cache calculations and function references to bypass redundant work.`,
          whyItMatters: `Filtering 10,000 items on every keystroke causes perceptible UI lag. useMemo ensures the filter runs only when the dataset or query changes.`,
          mainExample: {
            title: "useMemo & useCallback Integration",
            language: "javascript",
            code: `function FilterList({ items, filterQuery }) {\n  // Cached computation\n  const filtered = React.useMemo(() => {\n    return items.filter(i => i.title.toLowerCase().includes(filterQuery.toLowerCase()));\n  }, [items, filterQuery]);\n\n  // Stable function reference\n  const handleDelete = React.useCallback((id) => {\n    console.log("Delete item:", id);\n  }, []);\n\n  return <div>Filtered Count: {filtered.length}</div>;\n}`,
            executable: false,
            explanation: ["useMemo caches the filtered array; useCallback caches the handleDelete function."],
          },
          detailedExplanation: ["Do not overuse memoization for trivial computations, as hook overhead can exceed the cost of re-rendering."],
          commonMistakes: [],
          bestPractices: ["Measure performance with React Profiler before applying memoization."],
          summary: ["Targeted memoization prevents UI lag in complex data-heavy components."],
        },
      ],
    },
    {
      id: "mod-react-7",
      slug: "refs",
      title: "Module 7: Refs & DOM Manipulation (useRef)",
      description: "Holding mutable values without re-rendering and referencing DOM elements.",
      lessons: [
        {
          id: "react-refs",
          slug: "useref-and-dom-access",
          courseSlug: "react",
          moduleSlug: "refs",
          title: "useRef & Imperative DOM Access",
          description: "Access browser DOM elements directly (focus, scroll, measurement) and store mutable values without triggering re-renders.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Creating ref containers with const ref = useRef(initial)",
            "Focusing inputs and measuring bounding rectangles imperatively",
            "Storing previous values and timer IDs across renders",
          ],
          introduction: `useRef returns a mutable ref object whose .current property is initialized to the passed argument. Mutating .current does NOT trigger a component re-render.`,
          whyItMatters: `useRef is the standard React escape hatch for focusing inputs, triggering animations, or integrating third-party canvas libraries.`,
          mainExample: {
            title: "Auto-Focus Input with useRef",
            language: "javascript",
            code: `function SearchInput() {\n  const inputRef = React.useRef(null);\n\n  const handleFocus = () => {\n    inputRef.current?.focus();\n  };\n\n  return (\n    <div>\n      <input ref={inputRef} placeholder="Search documentation..." />\n      <button onClick={handleFocus}>Focus Search (Ctrl+K)</button>\n    </div>\n  );\n}`,
            executable: false,
            explanation: ["inputRef.current holds the direct DOM input node."],
          },
          detailedExplanation: ["Unlike useState, changing a ref value does not cause React to re-execute the component."],
          commonMistakes: [],
          bestPractices: ["Do not read or write ref.current during rendering; use refs only inside event handlers or effects."],
          summary: ["useRef bridges declarative React with imperative DOM manipulation."],
        },
      ],
    },
    {
      id: "mod-react-8",
      slug: "context-state",
      title: "Module 8: Global State Management & Context API",
      description: "Sharing global state across deeply nested components without prop drilling.",
      lessons: [
        {
          id: "react-context",
          slug: "context-api-and-global-state",
          courseSlug: "react",
          moduleSlug: "context-state",
          title: "Context API (createContext & useContext)",
          description: "Broadcast global state (theme, authentication, preferences) down the component tree without prop drilling.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Creating context with createContext() and consuming with useContext()",
            "Wrapping component trees in <ThemeContext.Provider value={...}>",
            "Preventing context re-render cascades with custom provider components",
          ],
          introduction: `The Context API provides a way to pass data through the component tree without having to pass props down manually at every single intermediate level.`,
          whyItMatters: `Context solves prop drilling for universal application data such as logged-in user sessions, themes, and notification toasts.`,
          mainExample: {
            title: "Theme Context Provider & Hook",
            language: "javascript",
            code: `const ThemeContext = React.createContext("light");\n\nfunction App() {\n  return (\n    <ThemeContext.Provider value="dark">\n      <Toolbar />\n    </ThemeContext.Provider>\n  );\n}\n\nfunction Toolbar() {\n  const theme = React.useContext(ThemeContext);\n  return <div>Active Global Theme: {theme}</div>;\n}`,
            executable: true,
            explanation: ["useContext(ThemeContext) reads the value from the nearest Provider above in the tree."],
          },
          detailedExplanation: ["Split frequently changing state into separate context providers to isolate re-renders."],
          commonMistakes: [],
          bestPractices: ["Create custom wrapper hooks like useTheme() rather than exporting the raw context object."],
          summary: ["Context API provides effortless global data broadcasting across component trees."],
        },
      ],
    },
    {
      id: "mod-react-9",
      slug: "custom-hooks",
      title: "Module 9: Custom Hooks & Logic Reusability",
      description: "Extracting stateful logic into reusable use* functions across multiple components.",
      lessons: [
        {
          id: "react-custom-hooks",
          slug: "authoring-custom-hooks",
          courseSlug: "react",
          moduleSlug: "custom-hooks",
          title: "Building Custom React Hooks (useLocalStorage, useFetch)",
          description: "Extract and package reusable stateful logic into standalone custom hooks with clean declarative APIs.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Rules of Custom Hooks: must start with 'use' prefix",
            "Composing built-in hooks (useState, useEffect) into domain-specific helpers",
            "Building useLocalStorage and useDebounce custom hooks",
          ],
          introduction: `Custom Hooks are JavaScript functions whose names start with 'use' and that may call other Hooks. They let you extract component logic into reusable functions.`,
          whyItMatters: `Instead of duplicating 15 lines of debouncing or local storage sync across 8 forms, you encapsulate the logic in a single reusable custom hook.`,
          mainExample: {
            title: "useDebounce Custom Hook",
            language: "javascript",
            code: `function useDebounce(value, delay = 300) {\n  const [debounced, setDebounced] = React.useState(value);\n\n  React.useEffect(() => {\n    const timer = setTimeout(() => setDebounced(value), delay);\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n\n  return debounced;\n}`,
            executable: false,
            explanation: ["useDebounce waits until the user pauses typing before updating the debounced value."],
          },
          detailedExplanation: ["Custom hooks do not share state values between components; each invocation creates isolated state."],
          commonMistakes: [],
          bestPractices: ["Keep custom hooks focused on a single reusable stateful responsibility."],
          summary: ["Custom hooks are the premier pattern for code reuse and logic modularity in React."],
        },
      ],
    },
    {
      id: "mod-react-10",
      slug: "forms",
      title: "Module 10: Forms & Controlled vs Uncontrolled Inputs",
      description: "Controlled components, form submission, React Hook Form, and validation schemas.",
      lessons: [
        {
          id: "react-forms",
          slug: "controlled-vs-uncontrolled-forms",
          courseSlug: "react",
          moduleSlug: "forms",
          title: "Controlled vs Uncontrolled Forms & Validation",
          description: "Manage form inputs with controlled state, handle complex forms, and validate inputs before submission.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Controlled inputs (value + onChange state sync)",
            "Uncontrolled inputs with FormData and defaultValue",
            "Form validation and preventing default submission reloads",
          ],
          introduction: `In React, form inputs can be Controlled (React state drives the input value) or Uncontrolled (DOM manages its own state and reads values on submit).`,
          whyItMatters: `Controlled inputs enable instant character validation, masked formatting (e.g. credit card spacing), and dynamic submit button disabling.`,
          mainExample: {
            title: "Controlled Form Component",
            language: "javascript",
            code: `function ContactForm() {\n  const [email, setEmail] = React.useState("");\n\n  const handleSubmit = (e) => {\n    e.preventDefault();\n    console.log("Submitting:", email);\n  };\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input\n        value={email}\n        onChange={(e) => setEmail(e.target.value)}\n        placeholder="name@example.com"\n      />\n      <button type="submit" disabled={!email.includes("@")}>Submit</button>\n    </form>\n  );\n}`,
            executable: false,
            explanation: ["value and onChange keep the input locked to React state."],
          },
          detailedExplanation: ["e.preventDefault() stops the browser from triggering a full page refresh on submit."],
          commonMistakes: [],
          bestPractices: ["Use uncontrolled inputs with FormData for simple high-performance forms with many fields."],
          summary: ["React provides full control over form validation, masking, and submission."],
        },
      ],
    },
    {
      id: "mod-react-11",
      slug: "react-advanced",
      title: "Module 11: Error Boundaries & React 19 Actions",
      description: "Component error boundaries, useActionState, useOptimistic, and transition states.",
      lessons: [
        {
          id: "react-error-boundaries",
          slug: "error-boundaries-and-actions",
          courseSlug: "react",
          moduleSlug: "react-advanced",
          title: "Error Boundaries & React 19 Actions (useActionState)",
          description: "Catch unexpected rendering crashes with Error Boundaries and handle async form actions with React 19 hooks.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Catching JavaScript render crashes using componentDidCatch Error Boundaries",
            "Graceful fallback error screens for users",
            "Modern React 19 useActionState and useOptimistic patterns",
          ],
          introduction: `Error Boundaries are React components that catch JavaScript errors anywhere in their child component tree, log those errors, and display a fallback UI instead of crashing the entire app.`,
          whyItMatters: `A runtime error in one isolated widget should never crash the entire page for the user.`,
          mainExample: {
            title: "Error Boundary Fallback UI",
            language: "javascript",
            code: `class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  static getDerivedStateFromError() { return { hasError: true }; }\n  componentDidCatch(error) { console.error("Caught crash:", error); }\n  render() {\n    if (this.state.hasError) {\n      return <div className="alert-box">Something went wrong. Please refresh.</div>;\n    }\n    return this.props.children;\n  }\n}`,
            executable: false,
            explanation: ["getDerivedStateFromError renders the fallback alert when an unhandled error occurs."],
          },
          detailedExplanation: ["Error boundaries catch errors during rendering, lifecycle methods, and constructors of child components."],
          commonMistakes: [],
          bestPractices: ["Wrap independent features (like sidebar, main content, comments) in separate Error Boundaries."],
          summary: ["Error boundaries guarantee enterprise resilience against unexpected client crashes."],
        },
      ],
    },
  ],
};
