import { Course } from "@/types";

export const rustCourse: Course = {
  id: "course-rust",
  slug: "rust",
  title: "Rust Systems & Memory Safety Mastery",
  tagline: "Memory safety without garbage collection — master Ownership, Borrowing, Lifetimes, and Traits.",
  description: "Master Rust: the Ownership model, mutable and immutable borrowing (&, &mut), lifetimes ('a), Pattern Matching, Enums with data (Option, Result), Traits, Cargo package management, and fearlessly concurrent systems programming.",
  category: "Programming Languages",
  level: "Advanced",
  estimatedHours: 30,
  icon: "Shield",
  badgeColor: "amber",
  prerequisites: ["Programming Experience"],
  skillsGained: [
    "The Ownership & Move Semantics System",
    "Borrow Checker Mechanics (References & Mutability)",
    "Pattern Matching & Robust Error Handling (Result<T, E>)",
    "Traits & Generic Type Constraints",
    "Fearless Concurrency & Zero-Cost Abstractions",
  ],
  featured: false,
  modules: [
    {
      id: "mod-rust-1",
      slug: "intro",
      title: "Module 1: Rust Philosophy & Cargo Toolchain",
      description: "Why Rust, Cargo package manager (cargo build, cargo test), and main.rs.",
      lessons: [
        {
          id: "rust-intro",
          slug: "rust-introduction",
          courseSlug: "rust",
          moduleSlug: "intro",
          title: "Rust Introduction & The Cargo Toolchain",
          description: "Discover why Rust achieves memory safety without a garbage collector and how Cargo manages builds.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Why memory safety without garbage collection is revolutionary",
            "Managing packages, dependencies, and testing with Cargo",
            "The fn main() entry point and println! macro",
          ],
          introduction: `Rust is a systems programming language focused on safety, speed, and concurrency. It achieves memory safety at compile time without a runtime garbage collector.`,
          whyItMatters: `Over 70% of security vulnerabilities in C/C++ are memory safety bugs (buffer overflows, use-after-free). Rust mathematically eliminates these at compile time.`,
          mainExample: {
            title: "Hello World in Rust",
            language: "rust",
            code: `fn main() {\n    println!("KWAS Academy: Safe Systems Programming with Rust");\n}`,
            executable: true,
            explanation: ["println! is a macro that enforces format string type safety at compile time."],
          },
          detailedExplanation: ["Cargo is Rust's unified build tool, dependency manager, test runner, and documentation generator."],
          commonMistakes: [],
          bestPractices: ["Always format code with 'cargo fmt' and lint with 'cargo clippy'."],
          summary: ["Rust provides C++ speed with total memory safety."],
        },
      ],
    },
    {
      id: "mod-rust-2",
      slug: "variables-mutability",
      title: "Module 2: Variables, Mutability & Shadowing",
      description: "Immutable by default (let), explicit mutability (let mut), constants, and variable shadowing.",
      lessons: [
        {
          id: "rust-mutability",
          slug: "immutability-and-shadowing",
          courseSlug: "rust",
          moduleSlug: "variables-mutability",
          title: "Immutability by Default & Variable Shadowing",
          description: "Understand why variables in Rust are immutable by default and how variable shadowing enables safe transformations.",
          durationMinutes: 14,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Why Rust defaults to immutable variables (let x = 5)",
            "Explicit mutability with 'let mut'",
            "Reusing variable names and changing types with Variable Shadowing",
          ],
          introduction: `In Rust, variables are immutable by default. This is one of many nudges Rust gives you to write code in a way that takes advantage of the safety and easy concurrency that Rust offers.`,
          whyItMatters: `Default immutability prevents accidental mutations across complex concurrent threads.`,
          mainExample: {
            title: "Variable Shadowing & Mutability",
            language: "rust",
            code: `fn main() {\n    // Mutable variable\n    let mut score = 100;\n    score += 50;\n\n    // Variable Shadowing (transforms type safely)\n    let spaces = "   ";\n    let spaces = spaces.len(); // spaces is now usize: 3\n    println!("Score: {}, Spaces count: {}", score, spaces);\n}`,
            executable: true,
            explanation: ["Shadowing with 'let spaces' creates a new variable, allowing the type to change safely."],
          },
          detailedExplanation: ["Constants (const MAX: u32 = 100) must be annotated with explicit types and evaluated at compile time."],
          commonMistakes: [],
          bestPractices: ["Prefer variable shadowing over making variables mutable whenever transforming data."],
          summary: ["Immutability and shadowing ensure deterministic state transitions."],
        },
      ],
    },
    {
      id: "mod-rust-3",
      slug: "ownership",
      title: "Module 3: The Ownership Model & Move Semantics",
      description: "The 3 Ownership rules, stack vs heap data, and the drop function.",
      lessons: [
        {
          id: "rust-ownership",
          slug: "ownership-and-move-semantics",
          courseSlug: "rust",
          moduleSlug: "ownership",
          title: "The 3 Ownership Rules & Move Semantics",
          description: "Master Rust's core breakthrough: Ownership rules, move semantics on heap data, and automatic Drop.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The 3 laws of Rust Ownership",
            "How ownership transfers (Move semantics) prevent double-free bugs",
            "Automatic memory deallocation when owners go out of scope (Drop trait)",
          ],
          introduction: `Ownership is Rust's most unique feature. It enables Rust to make memory safety guarantees without needing a garbage collector.`,
          whyItMatters: `Rule 1: Each value in Rust has an owner. Rule 2: There can only be one owner at a time. Rule 3: When the owner goes out of scope, the value is dropped.`,
          mainExample: {
            title: "Ownership Move Semantics",
            language: "rust",
            code: `fn main() {\n    let s1 = String::from("KWAS Academy");\n    let s2 = s1; // Ownership MOVED to s2. s1 is no longer valid!\n\n    println!("s2: {}", s2);\n    // println!("s1: {}", s1); // Compile Error: value borrowed here after move!\n}`,
            executable: true,
            explanation: ["Transferring pointer ownership prevents duplicate freeing of heap memory."],
          },
          detailedExplanation: ["Stack-only types (like integers and floats) implement the Copy trait and are copied rather than moved."],
          commonMistakes: [],
          bestPractices: ["Embrace move semantics; use .clone() only when an explicit deep heap copy is truly required."],
          summary: ["Ownership rules eliminate use-after-free and double-free bugs at compile time."],
        },
      ],
    },
    {
      id: "mod-rust-4",
      slug: "borrowing",
      title: "Module 4: Borrowing & References (&T and &mut T)",
      description: "The Borrow Checker, immutable borrows (&T), mutable borrows (&mut T), and data race prevention.",
      lessons: [
        {
          id: "rust-borrowing",
          slug: "references-and-borrowing-rules",
          courseSlug: "rust",
          moduleSlug: "borrowing",
          title: "References, Borrowing & The Borrow Checker",
          description: "Pass data without transferring ownership using references (&), and learn the golden rule of the borrow checker.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Borrowing data with immutable references (&String)",
            "Exclusive mutable borrowing (&mut String)",
            "The Golden Borrow Rule: Either 1 mutable reference OR any number of immutable references",
          ],
          introduction: `Instead of transferring ownership, Rust allows functions to 'borrow' access to data via references without taking ownership.`,
          whyItMatters: `The borrow checker rules mathematically prevent data races: two threads cannot mutate the same memory location simultaneously.`,
          mainExample: {
            title: "Immutable & Mutable Borrowing",
            language: "rust",
            code: `fn calculate_length(s: &String) -> usize {\n    s.len() // Borrowed reference\n}\n\nfn append_badge(s: &mut String) {\n    s.push_str(" [PRO]");\n}\n\nfn main() {\n    let mut name = String::from("Alex Developer");\n    println!("Length: {}", calculate_length(&name));\n    append_badge(&mut name);\n    println!("Updated: {}", name);\n}`,
            executable: true,
            explanation: ["&name borrows immutably; &mut name borrows mutably."],
          },
          detailedExplanation: ["You cannot have a mutable reference while immutable references are still in active use."],
          commonMistakes: [],
          bestPractices: ["Keep mutable borrow scopes as narrow as possible."],
          summary: ["Borrowing enables high-performance zero-copy memory access with compile-time safety."],
        },
      ],
    },
    {
      id: "mod-rust-5",
      slug: "slices",
      title: "Module 5: Slices & Memory Layout",
      description: "String slices (&str), array slices (&[T]), and contiguous view references.",
      lessons: [
        {
          id: "rust-slices",
          slug: "string-and-array-slices",
          courseSlug: "rust",
          moduleSlug: "slices",
          title: "Slices (&str, &[T]) & Memory Safety",
          description: "Reference contiguous sub-sequences of collections with zero memory allocation using string and array slices.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "What a slice is: a pointer to starting element + length",
            "String slices (&str) vs heap-allocated String",
            "Array slices (&[i32]) for generic contiguous sub-views",
          ],
          introduction: `A slice is a reference to a contiguous sequence of elements in a collection rather than the whole collection.`,
          whyItMatters: `String slices (&str) allow functions to accept both String and literal strings without performing heap allocations.`,
          mainExample: {
            title: "First Word Extractor with String Slice",
            language: "rust",
            code: `fn first_word(s: &str) -> &str {\n    let bytes = s.as_bytes();\n    for (i, &item) in bytes.iter().enumerate() {\n        if item == b' ' {\n            return &s[0..i];\n        }\n    }\n    &s[..]\n}\n\nfn main() {\n    let greeting = "Hello World";\n    println!("First word: {}", first_word(greeting));\n}`,
            executable: true,
            explanation: ["&s[0..i] returns a slice view pointing directly into original string bytes."],
          },
          detailedExplanation: ["Slices prevent index-out-of-sync bugs because the borrow checker links the slice lifetime to the underlying data."],
          commonMistakes: [],
          bestPractices: ["Always use &str for function input arguments instead of &String."],
          summary: ["Slices provide zero-cost views into contiguous memory segments."],
        },
      ],
    },
    {
      id: "mod-rust-6",
      slug: "structs",
      title: "Module 6: Structs & Methods",
      description: "Classic structs, tuple structs, impl blocks, and associated functions (Self::new).",
      lessons: [
        {
          id: "rust-structs",
          slug: "structs-and-impl-methods",
          courseSlug: "rust",
          moduleSlug: "structs",
          title: "Structs, Impl Blocks & Associated Functions",
          description: "Define custom domain records with structs and attach methods and constructors via 'impl' blocks.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Defining named-field structs and tuple structs",
            "Method receivers: &self (borrow), &mut self (mutate), self (consume)",
            "Associated constructor functions (Self::new)",
          ],
          introduction: `Structs are custom data types that let you package together and name multiple related values into a meaningful group.`,
          whyItMatters: `Attaching methods via 'impl' blocks cleanly separates data definition from behavioral algorithms.`,
          mainExample: {
            title: "Rectangle Struct with Method Implementation",
            language: "rust",
            code: `#[derive(Debug)]\nstruct Rectangle {\n    width: u32,\n    height: u32,\n}\n\nimpl Rectangle {\n    fn new(w: u32, h: u32) -> Self {\n        Self { width: w, height: h }\n    }\n    fn area(&self) -> u32 {\n        self.width * self.height\n    }\n}\n\nfn main() {\n    let rect = Rectangle::new(30, 50);\n    println!("Rect: {:?} | Area: {}", rect, rect.area());\n}`,
            executable: true,
            explanation: ["#[derive(Debug)] allows printing structs with {:?}."],
          },
          detailedExplanation: ["Associated functions without &self act like static factory methods in other languages."],
          commonMistakes: [],
          bestPractices: ["Always provide a new() associated constructor function for complex structs."],
          summary: ["Structs and impl blocks structure data and behavior cleanly."],
        },
      ],
    },
    {
      id: "mod-rust-7",
      slug: "enums-matching",
      title: "Module 7: Enums, Pattern Matching & Option",
      description: "Enums with payload data, the Option<T> type (no nulls), and match expressions.",
      lessons: [
        {
          id: "rust-enums",
          slug: "enums-pattern-matching-and-option",
          courseSlug: "rust",
          moduleSlug: "enums-matching",
          title: "Enums with Data, Pattern Matching & Option<T>",
          description: "Eliminate null pointer bugs using Option<T> (Some/None) and exhaustive 'match' expressions.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Enums that hold arbitrary payload data in each variant",
            "Why Rust has NO null primitive (uses Option<T> instead)",
            "Exhaustive pattern matching with the 'match' keyword",
          ],
          introduction: `Rust enums are algebraic data types that can hold different types and amounts of data in each variant. The Option enum represents either Some(value) or None.`,
          whyItMatters: `Tony Hoare called null his 'billion-dollar mistake'. Option<T> forces you to explicitly handle the None case at compile time.`,
          mainExample: {
            title: "Option Pattern Matching",
            language: "rust",
            code: `fn divide(numerator: f64, denominator: f64) -> Option<f64> {\n    if denominator == 0.0 { None } else { Some(numerator / denominator) }\n}\n\nfn main() {\n    match divide(10.0, 2.0) {\n        Some(result) => println!("Quotient: {}", result),\n        None => println!("Cannot divide by zero!"),\n    }\n}`,
            executable: true,
            explanation: ["match must cover all possible enum variants exhaustively."],
          },
          detailedExplanation: ["Use 'if let Some(val) = opt' when you only care about matching a single variant."],
          commonMistakes: [],
          bestPractices: ["Use Option<T> for any value that might be absent."],
          summary: ["Enums and Option eliminate null pointer crashes entirely."],
        },
      ],
    },
    {
      id: "mod-rust-8",
      slug: "error-handling",
      title: "Module 8: Error Handling with Result<T, E>",
      description: "Recoverable errors with Result<T, E>, unrecoverable panic!, and the '?' question mark operator.",
      lessons: [
        {
          id: "rust-result",
          slug: "result-and-question-mark-operator",
          courseSlug: "rust",
          moduleSlug: "error-handling",
          title: "Result<T, E> & The '?' Error Propagation Operator",
          description: "Handle recoverable errors gracefully with Result and propagate errors with the '?' operator.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The Result<T, E> enum (Ok(T) vs Err(E))",
            "Propagating errors effortlessly with the '?' operator",
            "Mapping and chaining errors with .map_err() and thiserror/anyhow",
          ],
          introduction: `Rust distinguishes between recoverable errors (using Result<T, E>) and unrecoverable errors (which call the panic! macro).`,
          whyItMatters: `The '?' operator returns the Err early from the current function if an error occurs, eliminating 5 lines of boilerplate per call.`,
          mainExample: {
            title: "Error Propagation with '?' Operator",
            language: "rust",
            code: `fn parse_port(port_str: &str) -> Result<u16, std::num::ParseIntError> {\n    let port: u16 = port_str.parse()?;\n    Ok(port)\n}\n\nfn main() {\n    match parse_port("8080") {\n        Ok(port) => println!("Server listening on port: {}", port),\n        Err(e) => println!("Invalid port: {}", e),\n    }\n}`,
            executable: true,
            explanation: ["'?' extracts the Ok value or returns the Err immediately from parse_port."],
          },
          detailedExplanation: ["Unwrap (.unwrap()) should only be used in quick prototypes or unit tests."],
          commonMistakes: [],
          bestPractices: ["Always return Result<T, E> from functions that perform I/O or parsing."],
          summary: ["Result and the '?' operator make robust error handling ergonomic."],
        },
      ],
    },
    {
      id: "mod-rust-9",
      slug: "traits-generics",
      title: "Module 9: Traits & Generics",
      description: "Defining traits, implementing traits for types, trait bounds (impl Trait), and derive macros.",
      lessons: [
        {
          id: "rust-traits",
          slug: "traits-and-trait-bounds",
          courseSlug: "rust",
          moduleSlug: "traits-generics",
          title: "Traits & Generic Trait Bounds (impl Trait)",
          description: "Define shared behavior interfaces with Traits and constrain generic functions with Trait Bounds.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Defining traits and implementing them on structs",
            "Constraining generic functions with trait bounds (T: Summary + Display)",
            "Default trait method implementations",
          ],
          introduction: `A trait defines functionality a particular type has and can share with other types. Traits are similar to interfaces in other languages, but with zero-cost static dispatch.`,
          whyItMatters: `Rust generates specialized monomorphized code for generic trait calls, executing with zero virtual method dispatch overhead.`,
          mainExample: {
            title: "Summary Trait Implementation",
            language: "rust",
            code: `trait Summary {\n    fn summarize(&self) -> String;\n}\n\nstruct Course {\n    title: String,\n}\n\nimpl Summary for Course {\n    fn summarize(&self) -> String {\n        format!("Course: {}", self.title)\n    }\n}\n\nfn main() {\n    let c = Course { title: String::from("Rust Mastery") };\n    println!("{}", c.summarize());\n}`,
            executable: true,
            explanation: ["impl Summary for Course provides the trait implementation."],
          },
          detailedExplanation: ["Traits can also be used for dynamic dispatch via Trait Objects (dyn Trait)."],
          commonMistakes: [],
          bestPractices: ["Derive standard traits (Debug, Clone, PartialEq) whenever possible."],
          summary: ["Traits define shared capabilities with zero runtime cost."],
        },
      ],
    },
    {
      id: "mod-rust-10",
      slug: "lifetimes",
      title: "Module 10: Lifetimes ('a) & Memory Safety",
      description: "Lifetime annotations, the borrow checker's lifetime validation, and 'static lifetime.",
      lessons: [
        {
          id: "rust-lifetimes",
          slug: "lifetimes-and-borrow-checker",
          courseSlug: "rust",
          moduleSlug: "lifetimes",
          title: "Lifetime Annotations ('a) & Dangling Reference Prevention",
          description: "Learn how lifetime annotations inform the borrow checker about relationships between reference parameters.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Why lifetimes exist: to ensure references never outlive the data they point to",
            "Lifetime annotation syntax (&'a str)",
            "Lifetime elision rules and the 'static lifetime",
          ],
          introduction: `Lifetimes are another kind of generic that ensure references are valid as long as we need them to be. Every reference in Rust has a lifetime.`,
          whyItMatters: `Lifetime annotations do not change how long references live; they describe the relationship between lifetimes of multiple references so the compiler can prove safety.`,
          mainExample: {
            title: "Longest String with Lifetime Annotation",
            language: "rust",
            code: `fn longest<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}\n\nfn main() {\n    let s1 = "HTML5";\n    let s2 = "TypeScript";\n    let result = longest(s1, s2);\n    println!("Longest: {}", result);\n}`,
            executable: true,
            explanation: ["'a tells the compiler that the returned reference will be valid as long as both x and y are valid."],
          },
          detailedExplanation: ["The compiler automatically applies lifetime elision rules for common function patterns."],
          commonMistakes: [],
          bestPractices: ["Trust the borrow checker; annotate lifetimes only when returning borrowed references."],
          summary: ["Lifetimes prevent dangling pointer bugs at compile time."],
        },
      ],
    },
    {
      id: "mod-rust-11",
      slug: "concurrency",
      title: "Module 11: Fearless Concurrency & Smart Pointers (Box, Rc, Arc)",
      description: "Box<T>, Arc<T>, Mutex<T>, std::thread::spawn, and message-passing channels (mpsc).",
      lessons: [
        {
          id: "rust-concurrency",
          slug: "fearless-concurrency-and-arc-mutex",
          courseSlug: "rust",
          moduleSlug: "concurrency",
          title: "Fearless Concurrency with Arc, Mutex & Channels",
          description: "Share thread-safe state across threads with Arc<Mutex<T>> and send messages with mpsc channels.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Spawning threads with std::thread::spawn and move closures",
            "Message passing concurrency with mpsc (multiple producer, single consumer)",
            "Shared-state concurrency using Arc<Mutex<T>> (Atomic Reference Counted)",
          ],
          introduction: `Rust's type system and ownership rules guarantee Fearless Concurrency: multithreaded data races and race conditions fail to compile!`,
          whyItMatters: `Arc (Atomic Reference Counted) and Mutex guarantee thread-safe shared mutable access with zero chance of data corruption.`,
          mainExample: {
            title: "Thread-Safe Counter with Arc & Mutex",
            language: "rust",
            code: `use std::sync::{Arc, Mutex};\nuse std::thread;\n\nfn main() {\n    let counter = Arc::new(Mutex::new(0));\n    let mut handles = vec![];\n\n    for _ in 0..5 {\n        let counter_clone = Arc::clone(&counter);\n        let handle = thread::spawn(move || {\n            let mut num = counter_clone.lock().unwrap();\n            *num += 1;\n        });\n        handles.push(handle);\n    }\n\n    for handle in handles { handle.join().unwrap(); }\n    println!("Final Thread-Safe Count: {}", *counter.lock().unwrap());\n}`,
            executable: true,
            explanation: ["Arc::clone increments atomic reference count; Mutex locks memory safely."],
          },
          detailedExplanation: ["The Send and Sync marker traits guarantee at compile time which types are safe to transfer across thread boundaries."],
          commonMistakes: [],
          bestPractices: ["Prefer message passing with channels over shared memory mutex locks."],
          summary: ["Rust makes concurrent systems programming fearless and bug-free."],
        },
      ],
    },
  ],
};
