import { Course } from "@/types";

export const sqlCourse: Course = {
  id: "course-sql",
  slug: "sql",
  title: "SQL & Relational Database Engineering",
  tagline: "Master relational databases, complex queries, JOINs, indexing, transactions, and performance tuning.",
  description: "Comprehensive relational database engineering: schema design, SQL CRUD operations, INNER/LEFT/FULL JOINs, aggregations, subqueries, Common Table Expressions (CTEs), ACID transactions, B-Tree indexes, and query execution plans.",
  category: "Databases",
  level: "Beginner",
  estimatedHours: 24,
  icon: "Database",
  badgeColor: "purple",
  prerequisites: ["Basic data concept familiarity."],
  skillsGained: [
    "Relational Schema Modeling (PK/FK Constraints, Normalization)",
    "High-Performance SQL Queries (JOINs, GROUP BY, HAVING)",
    "Common Table Expressions (WITH queries) & Window Functions",
    "ACID Transactions & Concurrency Isolation Levels",
    "Indexing Strategies (B-Tree, Hash, GIN) & EXPLAIN ANALYZE",
  ],
  featured: true,
  modules: [
    {
      id: "mod-sql-1",
      slug: "intro",
      title: "Module 1: Relational Database Concepts & ACID",
      description: "RDBMS architecture, tables, columns, rows, primary keys, and ACID guarantees.",
      lessons: [
        {
          id: "sql-intro",
          slug: "sql-introduction",
          courseSlug: "sql",
          moduleSlug: "intro",
          title: "Relational Database Fundamentals & SQL",
          description: "Understand relational theory, tables, primary keys, foreign keys, and write foundational SELECT queries.",
          durationMinutes: 14,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "How RDBMS structures data into relational tables with primary keys",
            "Writing SELECT, WHERE, ORDER BY, and LIMIT clauses",
            "Why SELECT * should be avoided in production systems",
          ],
          introduction: `SQL (Structured Query Language) is the universal domain-specific language used to manage, query, and manipulate data stored in Relational Database Management Systems.`,
          whyItMatters: `Databases are the persistent source of truth for all enterprise web applications.`,
          mainExample: {
            title: "SELECT Query with Filter & Sort",
            language: "sql",
            code: `SELECT id, name, email, score\nFROM students\nWHERE score >= 80\nORDER BY score DESC\nLIMIT 5;`,
            executable: true,
            explanation: ["WHERE score >= 80 filters rows matching the condition."],
          },
          detailedExplanation: ["SQL execution lifecycle: FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY -> LIMIT."],
          commonMistakes: [],
          bestPractices: ["Always select explicit columns rather than SELECT *."],
          summary: ["SQL is the foundational query language for all backend engineering."],
        },
      ],
    },
    {
      id: "mod-sql-2",
      slug: "ddl",
      title: "Module 2: Data Definition (CREATE, ALTER, DROP) & Data Types",
      description: "Table schema creation, column data types (VARCHAR, UUID, TIMESTAMP), and constraints.",
      lessons: [
        {
          id: "sql-ddl",
          slug: "create-alter-drop-tables",
          courseSlug: "sql",
          moduleSlug: "ddl",
          title: "DDL: CREATE TABLE, Constraints & Data Types",
          description: "Define relational tables with PRIMARY KEY, FOREIGN KEY, NOT NULL, UNIQUE, and CHECK constraints.",
          durationMinutes: 16,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Choosing optimal data types (VARCHAR, INT, UUID, NUMERIC, TIMESTAMPTZ)",
            "Enforcing entity integrity with PRIMARY KEY and UNIQUE constraints",
            "Referential integrity with FOREIGN KEY ... REFERENCES ... ON DELETE CASCADE",
          ],
          introduction: `Data Definition Language (DDL) commands define and modify the schema structure of your relational database tables and indexes.`,
          whyItMatters: `Declaring strict constraints at the database level guarantees data integrity even if application code contains bugs.`,
          mainExample: {
            title: "CREATE TABLE with Relational Constraints",
            language: "sql",
            code: `CREATE TABLE users (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    email VARCHAR(255) NOT NULL UNIQUE,\n    age INT CHECK (age >= 13),\n    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP\n);`,
            executable: true,
            explanation: ["CHECK constraint ensures age is at least 13; UNIQUE prevents duplicate emails."],
          },
          detailedExplanation: ["ALTER TABLE allows adding or dropping columns on existing production tables."],
          commonMistakes: [],
          bestPractices: ["Always store dates with timezone (TIMESTAMPTZ)."],
          summary: ["DDL establishes the structural integrity rules of your database."],
        },
      ],
    },
    {
      id: "mod-sql-3",
      slug: "dml",
      title: "Module 3: Data Manipulation (INSERT, UPDATE, DELETE)",
      description: "Modifying records, batch insertions, UPSERT (ON CONFLICT), and DELETE safety.",
      lessons: [
        {
          id: "sql-dml",
          slug: "insert-update-delete-records",
          courseSlug: "sql",
          moduleSlug: "dml",
          title: "DML: INSERT, UPDATE, DELETE & UPSERT",
          description: "Insert rows, update specific records safely with WHERE, delete records, and handle duplicate collisions with UPSERT.",
          durationMinutes: 15,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Inserting single and multiple rows with INSERT INTO",
            "Safe updates with UPDATE ... SET ... WHERE id = ...",
            "Handling existing collisions with INSERT ... ON CONFLICT DO UPDATE (UPSERT)",
          ],
          introduction: `Data Manipulation Language (DML) commands allow you to insert, modify, and delete rows in your database tables.`,
          whyItMatters: `Running UPDATE or DELETE without a WHERE clause will accidentally overwrite or wipe all rows in the entire table!`,
          mainExample: {
            title: "Safe INSERT with RETURNING & UPSERT",
            language: "sql",
            code: `INSERT INTO users (id, email, age)\nVALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'alex@example.com', 25)\nON CONFLICT (email) DO UPDATE \nSET age = EXCLUDED.age\nRETURNING id, email, created_at;`,
            executable: true,
            explanation: ["ON CONFLICT updates the existing record if the email already exists."],
          },
          detailedExplanation: ["RETURNING clause returns newly mutated values instantly without a second query."],
          commonMistakes: [],
          bestPractices: ["Always double-check WHERE clauses before running UPDATE or DELETE queries."],
          summary: ["DML manages the lifecycle of data rows inside relational tables."],
        },
      ],
    },
    {
      id: "mod-sql-4",
      slug: "select-filtering",
      title: "Module 4: Querying Data with SELECT, WHERE & ORDER BY",
      description: "Filtering with AND/OR, LIKE/ILIKE, IN, BETWEEN, NULL handling (IS NULL), and pagination.",
      lessons: [
        {
          id: "sql-filtering",
          slug: "filtering-like-and-pagination",
          courseSlug: "sql",
          moduleSlug: "select-filtering",
          title: "Advanced WHERE Filters, Pattern Matching & Pagination",
          description: "Filter datasets using pattern matching (LIKE/ILIKE), NULL safety (IS NOT NULL), and implement OFFSET/LIMIT pagination.",
          durationMinutes: 16,
          difficulty: "Beginner",
          whatYouWillLearn: [
            "Pattern matching with LIKE '%text%' and case-insensitive ILIKE",
            "Handling three-valued logic with IS NULL and IS NOT NULL",
            "Keyset cursor pagination vs OFFSET/LIMIT pagination",
          ],
          introduction: `The SELECT statement retrieves rows matching precise filtering criteria and sorts them in ascending (ASC) or descending (DESC) order.`,
          whyItMatters: `In SQL, NULL = NULL is UNKNOWN (not true). You must use IS NULL to test for missing values.`,
          mainExample: {
            title: "Filtered Search with Pagination",
            language: "sql",
            code: `SELECT id, name, email, score\nFROM students\nWHERE email ILIKE '%@kwasacademy.dev'\n  AND score BETWEEN 80 AND 100\n  AND status IS NOT NULL\nORDER BY score DESC\nLIMIT 10 OFFSET 0;`,
            executable: true,
            explanation: ["ILIKE matches case-insensitively.", "BETWEEN filters inclusive ranges."],
          },
          detailedExplanation: ["High OFFSET values (e.g. OFFSET 100000) are slow; use cursor pagination on large tables."],
          commonMistakes: [],
          bestPractices: ["Use keyset cursor pagination (WHERE id > last_seen_id) for large datasets."],
          summary: ["SELECT and WHERE clauses extract precise subsets of data efficiently."],
        },
      ],
    },
    {
      id: "mod-sql-5",
      slug: "aggregations",
      title: "Module 5: Aggregate Functions & GROUP BY / HAVING",
      description: "COUNT, SUM, AVG, MIN, MAX, GROUP BY multi-column, and HAVING post-aggregation filters.",
      lessons: [
        {
          id: "sql-aggregates",
          slug: "group-by-and-aggregates",
          courseSlug: "sql",
          moduleSlug: "aggregations",
          title: "Aggregate Functions (COUNT, SUM, AVG) & HAVING",
          description: "Summarize data groups, calculate financial metrics, and filter aggregated groups with HAVING.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Summarizing metrics with COUNT(*), SUM(col), AVG(col), MIN, MAX",
            "Grouping rows by dimensions with GROUP BY",
            "Why HAVING filters groups while WHERE filters individual rows",
          ],
          introduction: `Aggregate functions calculate a single summary result from multiple input row values. GROUP BY groups rows that have the same values into summary rows.`,
          whyItMatters: `Aggregations drive executive dashboards, financial summaries, and business intelligence metrics.`,
          mainExample: {
            title: "Revenue by Region with HAVING Filter",
            language: "sql",
            code: `SELECT \n    region,\n    COUNT(order_id) AS total_orders,\n    SUM(amount) AS total_revenue,\n    ROUND(AVG(amount), 2) AS avg_order_value\nFROM orders\nWHERE status = 'COMPLETED'\nGROUP BY region\nHAVING SUM(amount) > 10000\nORDER BY total_revenue DESC;`,
            executable: true,
            explanation: ["HAVING filters regions whose total revenue exceeds 10,000."],
          },
          detailedExplanation: ["COUNT(*) counts all rows; COUNT(column) counts non-null values only."],
          commonMistakes: [],
          bestPractices: ["Every non-aggregated column in the SELECT list must appear in the GROUP BY clause."],
          summary: ["Aggregations and GROUP BY synthesize raw records into actionable insights."],
        },
      ],
    },
    {
      id: "mod-sql-6",
      slug: "joins",
      title: "Module 6: Relational JOINs (INNER, LEFT, RIGHT, FULL)",
      description: "Combining normalized tables, foreign key matching, self joins, and cross joins.",
      lessons: [
        {
          id: "sql-joins",
          slug: "joins-and-aggregations",
          courseSlug: "sql",
          moduleSlug: "joins",
          title: "Relational JOINs (INNER, LEFT, RIGHT, FULL)",
          description: "Combine related tables across primary and foreign key relationships with high-performance JOIN clauses.",
          durationMinutes: 20,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "INNER JOIN (matching rows in both tables)",
            "LEFT JOIN (all left rows + matching right rows)",
            "FULL OUTER JOIN and Self-referencing JOINs",
          ],
          introduction: `In normalized databases, data is split across tables (Users, Orders, Items). JOIN clauses re-combine these tables during query time based on shared key columns.`,
          whyItMatters: `Choosing between INNER JOIN and LEFT JOIN determines whether records with zero orders are included or excluded in reports.`,
          mainExample: {
            title: "Customer Orders with LEFT JOIN",
            language: "sql",
            code: `SELECT \n    c.customer_id,\n    c.customer_name,\n    COUNT(o.order_id) AS orders_placed\nFROM customers c\nLEFT JOIN orders o ON c.customer_id = o.customer_id\nGROUP BY c.customer_id, c.customer_name\nORDER BY orders_placed DESC;`,
            executable: true,
            explanation: ["LEFT JOIN keeps customers who have 0 orders in the result set."],
          },
          detailedExplanation: ["Always index foreign key columns to ensure JOIN operations run via index scans."],
          commonMistakes: [],
          bestPractices: ["Always use table aliases (c, o) to keep multi-table queries readable."],
          summary: ["JOINs unlock the full power of normalized relational data architectures."],
        },
      ],
    },
    {
      id: "mod-sql-7",
      slug: "subqueries-ctes",
      title: "Module 7: Subqueries & Common Table Expressions (CTEs)",
      description: "Subqueries in WHERE/FROM, correlated subqueries, and readable WITH clauses (CTEs).",
      lessons: [
        {
          id: "sql-ctes",
          slug: "ctes-and-subqueries",
          courseSlug: "sql",
          moduleSlug: "subqueries-ctes",
          title: "Common Table Expressions (WITH) & Subqueries",
          description: "Break down monolithic queries into readable, reusable CTE pipelines using the WITH statement.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Writing Common Table Expressions (WITH table_name AS (...))",
            "Correlated subqueries (WHERE EXISTS (...))",
            "Recursive CTEs for hierarchical organizational trees",
          ],
          introduction: `Common Table Expressions (CTEs) define temporary named result sets that exist within the scope of a single SELECT, INSERT, UPDATE, or DELETE statement.`,
          whyItMatters: `CTEs transform 100-line unreadable nested subquery monstrosities into clean, sequential, top-to-bottom data pipelines.`,
          mainExample: {
            title: "Multi-Step CTE Query",
            language: "sql",
            code: `WITH HighValueCustomers AS (\n    SELECT customer_id, SUM(amount) AS total_spent\n    FROM orders\n    GROUP BY customer_id\n    HAVING SUM(amount) > 1000\n)\nSELECT c.customer_name, c.email, h.total_spent\nFROM HighValueCustomers h\nINNER JOIN customers c ON c.customer_id = h.customer_id\nORDER BY h.total_spent DESC;`,
            executable: true,
            explanation: ["HighValueCustomers is calculated first, making the final SELECT simple."],
          },
          detailedExplanation: ["In modern PostgreSQL, CTEs are inlined by the query planner for optimal execution speed."],
          commonMistakes: [],
          bestPractices: ["Use CTEs instead of deeply nested subqueries to improve code maintainability."],
          summary: ["CTEs provide clean modular structure for complex SQL analytics."],
        },
      ],
    },
    {
      id: "mod-sql-8",
      slug: "window-functions",
      title: "Module 8: Window Functions (ROW_NUMBER, RANK, LEAD, LAG)",
      description: "OVER (PARTITION BY ... ORDER BY ...), ROW_NUMBER, DENSE_RANK, LEAD, LAG, and running totals.",
      lessons: [
        {
          id: "sql-window",
          slug: "window-functions-mastery",
          courseSlug: "sql",
          moduleSlug: "window-functions",
          title: "Window Functions (ROW_NUMBER, RANK, LEAD, LAG)",
          description: "Perform advanced calculations across rows without collapsing them with the OVER (PARTITION BY) clause.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Difference between GROUP BY (collapses rows) and Window functions (retains rows)",
            "Ranking rows with ROW_NUMBER(), RANK(), and DENSE_RANK()",
            "Comparing against previous/next rows with LAG() and LEAD()",
          ],
          introduction: `A window function performs a calculation across a set of table rows that are somehow related to the current row, without collapsing the individual rows into a single summary output.`,
          whyItMatters: `Calculating running totals or month-over-month growth takes 1 line with window functions instead of 5 complex self-joins.`,
          mainExample: {
            title: "Top 3 Products per Category with ROW_NUMBER",
            language: "sql",
            code: `WITH RankedProducts AS (\n    SELECT \n        product_name,\n        category,\n        price,\n        ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC) as rank_in_category\n    FROM products\n)\nSELECT product_name, category, price\nFROM RankedProducts\nWHERE rank_in_category <= 3;`,
            executable: true,
            explanation: ["PARTITION BY category restarts the rank numbering for each category."],
          },
          detailedExplanation: ["LEAD(sales, 1) OVER (ORDER BY month) retrieves the next month's sales value."],
          commonMistakes: [],
          bestPractices: ["Use window functions for ranking, pagination, and time-series delta analysis."],
          summary: ["Window functions unlock advanced analytics without procedural code."],
        },
      ],
    },
    {
      id: "mod-sql-9",
      slug: "indexing-tuning",
      title: "Module 9: Indexing Strategies (B-Tree, Hash, GIN) & EXPLAIN",
      description: "B-Tree index structure, composite indexes, GIN index for JSONB, and reading EXPLAIN ANALYZE.",
      lessons: [
        {
          id: "sql-indexes",
          slug: "indexing-and-explain-analyze",
          courseSlug: "sql",
          moduleSlug: "indexing-tuning",
          title: "B-Tree Indexes & Query Execution Plans (EXPLAIN ANALYZE)",
          description: "Accelerate query performance from seconds to sub-milliseconds using B-Tree indexes and reading EXPLAIN plans.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "How B-Tree indexes enable O(log n) binary search lookup on disk",
            "Composite multi-column indexes and the left-prefix rule",
            "Reading EXPLAIN ANALYZE output: Seq Scan vs Index Scan vs Bitmap Heap Scan",
          ],
          introduction: `An index is a separate data structure on disk (most commonly a balanced B-Tree) that speeds up the retrieval of rows by column value, at the cost of additional write overhead.`,
          whyItMatters: `On a 10,000,000 row table, an unindexed query performs a sequential scan reading 2GB of disk. An index scan touches only 4 tree pages in <1ms.`,
          mainExample: {
            title: "Index Creation & EXPLAIN Plan",
            language: "sql",
            code: `-- Create Composite Index\nCREATE INDEX idx_orders_customer_status ON orders(customer_id, status);\n\n-- Inspect query execution plan\nEXPLAIN ANALYZE\nSELECT * FROM orders\nWHERE customer_id = 'CUST-001' AND status = 'COMPLETED';`,
            executable: true,
            explanation: ["Index scan executes in under 1ms on large datasets."],
          },
          detailedExplanation: ["Indexes speed up SELECT queries but slightly slow down INSERT, UPDATE, and DELETE operations."],
          commonMistakes: [],
          bestPractices: ["Index columns frequently used in WHERE filters, JOIN ON keys, and ORDER BY clauses."],
          summary: ["Proper indexing is the #1 factor in database scalability and throughput."],
        },
      ],
    },
    {
      id: "mod-sql-10",
      slug: "transactions",
      title: "Module 10: Transactions, Isolation Levels & Row Locks",
      description: "BEGIN, COMMIT, ROLLBACK, dirty reads, isolation levels (Read Committed, Serializable), and row locking.",
      lessons: [
        {
          id: "sql-transactions",
          slug: "transactions-and-isolation-levels",
          courseSlug: "sql",
          moduleSlug: "transactions",
          title: "ACID Transactions, Row Locks & Isolation Levels",
          description: "Ensure financial-grade data integrity with transactions, ROLLBACK on errors, and SELECT ... FOR UPDATE locks.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The 4 ACID Pillars: Atomicity, Consistency, Isolation, Durability",
            "Transaction lifecycle: BEGIN, COMMIT, ROLLBACK",
            "Pessimistic locking with SELECT ... FOR UPDATE to prevent race conditions",
          ],
          introduction: `A database transaction is a sequence of multiple database operations executed as a single, atomic unit of work. Either all statements succeed, or the entire batch rolls back completely.`,
          whyItMatters: `In bank transfers, deducting from Account A and adding to Account B must be atomic. If the server crashes mid-way, money cannot vanish into thin air.`,
          mainExample: {
            title: "Atomic Bank Transfer Transaction",
            language: "sql",
            code: `BEGIN;\n\n-- 1. Deduct from sender with row lock\nUPDATE accounts \nSET balance = balance - 100 \nWHERE id = 'acc_sender' AND balance >= 100;\n\n-- 2. Credit to receiver\nUPDATE accounts \nSET balance = balance + 100 \nWHERE id = 'acc_receiver';\n\nCOMMIT; -- All mutations become permanent atomically`,
            executable: true,
            explanation: ["If any error occurs before COMMIT, issuing ROLLBACK restores the original balances."],
          },
          detailedExplanation: ["Isolation levels (Read Committed, Repeatable Read, Serializable) balance concurrency with isolation."],
          commonMistakes: [],
          bestPractices: ["Keep transactions as short as possible to minimize row lock contention."],
          summary: ["ACID transactions guarantee total consistency and crash resilience."],
        },
      ],
    },
    {
      id: "mod-sql-11",
      slug: "schema-design",
      title: "Module 11: Database Normalization & Schema Architecture",
      description: "1NF, 2NF, 3NF normalization, foreign keys, junction tables, and deliberate denormalization.",
      lessons: [
        {
          id: "sql-normalization",
          slug: "normalization-and-schema-architecture",
          courseSlug: "sql",
          moduleSlug: "schema-design",
          title: "Database Normalization (1NF, 2NF, 3NF) & Schema Design",
          description: "Design relational database schemas eliminating redundancy via 1st, 2nd, and 3rd Normal Forms.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "First Normal Form (1NF): Atomic single values and unique primary keys",
            "Second Normal Form (2NF): No partial dependencies on composite keys",
            "Third Normal Form (3NF): No transitive non-key dependencies",
          ],
          introduction: `Database normalization is the process of structuring a relational database in accordance with a series of normal forms in order to reduce data redundancy and improve data integrity.`,
          whyItMatters: `Proper normalization prevents update anomalies where changing a customer's address requires modifying 500 duplicate order rows.`,
          mainExample: {
            title: "Normalized E-Commerce Schema Architecture",
            language: "sql",
            code: `CREATE TABLE categories (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100) NOT NULL\n);\n\nCREATE TABLE products (\n    id SERIAL PRIMARY KEY,\n    category_id INT REFERENCES categories(id),\n    title VARCHAR(200) NOT NULL,\n    price NUMERIC(10, 2) NOT NULL\n);`,
            executable: true,
            explanation: ["Foreign key category_id normalizes category names into a single source of truth."],
          },
          detailedExplanation: ["In high-throughput analytics data warehouses, deliberate denormalization (star schema) is used for speed."],
          commonMistakes: [],
          bestPractices: ["Aim for 3NF for OLTP transactional applications."],
          summary: ["Normalized schemas ensure data consistency and eliminate redundant updates."],
        },
      ],
    },
  ],
};
