import { Course } from "@/types";

export const systemDesignCourse: Course = {
  id: "course-system-design",
  slug: "system-design",
  title: "Large-Scale Distributed System Design",
  tagline: "Architect systems serving millions of users — load balancing, caching, sharding, and microservices.",
  description: "Learn to design highly available, fault-tolerant enterprise architectures: Horizontal vs Vertical scaling, Load Balancers (L4 vs L7), Caching strategies (Redis, CDN), Database replication and sharding, CAP Theorem, Message Queues (Kafka, RabbitMQ), Rate Limiting, and Microservices.",
  category: "System Design",
  level: "Advanced",
  estimatedHours: 28,
  icon: "Layers",
  badgeColor: "amber",
  prerequisites: ["Backend & Database Knowledge"],
  skillsGained: [
    "High Availability & Fault Tolerance Architecture Design",
    "Distributed Caching Strategies (Cache-Aside, Write-Through)",
    "Database Sharding, Partitioning & Master-Replica Topologies",
    "CAP Theorem & Distributed Consensus Analysis",
    "Asynchronous Event-Driven Architectures (Message Brokers)",
  ],
  featured: true,
  modules: [
    {
      id: "mod-sys-1",
      slug: "scalability-intro",
      title: "Module 1: System Design Principles & Scalability",
      description: "Vertical vs horizontal scaling, SLA/SLO/SLI metrics, latency vs throughput, and bottlenecks.",
      lessons: [
        {
          id: "sys-intro",
          slug: "system-design-introduction",
          courseSlug: "system-design",
          moduleSlug: "scalability-intro",
          title: "System Design Foundations & Scalability",
          description: "Understand the core building blocks of systems handling millions of requests per second.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Vertical scaling (scale-up) vs Horizontal scaling (scale-out)",
            "Latency (p50, p95, p99) vs Throughput (RPS)",
            "Availability SLAs (99.9% vs 99.999% 'five nines')",
          ],
          introduction: `System Design is the process of defining architecture, components, modules, interfaces, and data for a system to satisfy specified requirements at scale.`,
          whyItMatters: `Designing distributed systems that remain fast and reliable under high concurrency is one of the most critical skills for senior software engineers.`,
          mainExample: {
            title: "Horizontal Scaling with Stateless Nodes",
            language: "text",
            code: `User Requests -> Anycast DNS -> Load Balancer (Round Robin) -> [Node 1, Node 2, Node 3] -> Shared Database Cluster`,
            takeaway: "Stateless nodes allow horizontal auto-scaling based on CPU load.",
          },
          detailedExplanation: ["Keep application servers stateless by storing session state in distributed caches like Redis."],
          commonMistakes: [],
          bestPractices: ["Always eliminate Single Points of Failure (SPOFs) across every tier."],
          summary: ["Horizontal scaling and stateless architectures enable limitless growth."],
        },
      ],
    },
    {
      id: "mod-sys-2",
      slug: "load-balancing",
      title: "Module 2: Load Balancing (L4 vs L7) & Reverse Proxies",
      description: "Layer 4 transport vs Layer 7 application load balancing, NGINX, HAProxy, and algorithms.",
      lessons: [
        {
          id: "sys-lb",
          slug: "load-balancing-algorithms",
          courseSlug: "system-design",
          moduleSlug: "load-balancing",
          title: "Load Balancers (L4 vs L7) & Consistent Hashing",
          description: "Distribute traffic across server pools using Round Robin, Least Connections, and Consistent Hashing.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Layer 4 (TCP/UDP IP hash) vs Layer 7 (HTTP path, headers, cookies)",
            "Load balancing algorithms: Weighted Round Robin, Least Connections",
            "Consistent Hashing rings to prevent cache stampedes during node scaling",
          ],
          introduction: `Load balancers distribute incoming network traffic across a group of backend servers to maximize throughput, minimize response time, and avoid overload on any single server.`,
          whyItMatters: `Consistent Hashing ensures that when a cache node crashes, only 1/N of keys are remapped rather than invalidating 100% of the cache.`,
          mainExample: {
            title: "Layer 7 HTTP Route Routing",
            language: "nginx",
            code: `upstream api_servers {\n    least_conn;\n    server 10.0.0.1:4000;\n    server 10.0.0.2:4000;\n}\nserver {\n    listen 80;\n    location /api/ {\n        proxy_pass http://api_servers;\n    }\n}`,
            executable: false,
            explanation: ["least_conn routes requests to the server with fewest active connections."],
          },
          detailedExplanation: ["Reverse proxies also provide SSL termination, gzip compression, and DDoS filtering."],
          commonMistakes: [],
          bestPractices: ["Deploy load balancers in active-passive pairs with Virtual IP (VRRP) to prevent LB SPOFs."],
          summary: ["Load balancing distributes concurrency and guarantees high availability."],
        },
      ],
    },
    {
      id: "mod-sys-3",
      slug: "caching",
      title: "Module 3: Distributed Caching (Redis, Memcached, CDN)",
      description: "Cache-aside, write-through, write-behind, eviction policies (LRU, LFU), and cache invalidation.",
      lessons: [
        {
          id: "sys-caching",
          slug: "caching-strategies-and-redis",
          courseSlug: "system-design",
          moduleSlug: "caching",
          title: "Distributed Caching Patterns (Cache-Aside, Write-Through)",
          description: "Accelerate reads to sub-milliseconds using Redis, CDN edge caching, and LRU eviction policies.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Cache-Aside (Lazy loading) vs Write-Through vs Write-Behind",
            "Cache stampede, cache penetration, and cache avalanche mitigation",
            "Eviction policies: Least Recently Used (LRU) vs Least Frequently Used (LFU)",
          ],
          introduction: `Caching stores copies of data in fast, in-memory hardware (like RAM) so that future requests for that data can be served faster.`,
          whyItMatters: `Redis handles 100,000+ operations/second with sub-millisecond latency, shielding primary databases from read overload.`,
          mainExample: {
            title: "Cache-Aside Implementation Pattern",
            language: "javascript",
            code: `async function getCourse(slug) {\n  const cached = await redis.get(\`course:\${slug}\`);\n  if (cached) return JSON.parse(cached);\n  \n  const course = await db.query("SELECT * FROM courses WHERE slug = $1", [slug]);\n  await redis.set(\`course:\${slug}\`, JSON.stringify(course), "EX", 3600);\n  return course;\n}`,
            executable: false,
            explanation: ["Database is queried only on cache miss; cache is populated with 1-hour TTL."],
          },
          detailedExplanation: ["Phil Karlton famously said: 'There are only two hard things in Computer Science: cache invalidation and naming things.'"],
          commonMistakes: [],
          bestPractices: ["Always set a Time-To-Live (TTL) on all cached keys to prevent stale data buildup."],
          summary: ["Caching provides massive read speedups and protects persistent databases."],
        },
      ],
    },
    {
      id: "mod-sys-4",
      slug: "database-scaling",
      title: "Module 4: Database Scaling: Replication, Partitioning & Sharding",
      description: "Master-replica topologies, read replicas, horizontal sharding, and shard key selection.",
      lessons: [
        {
          id: "sys-sharding",
          slug: "database-sharding-and-replication",
          courseSlug: "system-design",
          moduleSlug: "database-scaling",
          title: "Database Replication, Partitioning & Sharding",
          description: "Scale databases past single-machine disk and CPU limits using master-slave replication and horizontal sharding.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Primary-Replica (Master-Slave) replication for read scaling",
            "Horizontal Sharding across multiple database instances based on Shard Key",
            "Handling cross-shard joins and distributed transactions",
          ],
          introduction: `When a single database server runs out of disk space or CPU capacity to process queries, databases scale out horizontally through Replication and Sharding.`,
          whyItMatters: `Sharding splits a 100TB database across 10 database servers of 10TB each based on user_id hashing.`,
          mainExample: {
            title: "Shard Key Routing Logic",
            language: "javascript",
            code: `function getShardDatabase(userId) {\n  const shardCount = 4;\n  const hash = hashFunction(userId);\n  const shardIndex = hash % shardCount;\n  return \`db_shard_\${shardIndex}\`;\n}`,
            executable: false,
            explanation: ["Consistent hashing directs user requests directly to the responsible database shard."],
          },
          detailedExplanation: ["Choosing a poor shard key (like country) causes hotspotting where one shard receives 90% of traffic."],
          commonMistakes: [],
          bestPractices: ["Select high-cardinality, evenly distributed shard keys (like UUID user_id)."],
          summary: ["Replication and sharding scale databases to petabytes of data."],
        },
      ],
    },
    {
      id: "mod-sys-5",
      slug: "cap-theorem",
      title: "Module 5: CAP Theorem & Distributed Consistency",
      description: "Consistency, Availability, Partition Tolerance, PACELC theorem, and eventual consistency.",
      lessons: [
        {
          id: "sys-cap",
          slug: "cap-theorem-and-pacelc",
          courseSlug: "system-design",
          moduleSlug: "cap-theorem",
          title: "The CAP Theorem & Eventual Consistency",
          description: "Understand the fundamental tradeoffs of distributed systems: Consistency (CP) vs Availability (AP) during network partitions.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The 3 pillars of CAP Theorem: Consistency, Availability, Partition Tolerance",
            "Why network partitions (P) are unavoidable in distributed systems",
            "Strong Consistency (PostgreSQL) vs Eventual Consistency (Cassandra, DynamoDB)",
          ],
          introduction: `Eric Brewer's CAP Theorem states that any distributed data store can simultaneously provide at most two out of three guarantees: Consistency, Availability, and Partition Tolerance.`,
          whyItMatters: `When network cables disconnect or routers fail between data centers, you MUST choose between returning an error (CP) or returning potentially stale data (AP).`,
          mainExample: {
            title: "CAP Tradeoff Spectrum",
            language: "text",
            code: `CP (Consistency + Partition Tolerance): Banking, Stock Exchanges (e.g. Spanner, CockroachDB)\nAP (Availability + Partition Tolerance): Social Feeds, DNS, Shopping Carts (e.g. DynamoDB, Cassandra)`,
            takeaway: "Choose CP for financial transactions and AP for high-uptime social streams.",
          },
          detailedExplanation: ["The PACELC theorem extends CAP by evaluating Latency vs Consistency during normal non-partitioned operations."],
          commonMistakes: [],
          bestPractices: ["Design systems with Eventual Consistency unless strict financial correctness is mandatory."],
          summary: ["The CAP theorem defines the fundamental physics of distributed data storage."],
        },
      ],
    },
    {
      id: "mod-sys-6",
      slug: "message-queues",
      title: "Module 6: Asynchronous Message Queues (Kafka, RabbitMQ)",
      description: "Pub/Sub architectures, message brokers, event-driven decoupling, and backpressure buffers.",
      lessons: [
        {
          id: "sys-queues",
          slug: "message-queues-kafka-and-rabbitmq",
          courseSlug: "system-design",
          moduleSlug: "message-queues",
          title: "Message Queues (Kafka, RabbitMQ) & Event-Driven Systems",
          description: "Decouple synchronous microservices using asynchronous message brokers, partition logs, and consumer groups.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Synchronous HTTP request chains vs Asynchronous Event-Driven messaging",
            "RabbitMQ (Smart Broker, Dumb Consumer) vs Apache Kafka (Distributed Commit Log)",
            "At-least-once, at-most-once, and idempotent message consumer processing",
          ],
          introduction: `Message queues enable asynchronous communication between microservices. Instead of Service A waiting for Service B to respond, Service A publishes an event to a queue and immediately returns success to the user.`,
          whyItMatters: `Message queues buffer sudden traffic surges during Black Friday sales, preventing backend database crashes.`,
          mainExample: {
            title: "Asynchronous Order Processing Flow",
            language: "text",
            code: `User Checkout -> Checkout Service -> [Kafka Topic: 'order.created'] \n                                           ├──> Payment Service\n                                           ├──> Email Notification Service\n                                           └──> Inventory Service`,
            takeaway: "Microservices consume events independently without blocking checkout response time.",
          },
          detailedExplanation: ["Idempotency keys guarantee that processing duplicate event deliveries does not charge customers twice."],
          commonMistakes: [],
          bestPractices: ["Always make message consumers idempotent."],
          summary: ["Message queues deliver loose coupling, resilience, and elasticity."],
        },
      ],
    },
    {
      id: "mod-sys-7",
      slug: "api-gateway",
      title: "Module 7: API Gateway & Rate Limiting Algorithms",
      description: "Token Bucket, Leaky Bucket, Sliding Window Log, and API Gateway routing.",
      lessons: [
        {
          id: "sys-rate-limiting",
          slug: "rate-limiting-algorithms-and-api-gateways",
          courseSlug: "system-design",
          moduleSlug: "api-gateway",
          title: "API Gateways & Rate Limiting Algorithms",
          description: "Protect downstream microservices using Token Bucket, Sliding Window Rate Limiters, and API Gateways.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The 4 Rate Limiting Algorithms: Token Bucket, Leaky Bucket, Fixed Window, Sliding Window",
            "Distributed rate limiting with Redis sliding logs and Lua scripts",
            "API Gateway responsibilities: Routing, Auth, Rate Limiting, SSL Termination",
          ],
          introduction: `A rate limiter controls the rate of traffic sent by a client or service. In the HTTP world, a rate limiter limits the number of client requests allowed within a specified time window.`,
          whyItMatters: `Rate limiting defends systems against Denial of Service (DoS) attacks, brute force attempts, and abusive scraping.`,
          mainExample: {
            title: "Token Bucket Algorithm Concept",
            language: "javascript",
            code: `// Token bucket refills at 10 tokens/sec up to capacity of 50 tokens\n// Each API request consumes 1 token; if bucket is empty, return HTTP 429 Too Many Requests\nconsole.log("Token Bucket allows short bursts while enforcing steady long-term limits.");`,
            executable: true,
            explanation: ["Token Bucket permits bursts of traffic while enforcing average rate limits."],
          },
          detailedExplanation: ["Return HTTP 429 Too Many Requests with Retry-After headers when limits are exceeded."],
          commonMistakes: [],
          bestPractices: ["Use Redis Lua scripts for atomic distributed rate limit token increments."],
          summary: ["API Gateways and rate limiting protect microservices from overload and abuse."],
        },
      ],
    },
    {
      id: "mod-sys-8",
      slug: "microservices",
      title: "Module 8: Microservices vs Monolithic Architecture",
      description: "Service boundaries, Domain-Driven Design (DDD), gRPC vs REST, and Saga pattern distributed transactions.",
      lessons: [
        {
          id: "sys-microservices",
          slug: "microservices-and-saga-pattern",
          courseSlug: "system-design",
          moduleSlug: "microservices",
          title: "Microservices Architecture & The Saga Pattern",
          description: "Design modular microservices, communicate via high-speed gRPC, and manage distributed transactions with Sagas.",
          durationMinutes: 22,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Decomposing monoliths using Domain-Driven Design (Bounded Contexts)",
            "High-speed binary communication with gRPC and Protocol Buffers",
            "Distributed transactions using Choreography/Orchestration Sagas and compensating actions",
          ],
          introduction: `Microservices architecture structures an application as a collection of loosely coupled, independently deployable services organized around business domains.`,
          whyItMatters: `Saga patterns coordinate distributed transactions across independent microservice databases using compensating transactions if a step fails.`,
          mainExample: {
            title: "Compensating Saga Transaction",
            language: "text",
            code: `1. Reserve Inventory (Success)\n2. Authorize Payment (Failed!)\n3. [Compensating Action triggered] -> Release Reserved Inventory`,
            takeaway: "Sagas maintain data consistency across distributed databases without distributed 2PC locks.",
          },
          detailedExplanation: ["gRPC uses HTTP/2 multiplexing and Protocol Buffers binary serialization for 5x faster speed than REST/JSON."],
          commonMistakes: [],
          bestPractices: ["Start with a modular monolith; split into microservices only when organizational scaling demands it."],
          summary: ["Microservices enable independent team deployment and specialized service scaling."],
        },
      ],
    },
    {
      id: "mod-sys-9",
      slug: "storage-systems",
      title: "Module 9: Storage Systems: Object, Block & File",
      description: "Object storage (S3), block storage (EBS), file systems (NFS), and LSM-Trees vs B-Trees.",
      lessons: [
        {
          id: "sys-storage",
          slug: "object-block-and-lsm-trees",
          courseSlug: "system-design",
          moduleSlug: "storage-systems",
          title: "Storage Systems: Object (S3), Block (EBS) & LSM-Trees",
          description: "Understand object storage mechanics, block devices, and write-optimized Log-Structured Merge (LSM) trees.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Object Storage (AWS S3) for immutable blobs with 99.999999999% durability",
            "Block Storage (AWS EBS) for high-IOPS database volumes",
            "LSM-Trees (RocksDB, Cassandra) for ultra-fast write-heavy workloads",
          ],
          introduction: `Different workloads require different storage engines: Object Storage for media files, Block Storage for database disk partitions, and LSM-Trees for high-write logging.`,
          whyItMatters: `LSM-Trees append writes sequentially to disk (100x faster than random B-Tree in-place overwrites), making them ideal for time-series and write-heavy systems.`,
          mainExample: {
            title: "LSM-Tree Write Pipeline",
            language: "text",
            code: `Write -> Write-Ahead Log (WAL on disk) -> MemTable (in RAM) -> SSTables (immutable disk files) -> Background Compaction`,
            takeaway: "Sequential disk writes achieve peak write throughput.",
          },
          detailedExplanation: ["Object storage uses erasure coding across multiple availability zones to achieve 11 nines of durability."],
          commonMistakes: [],
          bestPractices: ["Store user uploads (images/videos) in object storage (S3), never inside relational database BLOBs."],
          summary: ["Choosing the right storage architecture determines system performance and durability."],
        },
      ],
    },
    {
      id: "mod-sys-10",
      slug: "observability",
      title: "Module 10: Observability, Metrics & Distributed Tracing",
      description: "The 3 Pillars of Observability (Metrics, Logs, Traces), OpenTelemetry, Prometheus, and Grafana.",
      lessons: [
        {
          id: "sys-observability",
          slug: "metrics-logs-and-distributed-tracing",
          courseSlug: "system-design",
          moduleSlug: "observability",
          title: "The 3 Pillars of Observability & OpenTelemetry",
          description: "Trace distributed microservice requests across 20+ servers using OpenTelemetry trace IDs and Prometheus metrics.",
          durationMinutes: 20,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The 3 Pillars: Metrics (Prometheus), Structured Logs, Distributed Traces (Jaeger/Zipkin)",
            "Propagating W3C Trace Context headers (traceparent) across microservice boundaries",
            "Alerting thresholds on p99 latency regressions and error budgets",
          ],
          introduction: `Observability is the ability to infer the internal states of a system based on its external outputs (Metrics, Logs, and Traces).`,
          whyItMatters: `When an API call takes 4 seconds, distributed tracing pinpoints the exact 3.8-second slow SQL query inside Service #14 instantly.`,
          mainExample: {
            title: "Distributed Trace Span Propagation",
            language: "text",
            code: `Client (TraceID: 4bf92f) -> API Gateway [10ms]\n                             └──> Auth Service [15ms]\n                             └──> Order Service [3800ms] <-- BOTTLENECK FOUND!\n                                   └──> Postgres Query [3750ms]`,
            takeaway: "Distributed spans pinpoint root-cause latency bottlenecks in complex architectures.",
          },
          detailedExplanation: ["OpenTelemetry is the vendor-neutral Cloud Native Computing Foundation (CNCF) standard for telemetry."],
          commonMistakes: [],
          bestPractices: ["Instrument automated alerting on p99 latency spikes before users notice."],
          summary: ["Observability provides visibility and rapid root-cause diagnosis in distributed architectures."],
        },
      ],
    },
    {
      id: "mod-sys-11",
      slug: "case-studies",
      title: "Module 11: Designing Large-Scale Systems (URL Shortener, Feed, Chat)",
      description: "Step-by-step system design blueprints: TinyURL, Twitter Newsfeed, WhatsApp Chat, and YouTube Video Streaming.",
      lessons: [
        {
          id: "sys-case-studies",
          slug: "system-design-interview-blueprints",
          courseSlug: "system-design",
          moduleSlug: "case-studies",
          title: "End-to-End System Design Blueprint (TinyURL & Feed)",
          description: "Master the 4-step framework for system design interviews: Requirements, Back-of-the-Envelope Math, High-Level Architecture, and Deep Dives.",
          durationMinutes: 24,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "The 4-step System Design Interview Framework",
            "Back-of-the-envelope calculations for storage, bandwidth, and QPS",
            "Designing a globally scalable URL Shortener (Base62 encoding, KGS, Redis cache)",
          ],
          introduction: `Putting all system design components together: using the standard framework to design scalable, production-grade systems from requirements to trade-offs.`,
          whyItMatters: `Mastering back-of-the-envelope calculations allows you to accurately size server memory, disk storage, and network bandwidth before writing code.`,
          mainExample: {
            title: "TinyURL Architecture Blueprint",
            language: "text",
            code: `User -> Route53 DNS -> CDN -> L7 Load Balancer -> Web Nodes -> Redis Cache -> MongoDB Cluster / Key Generation Service (KGS)`,
            takeaway: "Pre-generating Base62 keys in a Key Generation Service eliminates URL collision locking.",
          },
          detailedExplanation: ["Always address bottlenecks, single points of failure, and data replication trade-offs in design reviews."],
          commonMistakes: [],
          bestPractices: ["Always clarify functional vs non-functional requirements (Availability vs Consistency) first."],
          summary: ["System design blueprints turn complex real-world scaling challenges into structured, elegant architectures."],
        },
      ],
    },
  ],
};
