import { Course } from "@/types";

export const typescriptCourse: Course = {
  id: "course-typescript",
  slug: "typescript",
  title: "TypeScript Enterprise Architecture",
  tagline: "Type-safe JavaScript for scalable web development, interfaces, generics, and compiler options.",
  description: "Master TypeScript: static typing, primitive types, union & intersection types, interfaces, type aliases, generics, utility types (Partial, Omit, Pick), type narrowing, and strict tsconfig settings.",
  category: "Programming Languages",
  level: "Intermediate",
  estimatedHours: 24,
  icon: "Code2",
  badgeColor: "blue",
  prerequisites: ["JavaScript Fundamentals"],
  skillsGained: [
    "Static Type System & Type Inference Mechanics",
    "Interfaces, Type Aliases & Extending Contracts",
    "Generics (<T>) & Constrained Type Parameters",
    "Type Narrowing (typeof, instanceof, type guards, discriminated unions)",
    "Utility Types (Partial, Record, Readonly, ReturnType, Omit)",
  ],
  featured: true,
  modules: [
    {
      id: "mod-ts-1",
      slug: "intro",
      title: "Module 1: TypeScript Compiler & Configuration",
      description: "tsc CLI, tsconfig.json strict flags, and compile-time verification.",
      lessons: [
        {
          id: "ts-intro",
          slug: "typescript-introduction",
          courseSlug: "typescript",
          moduleSlug: "intro",
          title: "TypeScript Introduction & The Compiler (tsc)",
          description: "Discover why TypeScript is standard in modern software engineering, type annotations, and compiling to JavaScript.",
          durationMinutes: 15,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Compile-time static type checking vs runtime JavaScript errors",
            "Configuring tsconfig.json with strict mode",
            "Basic type annotations (string, number, boolean, arrays, tuples)",
          ],
          introduction: `TypeScript is a typed superset of JavaScript developed by Microsoft. It adds static type checking to JavaScript, allowing developers to catch type bugs during development.`,
          whyItMatters: `Studies show that over 15% of all production JavaScript bugs are preventable with static typing.`,
          mainExample: {
            title: "Interface & Function Typing",
            language: "typescript",
            code: `interface Developer {\n  id: string;\n  name: string;\n  skills: string[];\n}\n\nfunction printDevSummary(dev: Developer): string {\n  return \`\${dev.name} specializes in: \${dev.skills.join(", ")}\`;\n}\n\nconst alex: Developer = { id: "usr_1", name: "Alex", skills: ["TypeScript", "Next.js"] };\nconsole.log(printDevSummary(alex));`,
            executable: true,
            explanation: ["interface defines an explicit shape contract enforced at compile time."],
          },
          detailedExplanation: ["TypeScript compiler strips away all type annotations, leaving clean, standard JavaScript code."],
          commonMistakes: [],
          bestPractices: ["Enable 'strict: true' in your tsconfig.json."],
          summary: ["TypeScript provides compile-time safety and world-class IDE autocompletion."],
        },
      ],
    },
    {
      id: "mod-ts-2",
      slug: "basic-types",
      title: "Module 2: Basic Types, Tuples & Enums",
      description: "Primitive types, any vs unknown, void vs never, fixed-length tuples, and enums.",
      lessons: [
        {
          id: "ts-types",
          slug: "primitives-tuples-and-enums",
          courseSlug: "typescript",
          moduleSlug: "basic-types",
          title: "Tuples, Enums & Unknown vs Any",
          description: "Master fixed-length array tuples, numeric/string enums, and the type-safe 'unknown' primitive.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Tuples with fixed length and explicit element types",
            "String literal unions vs TypeScript enums",
            "Why 'unknown' is 100% safer than 'any'",
          ],
          introduction: `TypeScript extends JavaScript primitives with strict types like Tuples (fixed-size array models) and the 'unknown' top type.`,
          whyItMatters: `Unlike 'any' which completely turns off type checking, 'unknown' forces developers to verify the type before accessing properties.`,
          mainExample: {
            title: "Type-Safe Unknown Handling",
            language: "typescript",
            code: `function handleData(input: unknown) {\n  if (typeof input === "string") {\n    console.log("String Length:", input.length); // Safe!\n  }\n}\n\nhandleData("KWAS Academy");`,
            executable: true,
            explanation: ["typeof check narrows unknown to string safely."],
          },
          detailedExplanation: ["Always prefer string literal unions ('admin' | 'user') over numeric enums in modern TypeScript."],
          commonMistakes: [],
          bestPractices: ["Never use 'any'; use 'unknown' when dealing with dynamic external API responses."],
          summary: ["Strict types eliminate unexpected runtime type errors."],
        },
      ],
    },
    {
      id: "mod-ts-3",
      slug: "interfaces-types",
      title: "Module 3: Interfaces & Type Aliases",
      description: "Defining object contracts, extending interfaces, intersection types, and declaration merging.",
      lessons: [
        {
          id: "ts-interfaces",
          slug: "interfaces-and-type-aliases",
          courseSlug: "typescript",
          moduleSlug: "interfaces-types",
          title: "Interfaces vs Type Aliases & Extending Contracts",
          description: "Learn when to use interface vs type, extending with 'extends' or '&', and readonly/optional properties.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Interface inheritance with the 'extends' keyword",
            "Type aliases for primitives, unions, and tuples",
            "Readonly and optional (?) property modifiers",
          ],
          introduction: `Interfaces and Type Aliases both define object shapes, but have distinct capabilities regarding declaration merging and union representations.`,
          whyItMatters: `Interfaces are ideal for open public API definitions, while type aliases excel at complex unions and mapped transformations.`,
          mainExample: {
            title: "Extended Interface Hierarchy",
            language: "typescript",
            code: `interface Identifiable {\n  readonly id: string;\n}\n\ninterface UserProfile extends Identifiable {\n  name: string;\n  email: string;\n  avatarUrl?: string;\n}\n\nconst user: UserProfile = {\n  id: "usr_101",\n  name: "Alex Dev",\n  email: "alex@kwas.dev"\n};\nconsole.log("User:", user.name);`,
            executable: true,
            explanation: ["readonly prevents property reassignment."],
          },
          detailedExplanation: ["Interfaces support declaration merging across multiple declaration files."],
          commonMistakes: [],
          bestPractices: ["Use interface for object models and type for unions/primitives."],
          summary: ["Interfaces and type aliases form the structural bedrock of TypeScript."],
        },
      ],
    },
    {
      id: "mod-ts-4",
      slug: "unions-intersections",
      title: "Module 4: Union, Intersection & Literal Types",
      description: "Combining types with | (OR) and & (AND), literal types, and template literal types.",
      lessons: [
        {
          id: "ts-unions",
          slug: "union-and-intersection-types",
          courseSlug: "typescript",
          moduleSlug: "unions-intersections",
          title: "Union (|) & Intersection (&) Types",
          description: "Model complex real-world data structures with union types and merge contracts with intersections.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Union types (|) for values that can be one of several types",
            "Intersection types (&) to combine multiple object shapes",
            "Template literal types (e.g. `on${Capitalize<string>}`)",
          ],
          introduction: `Union and intersection types allow you to compose existing types into sophisticated, expressive domain models.`,
          whyItMatters: `Unions model states like 'pending' | 'success' | 'error' without messy numeric flags.`,
          mainExample: {
            title: "Union State & Intersection Merge",
            language: "typescript",
            code: `type Status = "idle" | "loading" | "success" | "error";\n\ntype Timestamps = { createdAt: Date; updatedAt: Date };\ntype Article = { title: string; body: string };\ntype PersistedArticle = Article & Timestamps;\n\nconsole.log("Composed persistent entity types cleanly.");`,
            executable: true,
            explanation: ["PersistedArticle has all 4 properties from both types."],
          },
          detailedExplanation: ["Unions require type narrowing before accessing member-specific properties."],
          commonMistakes: [],
          bestPractices: ["Use literal unions for finite state machines."],
          summary: ["Unions and intersections provide flexible type composition."],
        },
      ],
    },
    {
      id: "mod-ts-5",
      slug: "functions",
      title: "Module 5: Functions, Signatures & Overloads",
      description: "Function parameter typing, return inference, optional parameters, and function overloads.",
      lessons: [
        {
          id: "ts-func-overloads",
          slug: "function-signatures-and-overloads",
          courseSlug: "typescript",
          moduleSlug: "functions",
          title: "Function Types, Callbacks & Overloads",
          description: "Write type-safe functions with explicit return types, callback signatures, and overload definitions.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Typing higher-order callback arguments ((item: T) => boolean)",
            "Declaring function overloads for multiple call signatures",
            "Return type annotations vs automatic type inference",
          ],
          introduction: `Functions in TypeScript can specify parameter types, return types, and multiple overload signatures for polymorphic behavior.`,
          whyItMatters: `Function overloads allow a single function to return different types based on the input argument type.`,
          mainExample: {
            title: "Function Overload Signatures",
            language: "typescript",
            code: `function format(value: string): string;\nfunction format(value: number): string;\nfunction format(value: string | number): string {\n  return typeof value === "number" ? \`$\${value.toFixed(2)}\` : value.trim();\n}\n\nconsole.log(format(129.5));\nconsole.log(format("  KWAS  "));`,
            executable: true,
            explanation: ["Overload signatures provide precise autocompletion for each argument type."],
          },
          detailedExplanation: ["The implementation signature at the bottom is not visible to callers."],
          commonMistakes: [],
          bestPractices: ["Always annotate return types on exported public API functions."],
          summary: ["Function typing ensures type safety across functional invocation boundaries."],
        },
      ],
    },
    {
      id: "mod-ts-6",
      slug: "generics",
      title: "Module 6: Generics & Constrained Type Parameters",
      description: "Generic functions, classes, interfaces, generic constraints (extends), and keyof operator.",
      lessons: [
        {
          id: "ts-generics",
          slug: "typescript-generics",
          courseSlug: "typescript",
          moduleSlug: "generics",
          title: "Generics (<T>) & Constrained Type Parameters",
          description: "Learn how to write reusable, type-safe functions, classes, and interfaces that work with multiple data types.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "What Generics are and why they avoid type duplication",
            "Type constraints using extends keyword (e.g. <T extends Identifiable>)",
            "Built-in Utility Types: Partial, Pick, Omit, and Record",
          ],
          introduction: `Generics allow you to write reusable code components that work with a variety of types rather than a single one.`,
          whyItMatters: `Generics power UI state hooks, database ORMs, state management stores, and type-safe HTTP clients.`,
          mainExample: {
            title: "Generic Stack Data Structure",
            language: "typescript",
            code: `class Stack<T> {\n  private items: T[] = [];\n  push(item: T): void { this.items.push(item); }\n  pop(): T | undefined { return this.items.pop(); }\n}\n\nconst nums = new Stack<number>();\nnums.push(42);\nconsole.log("Popped:", nums.pop());`,
            executable: true,
            explanation: ["Stack<T> guarantees type consistency across push and pop operations."],
          },
          detailedExplanation: ["Use keyof T to constrain generic parameters to existing object property names."],
          commonMistakes: [],
          bestPractices: ["Use descriptive generic names (e.g. <TResponse, TError>) when multiple exist."],
          summary: ["Generics enable maximum code reusability without sacrificing static type safety."],
        },
      ],
    },
    {
      id: "mod-ts-7",
      slug: "type-narrowing",
      title: "Module 7: Type Narrowing & Discriminated Unions",
      description: "Type guards (typeof, instanceof), user-defined type predicates (is), and discriminated unions.",
      lessons: [
        {
          id: "ts-narrowing",
          slug: "type-narrowing-and-predicates",
          courseSlug: "typescript",
          moduleSlug: "type-narrowing",
          title: "Discriminated Unions & Custom Type Predicates",
          description: "Eliminate impossible UI states using discriminated union tagged objects and custom 'x is Type' predicates.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Discriminated Unions with common literal tag properties",
            "Writing custom user-defined type guards (is fish)",
            "Exhaustiveness checking with the 'never' type",
          ],
          introduction: `Type narrowing is the process by which TypeScript refines a broad type (like string | number) into a specific type based on conditional checks.`,
          whyItMatters: `Discriminated unions make invalid application states mathematically impossible to represent.`,
          mainExample: {
            title: "Discriminated Union State Handler",
            language: "typescript",
            code: `type AsyncState<T> =\n  | { status: "loading" }\n  | { status: "success"; data: T }\n  | { status: "error"; error: string };\n\nfunction renderUI(state: AsyncState<string[]>) {\n  if (state.status === "success") {\n    console.log("Loaded items:", state.data.length);\n  }\n}\n\nrenderUI({ status: "success", data: ["HTML", "CSS"] });`,
            executable: true,
            explanation: ["TypeScript knows state.data exists only inside the 'success' branch."],
          },
          detailedExplanation: ["Exhaustive checks with 'never' ensure you handle every union branch in switch statements."],
          commonMistakes: [],
          bestPractices: ["Always tag state representations with a common 'status' or 'kind' property."],
          summary: ["Discriminated unions provide bulletproof state machine modeling in TypeScript."],
        },
      ],
    },
    {
      id: "mod-ts-8",
      slug: "utility-types",
      title: "Module 8: Built-in Utility Types & Mapped Types",
      description: "Partial, Required, Readonly, Record, Pick, Omit, ReturnType, and Parameters.",
      lessons: [
        {
          id: "ts-utilities",
          slug: "utility-and-mapped-types",
          courseSlug: "typescript",
          moduleSlug: "utility-types",
          title: "Built-in Utility Types (Partial, Omit, Pick, Record)",
          description: "Transform existing interfaces effortlessly with standard TypeScript utility types.",
          durationMinutes: 18,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Partial<T> and Required<T> modifiers",
            "Filtering properties with Pick<T, K> and Omit<T, K>",
            "Key-value dictionaries with Record<Keys, Type>",
          ],
          introduction: `TypeScript includes standard global utility types that facilitate common type transformations without manual re-typing.`,
          whyItMatters: `Using Omit<User, 'id'> ensures updates never accidentally re-declare duplicate properties.`,
          mainExample: {
            title: "Utility Types in Action",
            language: "typescript",
            code: `interface User {\n  id: string;\n  name: string;\n  email: string;\n  role: string;\n}\n\n// Create payload without id\ntype CreateUserDto = Omit<User, "id">;\n\n// Patch payload with optional fields\ntype UpdateUserDto = Partial<CreateUserDto>;\n\nconsole.log("Utility types prevent schema drift.");`,
            executable: true,
            explanation: ["Omit removes specified keys; Partial marks all remaining fields optional."],
          },
          detailedExplanation: ["ReturnType<typeof fn> extracts the return value type of any function."],
          commonMistakes: [],
          bestPractices: ["Use Pick and Omit for API request/response transfer objects (DTOs)."],
          summary: ["Utility types supercharge type transformation and eliminate code duplication."],
        },
      ],
    },
    {
      id: "mod-ts-9",
      slug: "classes-decorators",
      title: "Module 9: Classes, Decorators & Object-Oriented TS",
      description: "Access modifiers (private, protected, public), parameter properties, and Stage 3 decorators.",
      lessons: [
        {
          id: "ts-oop",
          slug: "classes-and-access-modifiers",
          courseSlug: "typescript",
          moduleSlug: "classes-decorators",
          title: "Access Modifiers & Parameter Properties",
          description: "Encapsulate class internals with private, protected, readonly, and concise parameter property constructors.",
          durationMinutes: 16,
          difficulty: "Intermediate",
          whatYouWillLearn: [
            "Compile-time access modifiers (private, protected, public)",
            "ECMAScript native private fields (#field)",
            "Constructor parameter properties for instant field binding",
          ],
          introduction: `TypeScript extends JavaScript classes with visibility modifiers, abstract classes, and concise constructor parameter initialization.`,
          whyItMatters: `Parameter properties turn 5-line constructor boilerplate into a single elegant line.`,
          mainExample: {
            title: "Parameter Properties & Private State",
            language: "typescript",
            code: `class BankAccount {\n  // Parameter property initializes and assigns fields automatically\n  constructor(\n    public readonly accountId: string,\n    private balance: number\n  ) {}\n\n  getBalance(): number {\n    return this.balance;\n  }\n}\n\nconst acc = new BankAccount("ACC-1", 500);\nconsole.log("Account:", acc.accountId, "| Balance: $" + acc.getBalance());`,
            executable: true,
            explanation: ["public/private keywords in constructor create and assign class members automatically."],
          },
          detailedExplanation: ["Abstract classes define contracts with partial implementation for child subclasses."],
          commonMistakes: [],
          bestPractices: ["Use parameter properties to eliminate repetitive constructor assignments."],
          summary: ["Classes and access modifiers provide enterprise object-oriented encapsulation."],
        },
      ],
    },
    {
      id: "mod-ts-10",
      slug: "declarations",
      title: "Module 10: Module Declarations & Ambient Namespaces",
      description: ".d.ts type definition files, declare module, @types packages, and global augmentation.",
      lessons: [
        {
          id: "ts-declarations",
          slug: "type-declaration-files",
          courseSlug: "typescript",
          moduleSlug: "declarations",
          title: "Type Definition Files (.d.ts) & Ambient Types",
          description: "Author type definition files (.d.ts), augment third-party modules, and consume @types packages.",
          durationMinutes: 16,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "How .d.ts files describe JavaScript libraries to TypeScript",
            "Module augmentation to add custom properties to global Window or Express.Request",
            "The role of DefinitelyTyped and @types/* packages",
          ],
          introduction: `Type declaration files (.d.ts) contain only type metadata without executable runtime JavaScript code, bridging non-TypeScript libraries with the compiler.`,
          whyItMatters: `Module augmentation allows you to attach user authentication objects to Express Request types without compiler errors.`,
          mainExample: {
            title: "Express Request Type Augmentation",
            language: "typescript",
            code: `// types/express.d.ts\ndeclare global {\n  namespace Express {\n    interface Request {\n      user?: { id: string; role: string };\n    }\n  }\n}\nconsole.log("Ambient declaration files augment global types.");`,
            executable: true,
            explanation: ["declare global extends existing framework types with custom properties."],
          },
          detailedExplanation: [".d.ts files are automatically generated when tsconfig.json has 'declaration: true'."],
          commonMistakes: [],
          bestPractices: ["Store custom type declarations in a dedicated src/types/ folder."],
          summary: ["Declaration files enable seamless interoperability across the entire JavaScript ecosystem."],
        },
      ],
    },
    {
      id: "mod-ts-11",
      slug: "enterprise-ts",
      title: "Module 11: Strict tsconfig & Enterprise Best Practices",
      description: "strictNullChecks, noImplicitAny, monorepo project references, and linting rules.",
      lessons: [
        {
          id: "ts-enterprise",
          slug: "strict-tsconfig-and-best-practices",
          courseSlug: "typescript",
          moduleSlug: "enterprise-ts",
          title: "Production tsconfig.json & Monorepo Architecture",
          description: "Configure enterprise-grade TypeScript projects with strict compiler options and project references.",
          durationMinutes: 18,
          difficulty: "Advanced",
          whatYouWillLearn: [
            "Strict compiler options (strictNullChecks, noImplicitAny, noUncheckedIndexedAccess)",
            "Configuring path aliases (@/*) for clean imports",
            "TypeScript Project References for blazing fast monorepo builds",
          ],
          introduction: `Configuring TypeScript with strict settings ensures maximum type safety and prevents developers from slipping untyped code into production.`,
          whyItMatters: `Enabling noUncheckedIndexedAccess catches out-of-bounds array lookups before they cause runtime undefined crashes.`,
          mainExample: {
            title: "Production tsconfig.json Preset",
            language: "json",
            code: `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "strict": true,\n    "noImplicitAny": true,\n    "strictNullChecks": true,\n    "noUncheckedIndexedAccess": true,\n    "baseUrl": ".",\n    "paths": { "@/*": ["src/*"] }\n  }\n}`,
            executable: false,
            explanation: ["Strict flags enforce total compile-time verification across the codebase."],
          },
          detailedExplanation: ["Project references allow separate packages in a monorepo to compile independently in parallel."],
          commonMistakes: [],
          bestPractices: ["Always keep strict mode enabled from the very beginning of a project."],
          summary: ["A strict compiler configuration guarantees long-term codebase health and scalability."],
        },
      ],
    },
  ],
};
